
select aliquot_label, aliquot_id, in_stock from aliquot_masters where in_stock IN ('','availlable');

-- ----------------------------------------------------------------------------------------------------
-- Add range file option
-- ----------------------------------------------------------------------------------------------------

UPDATE structure_fields SET type = 'input', setting = 'size=30,class=range file' WHERE field = 'participant_identifier';
UPDATE structure_fields SET type = 'input', setting = 'size=30,class=range file' WHERE field = 'aliquot_label';
UPDATE structure_fields SET type = 'input', setting = 'size=30,class=range file' WHERE field = 'misc_identifier_value' AND model LIKE 'View%';

-- ----------------------------------------------------------------------------------------------------
-- Create adriana report : Tissue DNA summary
-- ----------------------------------------------------------------------------------------------------

INSERT INTO `datamart_reports` (`id`, `name`, `description`, `form_alias_for_search`, `form_alias_for_results`, `form_type_for_results`, `function`, `flag_active`) 
VALUES
(null, 'qc_lady_report_tissue_dna_summary', 'qc_lady_report_tissue_dna_summary_desc', 'qc_lady_report_tissue_dna_summary_params', 'qc_lady_report_tissue_dna_summary_results', 'index', 'tissueDNASummary', 1);
INSERT INTO `datamart_structure_functions` (`id`, `datamart_structure_id`, `label`, `link`, `flag_active`, `ref_single_fct_link`) VALUES
(null, (SELECT id FROM datamart_structures WHERE model = 'Participant'), 'qc_lady_report_tissue_dna_summary creation', (SELECT CONCAT('/Datamart/Reports/manageReport/',id) FROM datamart_reports WHERE name = 'qc_lady_report_tissue_dna_summary'), 1, '');
INSERT INTO `datamart_structure_functions` (`id`, `datamart_structure_id`, `label`, `link`, `flag_active`, `ref_single_fct_link`) VALUES
(null, (SELECT id FROM datamart_structures WHERE model = 'ViewAliquot'), 'qc_lady_report_tissue_dna_summary creation', (SELECT CONCAT('/Datamart/Reports/manageReport/',id) FROM datamart_reports WHERE name = 'qc_lady_report_tissue_dna_summary'), 1, '');

INSERT INTO structures(`alias`) VALUES ('qc_lady_report_tissue_dna_summary_params');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_params'), (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label'), '0', '1', '', '1', 'tissue block aliquot label', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'),
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_params'), (SELECT id FROM structure_fields WHERE `model`='ViewCollection' AND `tablename`='' AND `field`='misc_identifier_value'), '0', '2', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'),
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_params'), (SELECT id FROM structure_fields WHERE `model`='ViewCollection' AND `tablename`='' AND `field`='participant_identifier'), '0', '3', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');

INSERT INTO structures(`alias`) VALUES ('qc_lady_report_tissue_dna_summary_results');
INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Datamart', 'Generated', '', 'qc_lady_qc_nano_drop_rna_yield_ug', 'input',  NULL , '0', 'size=5', '', '', 'nano drop rna yield ug', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_nano_drop_rna_260_280', 'input',  NULL , '0', 'size=5', '', '', 'nano drop rna 260/280', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_bioanalyzer_rna_yield_ug', 'input',  NULL , '0', 'size=5', '', '', 'bioanalyzer rna yield ug', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_bioanalyzer_rna_rin', 'input',  NULL , '0', 'size=5', '', '', 'bioanalyzer rna rin', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_nano_drop_dna_yield_ug', 'input',  NULL , '0', 'size=5', '', '', 'nano drop dna yield ug', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_nano_drop_dna_260_280', 'input',  NULL , '0', 'size=5', '', '', 'nano drop dna 260/280', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_pico_green_dna_yield_ug', 'input',  NULL , '0', 'size=5', '', '', 'pico green dna yield ug', ''),
('Datamart', 'Generated', '', 'qc_lady_qc_rna_sample_code', 'input',  NULL , '0', 'size=5', '', '', 'rna sample code', ''), 
('Datamart', 'Generated', '', 'qc_lady_qc_dna_sample_code', 'input',  NULL , '0', 'size=5', '', '', 'dna sample code', '');
DELETE FROM structure_formats WHERE structure_id = (SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0'), '0', '1', '', '1', 'tissue block aliquot label', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='ViewCollection' AND `tablename`='' AND `field`='misc_identifier_value' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=30,class=range file' AND `default`='' AND `language_help`='' AND `language_label`='bank identifier' AND `language_tag`=''), '0', '2', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='ViewCollection' AND `tablename`='' AND `field`='participant_identifier' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=30,class=range file' AND `default`='' AND `language_help`='' AND `language_label`='participant identifier' AND `language_tag`=''), '0', '3', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='ViewCollection' AND `tablename`='' AND `field`='qc_lady_specimen_type_precision' AND `type`='select' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='qc_lady_collection_specimen_type_precision')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='collection specimen type' AND `language_tag`=''), '0', '4', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotDetail' AND `tablename`='' AND `field`='qc_lady_storage_solution' AND `type`='select' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='qc_lady_tissue_tube_storage_solution')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='contains' AND `language_tag`=''), '0', '10', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotDetail' AND `tablename`='' AND `field`='qc_lady_storage_method' AND `type`='select' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='qc_lady_tissue_tube_storage_method')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='storage method' AND `language_tag`=''), '0', '11', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotReviewDetail' AND `tablename`='qc_lady_ar_qcrocs' AND `field`='tumor_percentage' AND `type`='float' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='tumor percentage' AND `language_tag`=''), '0', '20', 'block review', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotReviewDetail' AND `tablename`='qc_lady_ar_qcrocs' AND `field`='necrosis_percentage_itz' AND `type`='float' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='necrosis percentage' AND `language_tag`=''), '0', '22', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotReviewDetail' AND `tablename`='qc_lady_ar_qcrocs' AND `field`='cellularity_percentage_itz' AND `type`='float' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='cellularity percentage' AND `language_tag`=''), '0', '21', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='AliquotReviewDetail' AND `tablename`='qc_lady_ar_qcrocs' AND `field`='stroma_percentage_itz' AND `type`='float' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='stroma percentage' AND `language_tag`=''), '0', '23', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_nano_drop_rna_yield_ug' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='nano drop rna yield ug' AND `language_tag`=''), '0', '31', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_nano_drop_rna_260_280' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='nano drop rna 260/280' AND `language_tag`=''), '0', '32', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_bioanalyzer_rna_yield_ug' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='bioanalyzer rna yield ug' AND `language_tag`=''), '0', '33', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_bioanalyzer_rna_rin' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='bioanalyzer rna rin' AND `language_tag`=''), '0', '34', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_nano_drop_dna_yield_ug' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='nano drop dna yield ug' AND `language_tag`=''), '0', '41', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_nano_drop_dna_260_280' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='nano drop dna 260/280' AND `language_tag`=''), '0', '42', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_pico_green_dna_yield_ug' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='pico green dna yield ug' AND `language_tag`=''), '0', '43', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_rna_sample_code' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='rna sample code' AND `language_tag`=''), '0', '30', 'rna quality controls', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0'), 
((SELECT id FROM structures WHERE alias='qc_lady_report_tissue_dna_summary_results'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='qc_lady_qc_dna_sample_code' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=5' AND `default`='' AND `language_help`='' AND `language_label`='dna sample code' AND `language_tag`=''), '0', '40', 'dna quality controls', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0');

INSERT IGNORE INTO i18n (id,en,fr) VALUES 
('qc_lady_report_tissue_dna_summary', 'Tissue DNA Summary', 'Résumé - ADN de tissu'),
('qc_lady_report_tissue_dna_summary creation', 'Create ''Tissue DNA Summary''', 'Créer ''Résumé - ADN de tissu'''),
('qc_lady_report_tissue_dna_summary_desc','Will list tissue type, tissue review then quality controls linked to a tissue DNA','Liste le type du tissu, les résultats du rapport d''histologie et les contrôles de qualité attachés à un ADN de tissu.'),
('tissue block aliquot label', 'Tissue Block Label', 'Étiquette du bloc (tissu)'),
('block review','Block Review','Analyse de bloc'),
('rna quality controls','QC - RNA','QC - ARN'),
('dna quality controls','QC - DNA','QC - ADN'),
('rna sample code' , 'RNA System Code','ARN - Code système'),
('dna sample code' , 'DNA System Code','ADN - Code système'),
('nano drop rna yield ug','RNA Yield (ug/NanoDrop)','Quantité ARN (ug/NanoDrop)'),
('nano drop rna 260/280','RNA 260/280 (NanoDrop)','ARN 260/280 (NanoDrop)'),
('bioanalyzer rna yield ug','RNA Yield (ug/Bioanalyzer)','Quantité ARN (ug/Bioanalyzer)'),
('bioanalyzer rna rin','RNA RIN (Bioanalyzer)','ARN RIN (Bioanalyzer)'),
('nano drop dna yield ug','DNA Yield (ug/NanoDrop)','Quantité ADN (ug/NanoDrop)'),
('nano drop dna 260/280','DNA 260/280 (NanoDrop)','ADN 260/280 (NanoDrop)'),
('pico green dna yield ug','DNA Yield (ug/PicoGreen)','Quantité ADN (ug/PicoGreen)'),
('concentration unit missing','Concentration unit missing','Unité de concentration manquant'),
('at least one criteria has to be entered','At least one criteria has to be entered','Au moins un critère doit être saisi'),
('no aliquot label search based on range defintion is supported', 'No aliquot label search based on range defintion is supported', 'Aucune recherche sur l''étiquette de l''aliquot par défintion d''un interval n''est pris en compte'),
('no bank identifier search based on range defintion is supported', 'No bank identifier search search based on range defintion is supported', 'Aucune recherche sur l''identifiant de banque par défintion d''un interval n''est pris en compte'),
('some blocks are linked to many aliquots source', 'Some blocks are linked to many aliquots source', 'Certains blocs sont attachés à plusieurs aliquots ''source'''),
('some blocks have been attached to many reviews', 'Some blocks have been attached to many reviews','Certains blocs sont attachés à plusieurs analyse de bloc');

UPDATE versions SET build_number = '5286' WHERE version_number = '2.5.4';
UPDATE versions SET permissions_regenerated = 0;