<?php

class AliquotMasterCustom extends AliquotMaster
{

    var $useTable = 'aliquot_masters';

    var $name = 'AliquotMaster';

    public function regenerateAliquotBarcode()
    {
        $queryToUpdate = "UPDATE aliquot_masters SET barcode = CONCAT('ATiM#', id) WHERE barcode IS NULL OR barcode LIKE '';";
        $this->tryCatchQuery($queryToUpdate);
        $this->tryCatchQuery(str_replace("aliquot_masters", "aliquot_masters_revs", $queryToUpdate));
    }
    
    public function validates($options = array())
    {
        $validate = parent::validates($options);
        // Validate barcode is different than barcodes generated by the system
        if (isset($this->data['AliquotMaster']['barcode']) && !$this->id && preg_match('/^atim#/i', $this->data['AliquotMaster']['barcode'])) {
            $this->validationErrors['barcode'][] = 'error barcode should be different than system barcode';
            $validate = false;
        }
        return $validate;
    }
}