-- TFRI AML/MDS Custom Script
-- Version: v0.7
-- ATiM Version: v2.5.4

-- Update bank name for version tracking during customization
REPLACE INTO `i18n` (`id`, `en`, `fr`)
	VALUES ('core_installname', 'TFRI MDS/AML Biobank v0.7 DEV', '');
	
	
-- Eventum ID: 2920	- Profile headings
UPDATE structure_formats SET `language_heading`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='participants' AND `field`='tfri_aml_chemo_start' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

REPLACE INTO `i18n` (`id`, `en`, `fr`)
	VALUES ('clin_demographics', 'Study Registration', '');
	
-- Eventum ID: 2951 - Profile - Move date fields
UPDATE structure_formats SET `display_column`='1', `display_order`='0', `language_heading`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='participants' AND `field`='tfri_aml_date_registration' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

-- Eventum ID: 2952 - Profile - Add date of acknowledgement
ALTER TABLE `participants` 
ADD COLUMN `tfri_aml_date_acknowledgement` DATE NULL DEFAULT NULL AFTER `tfri_aml_date_registration`;

ALTER TABLE `participants_revs` 
ADD COLUMN `tfri_aml_date_acknowledgement` DATE NULL DEFAULT NULL AFTER `tfri_aml_date_registration`;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'Participant', 'participants', 'tfri_aml_date_acknowledgement', 'date',  NULL , '0', '', '', '', 'tfri aml date acknowledgement', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='participants'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='participants' AND `field`='tfri_aml_date_acknowledgement' AND `type`='date' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='tfri aml date acknowledgement' AND `language_tag`=''), '2', '75', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');

UPDATE structure_fields SET  `language_help`='tfri study acknowledgement' WHERE model='Participant' AND tablename='participants' AND field='tfri_aml_date_acknowledgement' AND `type`='date' AND structure_value_domain  IS NULL ;
UPDATE structure_formats SET `language_heading`='tfri study acknowledgement' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='participants' AND `field`='tfri_aml_date_acknowledgement' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('tfri study acknowledgement', 'Study Acknowledgement', ''),
 ('tfri aml date acknowledgement', 'Date of Acknowledgement', '');
 
-- Eventum ID: 2953 - Profile - Preliminary diagnosis
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="tfri_profile_disease"), (SELECT id FROM structure_permissible_values WHERE value="other" AND language_alias="other"), "7", "1");

-- Eventum ID: 2949 - Consent Drop Down - Add unknown
UPDATE structure_value_domains AS svd INNER JOIN structure_value_domains_permissible_values AS svdpv ON svdpv.structure_value_domain_id=svd.id INNER JOIN structure_permissible_values AS spv ON spv.id=svdpv.structure_permissible_value_id SET `display_order`="4" WHERE svd.domain_name='tfri_consent_status' AND spv.id=(SELECT id FROM structure_permissible_values WHERE value="withdrawn" AND language_alias="withdrawn");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="tfri_consent_status"), (SELECT id FROM structure_permissible_values WHERE value="denied" AND language_alias="denied"), "2", "1");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="tfri_consent_status"), (SELECT id FROM structure_permissible_values WHERE value="unknown" AND language_alias="unknown"), "3", "1");
DELETE svdpv FROM structure_value_domains_permissible_values AS svdpv INNER JOIN structure_permissible_values AS spv ON svdpv.structure_permissible_value_id=spv.id WHERE spv.value="denied or n/a" AND spv.language_alias="denied or n/a";
DELETE FROM structure_permissible_values WHERE value="denied or n/a" AND language_alias="denied or n/a";

INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="tfri_consent_status"), (SELECT id FROM structure_permissible_values WHERE value="n/a" AND language_alias="n/a"), "5", "1");

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('n/a', 'N/A', ''),
 ('denied', 'Denied', '');

-- Eventum ID: 2954 - Consent - Add NA checkbox
ALTER TABLE `cd_tfri_aml_mds` 
ADD COLUMN `tfri_other_research_not_applicable` VARCHAR(10) NULL DEFAULT NULL AFTER `tfri_version_date_other_research`,
ADD COLUMN `tfri_intercellular_not_applicable` VARCHAR(10) NULL DEFAULT NULL AFTER `tfri_version_date_consent_intercellular`;

ALTER TABLE `cd_tfri_aml_mds_revs` 
ADD COLUMN `tfri_other_research_not_applicable` VARCHAR(10) NULL DEFAULT NULL AFTER `tfri_version_date_other_research`,
ADD COLUMN `tfri_intercellular_not_applicable` VARCHAR(10) NULL DEFAULT NULL AFTER `tfri_version_date_consent_intercellular`;

-- Form 5
INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'Participant', 'cd_tfri_aml_mds', 'tfri_other_research_not_applicable', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'tfri other research not applicable', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='cd_tfri_site_5'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='cd_tfri_aml_mds' AND `field`='tfri_other_research_not_applicable' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='tfri other research not applicable' AND `language_tag`=''), '1', '56', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');
UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') ,  `language_tag`='tfri other research not applicable' WHERE model='Participant' AND tablename='cd_tfri_aml_mds' AND field='tfri_other_research_not_applicable' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') ,  `language_label`='' WHERE model='Participant' AND tablename='cd_tfri_aml_mds' AND field='tfri_other_research_not_applicable' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');

-- Form 1
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='cd_tfri_site_1'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='cd_tfri_aml_mds' AND `field`='tfri_other_research_not_applicable' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='tfri other research not applicable'), '1', '57', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');

-- Form 2
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='cd_tfri_site_2'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='cd_tfri_aml_mds' AND `field`='tfri_other_research_not_applicable' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='tfri other research not applicable'), '1', '57', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');

-- Form 4
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='cd_tfri_site_4'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='cd_tfri_aml_mds' AND `field`='tfri_other_research_not_applicable' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='tfri other research not applicable'), '1', '57', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'Participant', 'cd_tfri_aml_mds', 'tfri_intercellular_not_applicable', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', '', 'tfri intercellular not applicable');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='cd_tfri_site_4'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='cd_tfri_aml_mds' AND `field`='tfri_intercellular_not_applicable' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='tfri intercellular not applicable'), '1', '49', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('tfri other research not applicable', 'Not applicable - Other research', ''),
 ('tfri intercellular not applicable', 'Not applicable - Intercellular', ''); 

-- Eventum ID: 2950 - Baseline - Genetic testing updates

-- Fix label for 1.6A and 1.6B
UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='genetic_status_options') ,  `language_label`='flt itd status at dx' WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='flt_status_at_dx' AND `type`='select' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='genetic_status_options');
UPDATE structure_formats SET `display_order`='82' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_tkd_status_at_dx' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='genetic_status_options') AND `flag_confidential`='0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('flt itd status at dx', '1.6A FLT-3 ITD status at diagnosis', ''),	
 ('flt tkd status at dx', '1.6B FLT-3 TKD status at diagnosis', ''); 
 
-- Fix order
UPDATE structure_formats SET `display_order`='83' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_date_collection' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='84' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_date_collection_status' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='flt_date_collection_options') AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='86' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_status_at_dx' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='genetic_status_options') AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='87' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_status' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='npm1_status_options') AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='88' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_date_of_collection' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='89' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_date_collection_status' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='npm1_date_collection_options') AND `flag_confidential`='0'); 

-- Fix drop down status menu
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="genetic_status_options"), (SELECT id FROM structure_permissible_values WHERE value="not done" AND language_alias="not done"), "4", "1");

-- Drop extra not done status field
DELETE FROM structure_formats WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_status' AND `language_label`='' AND `language_tag`='flt status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='flt_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0');
DELETE FROM structure_formats WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_status' AND `language_label`='' AND `language_tag`='npm status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='npm1_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0');
DELETE FROM structure_formats WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='cepba_status' AND `language_label`='' AND `language_tag`='cepba status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='cepba_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0');
-- Delete obsolete structure fields and validations
DELETE FROM structure_validations WHERE structure_field_id IN (SELECT id FROM structure_fields WHERE (`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_status' AND `language_label`='' AND `language_tag`='flt status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='flt_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0') OR (
`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_status' AND `language_label`='' AND `language_tag`='npm status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='npm1_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0') OR (
`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='cepba_status' AND `language_label`='' AND `language_tag`='cepba status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='cepba_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0'));
DELETE FROM structure_fields WHERE (`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_status' AND `language_label`='' AND `language_tag`='flt status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='flt_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0') OR (
`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='npm_status' AND `language_label`='' AND `language_tag`='npm status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='npm1_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0') OR (
`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='cepba_status' AND `language_label`='' AND `language_tag`='cepba status' AND `type`='select' AND `setting`='' AND `default`='' AND `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='cepba_status_options') AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0');

-- Fix FLT date of collection status
UPDATE structure_fields SET  `language_label`='flt itd date collection' WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='flt_date_collection' AND `type`='date' AND structure_value_domain  IS NULL ;

UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='flt_date_collection_options') ,  `language_tag`='flt itd date collection status' WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='flt_date_collection_status' AND `type`='select' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='flt_date_collection_options');
UPDATE structure_formats SET `display_order`='82' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_date_collection' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='83' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_date_collection_status' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='flt_date_collection_options') AND `flag_confidential`='0');

UPDATE structure_formats SET `display_order`='81' WHERE structure_id=(SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_tkd_status_at_dx' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='genetic_status_options') AND `flag_confidential`='0');

-- Add new date of collection for FLT TKD
ALTER TABLE `ed_tfri_clinical_section_1` 
ADD COLUMN `flt_tkd_date_collection` DATE NULL DEFAULT NULL AFTER `flt_date_collection_status`,
ADD COLUMN `flt_tkd_date_collection_status` VARCHAR(45) NULL DEFAULT NULL AFTER `flt_tkd_date_collection`;
ALTER TABLE `ed_tfri_clinical_section_1_revs` 
ADD COLUMN `flt_tkd_date_collection` DATE NULL DEFAULT NULL AFTER `flt_date_collection_status`,
ADD COLUMN `flt_tkd_date_collection_status` VARCHAR(45) NULL DEFAULT NULL AFTER `flt_tkd_date_collection`;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'Participant', 'ed_tfri_clinical_section_1', 'flt_tkd_date_collection', 'date',  NULL , '0', '', '', '', 'flt tkd date collection', ''), 
('ClinicalAnnotation', 'Participant', 'ed_tfri_clinical_section_1', 'flt_tkd_date_collection_status', 'select', (SELECT id FROM structure_value_domains WHERE domain_name='flt_date_collection_options') , '0', '', '', '', '', 'flt tkd date collection status');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_tkd_date_collection' AND `type`='date' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='flt tkd date collection' AND `language_tag`=''), '1', '84', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='ed_tfri_clinical_section_1'), (SELECT id FROM structure_fields WHERE `model`='Participant' AND `tablename`='ed_tfri_clinical_section_1' AND `field`='flt_tkd_date_collection_status' AND `type`='select' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='flt_date_collection_options')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='flt tkd date collection status'), '1', '85', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('flt itd date collection status', 'FLT-3 ITD date collection status', ''),
 ('flt tkd date collection status', 'FLT-3 TKD date collection status', ''), 	
 ('flt itd date collection', '1.7A FLT-3 ITD Date of collection', ''),	
 ('flt tkd date collection', '1.7B FLT-3 TKD Date of collection', ''); 


-- Eventum ID: 2938 Baseline - Add unknown to drop down lists

UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='rbc_transfusion_prior_cbc_test' AND `type`='select' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yesno');
UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='platelet_transfusion_prior_cbc_test' AND `type`='select' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yesno');
UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='leukapheresis_prior_therapy' AND `type`='select' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yesno');

UPDATE structure_fields SET  `type`='select',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='smoking_history_status' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `type`='select',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='smoked_previous_year' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `type`='select',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='smoked_prior_previous_year' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `type`='select',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_unknown')  WHERE model='EventDetail' AND tablename='ed_tfri_clinical_section_1' AND field='alcohol_consumption_greater_month' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');

INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="alcohol_consumption_pattern_options"), (SELECT id FROM structure_permissible_values WHERE value="UNK" AND language_alias="UNK"), "7", "1");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="exercise_pattern_options"), (SELECT id FROM structure_permissible_values WHERE value="UNK" AND language_alias="UNK"), "5", "1");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="participant_job_options"), (SELECT id FROM structure_permissible_values WHERE value="UNK" AND language_alias="UNK"), "4", "1");

-- Eventum ID: 2958 Event Masters - Disable common date
UPDATE structure_formats SET `flag_add`='0', `flag_edit`='0', `flag_search`='0', `flag_addgrid`='0', `flag_editgrid`='0', `flag_index`='0', `flag_detail`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='eventmasters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventMaster' AND `tablename`='event_masters' AND `field`='event_date' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

-- Eventum ID: 2959 Transplant - Add date of transplant
ALTER TABLE `ed_tfri_study_eq_5d_health` 
ADD COLUMN `date_of_transplant` DATE NULL DEFAULT NULL AFTER `method_of_completion`;
ALTER TABLE `ed_tfri_study_eq_5d_health_revs` 
ADD COLUMN `date_of_transplant` DATE NULL DEFAULT NULL AFTER `method_of_completion`;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'EventDetail', 'ed_tfri_study_eq_5d_health', 'date_of_transplant', 'date',  NULL , '0', '', '', '', 'date of transplant', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='ed_tfri_clinical_transplant'), (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ed_tfri_study_eq_5d_health' AND `field`='date_of_transplant' AND `type`='date' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='date of transplant' AND `language_tag`=''), '1', '1', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('date of transplant', '8.1 Enter date of transplant', '');
 
-- Eventum ID: 2962 Bank names - Acronyms
UPDATE `banks` SET `name`='TFRI-MTB', `description`='' WHERE `id`='3';
UPDATE `banks` SET `name`='TFRI-HCBBC' WHERE `id`='2';
UPDATE `banks` SET `name`='TFRI-BCLQ' WHERE `id`='1';
UPDATE `banks` SET `name`='TFRI-PMCCLCLB' WHERE `id`='4';

-- Eventum ID: 2946 Aliquot search view customization
UPDATE structure_formats SET `flag_index`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='ViewAliquot' AND `tablename`='' AND `field`='storage_coord_x' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_index`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='ViewAliquot' AND `tablename`='' AND `field`='storage_coord_y' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_index`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='ViewAliquot' AND `tablename`='' AND `field`='parent_sample_type' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='parent_sample_type') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_search`='0', `flag_index`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='ViewAliquot' AND `tablename`='view_aliquots' AND `field`='created' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_search`='0', `flag_index`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='ViewAliquot' AND `tablename`='view_aliquots' AND `field`='temperature' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_search`='0', `flag_index`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='ViewAliquot' AND `tablename`='view_aliquots' AND `field`='temp_unit' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='temperature_unit_code') AND `flag_confidential`='0');

-- Eventum ID: 2963 Aliquot - Enable storage selection label
UPDATE structure_formats SET `flag_add`='1', `flag_edit`='1', `flag_search`='1', `flag_addgrid`='1', `flag_editgrid`='1', `flag_batchedit`='1', `flag_index`='1', `flag_detail`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='FunctionManagement' AND `tablename`='' AND `field`='recorded_storage_selection_label' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

-- Eventum ID: 2838 Review AML Diagnosis Form
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_runx1-runx1t1' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_cbfbeta_myh11' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='apl_recurrent_genetic_pml_raralpha' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_dek-nup214' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_rpn1-evi1' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_rbm15-mkl1' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_mutated_npm1' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_mutated_cebpa' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_recurrent_genetic_myelodysplasia_related' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_minimally_differentiated' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_without_maturation' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_acute_myelomonocytic_leukemia' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_acute_monoblastic_monocytic_leukemia' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_acute_erythroid_leukemia_pure' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_acute_erythroid_leukemia_erythroleukemia' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_megakaryoblastic_leukemia' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_acute_basophilic_leukemia' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_acute_panmyelosis_myelofibrosis' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_myeloid_sarcoma' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_nos_blastic_plasmacytoid_dendritic_cell_neoplasm' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_ambiguous_acute_undifferentiated_leukemia' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_ambiguous_mixed_phenotype_bcr-abl1' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_ambiguous_mixed_phenotype_mll_rearranged' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_ambiguous_mixed_phenotype_b-myeloid_nos' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_ambiguous_mixed_phenotype_t-myeloid_nos' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');
UPDATE structure_fields SET  `plugin`='ClinicalAnnotation',  `model`='DiagnosisDetail',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='SampleDetail' AND tablename='dxd_tfri_aml' AND field='aml_ambiguous_natural_killer_cell_lymphoblastic' AND `type`='checkbox' AND structure_value_domain =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('aml nos without maturation', 'AML without maturation (M1)', '');

ALTER TABLE `dxd_tfri_aml` 
ADD COLUMN `aml_nos_with_maturation` CHAR(3) NULL DEFAULT NULL AFTER `aml_nos_without_maturation`;
ALTER TABLE `dxd_tfri_aml_revs` 
ADD COLUMN `aml_nos_with_maturation` CHAR(3) NULL DEFAULT NULL AFTER `aml_nos_without_maturation`;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_aml', 'aml_nos_with_maturation', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'aml nos with maturation', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='dx_tfri_aml'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_aml' AND `field`='aml_nos_with_maturation' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='aml nos with maturation' AND `language_tag`=''), '1', '16', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0');
UPDATE structure_formats SET `display_column`='2' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_aml') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_aml' AND `field`='aml_nos_with_maturation' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') AND `flag_confidential`='0');
 
REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('aml recurrent genetic runx1-runx1t1', "AML with t(8;21)(q22;q22); RUNX1-RUNX1T1", ''), 
 ('aml recurrent genetic dek-nup214', "AML with t(6;9)(p23;q34); DEK-NUP214", ''),
 ('aml nos with maturation', 'AML with maturation (M2)', '');
 
-- Add transform field
ALTER TABLE `dxd_tfri_aml` 
ADD COLUMN `aml_transform_mds` CHAR(3) NULL DEFAULT NULL AFTER `aml_ambiguous_natural_killer_cell_lymphoblastic`;
ALTER TABLE `dxd_tfri_aml_revs` 
ADD COLUMN `aml_transform_mds` CHAR(3) NULL DEFAULT NULL AFTER `aml_ambiguous_natural_killer_cell_lymphoblastic`;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_aml', 'aml_transform_mds', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'aml transform mds', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='dx_tfri_aml'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_aml' AND `field`='aml_transform_mds' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='aml transform mds' AND `language_tag`=''), '2', '70', 'aml transform', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('aml transform mds', "9. Did AML transform from MDS/MDP?", ''),
 ('aml transform', "AML Transform", '');   

-- Eventum ID: 2830 Other Diagnosis Types
UPDATE structure_fields SET  `setting`='size=30' WHERE model='DiagnosisDetail' AND tablename='dxd_tfri_other' AND field='tfri_other_diagnosis' AND `type`='input' AND structure_value_domain  IS NULL ;

ALTER TABLE `dxd_tfri_other` 
DROP COLUMN `tfri_b_lyphoblastic_leukemia_lymphoma`,
CHANGE COLUMN `tfri_t_lyphoblastic_leukemia_lymphoma` `tfri_t_lyphoblastic_leukemia_lymphoma` VARCHAR(45) NULL DEFAULT NULL ,
ADD COLUMN `myeloid_proliferations_transient_abnormal_myelopoiesis` VARCHAR(45) NULL DEFAULT NULL AFTER `diagnosis_master_id`,
ADD COLUMN `myeloid_proliferations_leukemia_downs` VARCHAR(45) NULL DEFAULT NULL AFTER `myeloid_proliferations_transient_abnormal_myelopoiesis`,
ADD COLUMN `b_lyphoblastic_nos` VARCHAR(45) NULL DEFAULT NULL AFTER `myeloid_proliferations_leukemia_downs`,
ADD COLUMN `b_lyphoblastic_recurrent_abnormalities` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_nos`,
ADD COLUMN `b_lyphoblastic_with_BCR-ABL_1` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_recurrent_abnormalities`,
ADD COLUMN `b_lyphoblastic_with_MLL_rearranged` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_BCR-ABL_1`,
ADD COLUMN `b_lyphoblastic_with_TEL-AML1` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_MLL_rearranged`,
ADD COLUMN `b_lyphoblastic_hyperdiploidy` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_TEL-AML1`,
ADD COLUMN `b_lyphoblastic_hypodiploidy` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_hyperdiploidy`,
ADD COLUMN `b_lyphoblastic_with_IL3-IGH` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_hypodiploidy`,
ADD COLUMN `b_lyphoblastic_with_TCF3-PBX1` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_IL3-IGH`,
ADD COLUMN `tfri_other_common_dx` VARCHAR(150) NULL DEFAULT NULL AFTER `tfri_other_diagnosis`;

ALTER TABLE `dxd_tfri_other_revs` 
DROP COLUMN `tfri_b_lyphoblastic_leukemia_lymphoma`,
CHANGE COLUMN `tfri_t_lyphoblastic_leukemia_lymphoma` `tfri_t_lyphoblastic_leukemia_lymphoma` VARCHAR(45) NULL DEFAULT NULL ,
ADD COLUMN `myeloid_proliferations_transient_abnormal_myelopoiesis` VARCHAR(45) NULL DEFAULT NULL AFTER `diagnosis_master_id`,
ADD COLUMN `myeloid_proliferations_leukemia_downs` VARCHAR(45) NULL DEFAULT NULL AFTER `myeloid_proliferations_transient_abnormal_myelopoiesis`,
ADD COLUMN `b_lyphoblastic_nos` VARCHAR(45) NULL DEFAULT NULL AFTER `myeloid_proliferations_leukemia_downs`,
ADD COLUMN `b_lyphoblastic_recurrent_abnormalities` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_nos`,
ADD COLUMN `b_lyphoblastic_with_BCR-ABL_1` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_recurrent_abnormalities`,
ADD COLUMN `b_lyphoblastic_with_MLL_rearranged` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_BCR-ABL_1`,
ADD COLUMN `b_lyphoblastic_with_TEL-AML1` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_MLL_rearranged`,
ADD COLUMN `b_lyphoblastic_hyperdiploidy` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_TEL-AML1`,
ADD COLUMN `b_lyphoblastic_hypodiploidy` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_hyperdiploidy`,
ADD COLUMN `b_lyphoblastic_with_IL3-IGH` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_hypodiploidy`,
ADD COLUMN `b_lyphoblastic_with_TCF3-PBX1` VARCHAR(45) NULL DEFAULT NULL AFTER `b_lyphoblastic_with_IL3-IGH`,
ADD COLUMN `tfri_other_common_dx` VARCHAR(150) NULL DEFAULT NULL AFTER `tfri_other_diagnosis`;

-- Drop demo field
-- delete structure_formats
DELETE FROM structure_formats WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_b_lyphoblastic_leukemia_lymphoma' AND `language_label`='tfri b lyphoblastic leukemia lymphoma' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0');
-- Delete obsolete structure fields and validations
DELETE FROM structure_validations WHERE structure_field_id IN (SELECT id FROM structure_fields WHERE (`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_b_lyphoblastic_leukemia_lymphoma' AND `language_label`='tfri b lyphoblastic leukemia lymphoma' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0'));
DELETE FROM structure_fields WHERE (`public_identifier`='' AND `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_b_lyphoblastic_leukemia_lymphoma' AND `language_label`='tfri b lyphoblastic leukemia lymphoma' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0');

-- Build new dx types
UPDATE structure_fields SET  `type`='checkbox',  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  WHERE model='DiagnosisDetail' AND tablename='dxd_tfri_other' AND field='tfri_t_lyphoblastic_leukemia_lymphoma' AND `type`='input' AND structure_value_domain  IS NULL ;
UPDATE structure_formats SET `language_heading`='lyphoblastic leukemia lymphoma' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_t_lyphoblastic_leukemia_lymphoma' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'myeloid_proliferations_transient_abnormal_myelopoiesis', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'myeloid proliferations transient abnormal myelopoiesis', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'myeloid_proliferations_leukemia_downs', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'myeloid proliferations leukemia downs', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='myeloid_proliferations_transient_abnormal_myelopoiesis' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='myeloid proliferations transient abnormal myelopoiesis' AND `language_tag`=''), '1', '10', 'myeloid proliferations', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='myeloid_proliferations_leukemia_downs' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='myeloid proliferations leukemia downs' AND `language_tag`=''), '1', '12', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0');
UPDATE structure_formats SET `display_order`='85', `language_heading`='lyphoblastic leukemia lymphoma' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_t_lyphoblastic_leukemia_lymphoma' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='90' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_other_diagnosis' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `language_heading`='other diagnosis' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_other_diagnosis' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');


INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_nos', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic nos', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_recurrent_abnormalities', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic recurrent abnormalities', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_with_BCR-ABL_1', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic with BCR-ABL 1', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_with_MLL_rearranged', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic with MLL rearranged', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_with_TEL-AML1', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic with TEL-AML1', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_hyperdiploidy', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic hyperdiploidy', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_hypodiploidy', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic hypodiploidy', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_with_IL3-IGH', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic with IL3-IGH', ''), 
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'b_lyphoblastic_with_TCF3-PBX1', 'checkbox', (SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox') , '0', '', '', '', 'b lyphoblastic with TCF3-PBX1', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_nos' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic nos' AND `language_tag`=''), '2', '10', 'b lymphoblastic', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_recurrent_abnormalities' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic recurrent abnormalities' AND `language_tag`=''), '2', '15', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_with_BCR-ABL_1' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic with BCR-ABL 1' AND `language_tag`=''), '2', '20', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_with_MLL_rearranged' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic with MLL rearranged' AND `language_tag`=''), '2', '25', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_with_TEL-AML1' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic with TEL-AML1' AND `language_tag`=''), '2', '30', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_hyperdiploidy' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic hyperdiploidy' AND `language_tag`=''), '2', '35', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_hypodiploidy' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic hypodiploidy' AND `language_tag`=''), '2', '40', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_with_IL3-IGH' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic with IL3-IGH' AND `language_tag`=''), '2', '45', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0'), 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='b_lyphoblastic_with_TCF3-PBX1' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='b lyphoblastic with TCF3-PBX1' AND `language_tag`=''), '2', '50', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('tfri other diagnosis', '10. Other diagnosis (not included in table)', ''),
 ('lyphoblastic leukemia lymphoma', '8. T Lyphoblastic Leukemia/Lymphoma', ''), 
 ('myeloid proliferations', '7. Myeloid proliferations related to Down syndrome', ''),
 ('myeloid proliferations transient abnormal myelopoiesis', 'Transient abnormal myelopoiesis', ''), 
 ('myeloid proliferations leukemia downs', 'Myeloid leukemia associated with Down syndrome', ''),
 ('other diagnosis', '10. Other diagnosis (Not yet specified', ''), 
 ('b lyphoblastic nos', 'B lyphoblastic leukemia/lymphoma, NOS', ''),
 ('b lyphoblastic recurrent abnormalities', 'B lyphoblastic leukemia/lymphoma with recurrent genetic abnormalities', ''), 
 ('b lyphoblastic with BCR-ABL 1', 'B lyphoblastic with t(9;22)(q34;q11.2); BCR-ABL 1', ''),
 ('b lyphoblastic with MLL rearranged', 'B lyphoblastic leukemia/lymphoma with t(v;11q23); MLL rearranged', ''), 
 ('b lyphoblastic with TEL-AML1', 'B lyphoblastic with t(12;21)(p13;q22) TEL-AML1 (ETV6-RUNX1', ''), 
 ('b lyphoblastic hyperdiploidy', 'B lyphoblastic leukemia/lymphoma with hyperdiploidy', ''),
 ('b lyphoblastic hypodiploidy', 'B lyphoblastic leukemia/lymphoma with hypodiploidy', ''), 
 ('b lyphoblastic with IL3-IGH', 'B lyphoblastic leukemia/lymphoma with t(5;14)(q31;q132)IL3-IGH', ''),
 ('b lyphoblastic with TCF3-PBX1', 'B lyphoblastic leukemia/lymphoma with t(1;19)(q23;p13.3); TCF3-PBX1', ''),  
 ('b lymphoblastic', '6. B lymphoblastic leukemia/lymphoma', '');

-- Add value domain for other diagnosis
INSERT INTO structure_value_domains (domain_name, override, category, source) VALUES ("other_dx_options", "open", "", NULL);
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="ALL" AND language_alias="ALL"), "1", "1");
INSERT INTO structure_permissible_values (value, language_alias) VALUES("APL", "APL");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="APL" AND language_alias="APL"), "2", "1");
INSERT INTO structure_permissible_values (value, language_alias) VALUES("CLL", "CLL");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="CLL" AND language_alias="CLL"), "3", "1");
INSERT INTO structure_permissible_values (value, language_alias) VALUES("CML", "CML");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="CML" AND language_alias="CML"), "4", "1");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="Lymphoma" AND language_alias="Lymphoma"), "6", "1");
INSERT INTO structure_permissible_values (value, language_alias) VALUES("Aplastic anemia", "Aplastic anemia");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="Aplastic anemia" AND language_alias="Aplastic anemia"), "5", "1");
INSERT INTO structure_permissible_values (value, language_alias) VALUES("Other malignant hematologic disorder", "Other malignant hematologic disorder");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="Other malignant hematologic disorder" AND language_alias="Other malignant hematologic disorder"), "7", "1");
INSERT INTO structure_permissible_values (value, language_alias) VALUES("Other non-malignant hematologic disorder", "Other non-malignant hematologic disorder");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="Other non-malignant hematologic disorder" AND language_alias="Other non-malignant hematologic disorder"), "8", "1");
INSERT INTO structure_value_domains_permissible_values (structure_value_domain_id, structure_permissible_value_id, display_order, flag_active) VALUES ((SELECT id FROM structure_value_domains WHERE domain_name="other_dx_options"), (SELECT id FROM structure_permissible_values WHERE value="other" AND language_alias="other"), "9", "1");

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('APL', 'APL', ''),
 ('CLL', 'CLL', ''),
 ('CML', 'CML', ''),  
 ('Lymphoma', 'Lymphoma', ''),
 ('ALL', 'ALL', ''),
 ('Aplastic anemia', 'Aplastic anemia', ''),  
 ('Other malignant hematologic disorder', 'Other malignant hematologic disorder', ''),
 ('Other non-malignant hematologic disorder', 'Other non-malignant hematologic disorder', '');
 
-- Add field
INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_tfri_other', 'tfri_other_common_dx', 'select', (SELECT id FROM structure_value_domains WHERE domain_name='other_dx_options') , '0', '', '', '', 'tfri other common dx', '');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='dx_tfri_other'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_other_common_dx' AND `type`='select' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='other_dx_options')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='tfri other common dx' AND `language_tag`=''), '2', '88', 'other diagnosis', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0');
UPDATE structure_fields SET  `language_label`='',  `language_tag`='tfri other diagnosis' WHERE model='DiagnosisDetail' AND tablename='dxd_tfri_other' AND field='tfri_other_diagnosis' AND `type`='input' AND structure_value_domain  IS NULL ;
UPDATE structure_formats SET `language_heading`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_other_diagnosis' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_column`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tfri_other') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='dxd_tfri_other' AND `field`='tfri_other_common_dx' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='other_dx_options') AND `flag_confidential`='0');

REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
 ('tfri other common dx', 'Other common diagnosis ', ''),
 ('tfri other diagnosis', 'If other diagnosis, specify', '');

