<?php
/** **********************************************************************
 * CHUM-BioTransit Project
 * ***********************************************************************
 *
 * InventoryManagement plugin custom code
 *
 * Class AliquotMasterCustom
 * 
 * @author N. Luc - CTRNet (nicolas.luc@gmail.com)
 * @since 2018-10-22
 */
 
class AliquotMasterCustom extends AliquotMaster
{
    var $useTable = 'aliquot_masters';
    
    var $name = "AliquotMaster";
    
    /**
     * Will return an empty array considering that no consent exists into CUSM-CIM version.
     *
     * @param array $aliquot
     *            with either a key 'id' referring to an array
     *            of ids, or a key 'data' referring to AliquotMaster.
     * @param If|string $modelName If
     *            the aliquot array contains data, the model name
     *            to use.
     * @return an array having unconsented aliquot as key and their consent
     *         status as value. This function refers to
     * ViewCollection->getUnconsentedCollections.
     */
    public function getUnconsentedAliquots(array $aliquot, $modelName = 'AliquotMaster')
    {
        return array();
    }
    
    /**
     * Aliquot data custom valdiation.
     *
     * @param array $options
     * @return bool
     */
    public function validates($options = array())
    {
        $validate = parent::validates($options);
        
        // Validate barcode is different than barcodes generated by the system
        if (isset($this->data['AliquotMaster']['barcode']) && !$this->id && preg_match('/^atim#/i', $this->data['AliquotMaster']['barcode'])) {
            $this->validationErrors['barcode'][] = 'error barcode should be different than system barcode';
            $validate = false;
        }
        
        return $validate;
    }

    public function regenerateAliquotBarcode()
    {
        $queryToUpdate = "UPDATE aliquot_masters SET barcode = CONCAT('ATiM#', id) WHERE barcode IS NULL OR barcode LIKE '';";
        $this->tryCatchQuery($queryToUpdate);
        $this->tryCatchQuery(str_replace("aliquot_masters", "aliquot_masters_revs", $queryToUpdate));
    }
}