TRUNCATE chus_topography_coding;
INSERT INTO chus_topography_coding (code,category,description)
VALUEs
("C150", "Oesophagus", "Cervical oesophagus"),
("C151", "Oesophagus", "Thoracic oesophagus"),
("C152", "Oesophagus", "Abdominal oesophagus"),
("C153", "Oesophagus", "Upper third of oesophagus"),
("C154", "Oesophagus", "Middle third of oesophagus"),
("C155", "Oesophagus", "Lower third of oesophagus"),
("C158", "Oesophagus", "Overlapping lesion of oesophagus"),
("C159", "Oesophagus", "Oesophagus unspecified"),
("C160", "Stomach", "Cardia unspecified"),
("C161", "Stomach", "Fundus of stomach"),
("C162", "Stomach", "Body of stomach"),
("C163", "Stomach", "Gastric (pyloric) antrum"),
("C164", "Stomach", "Pylorus"),
("C165", "Stomach", "Lesser curvature of stomach unspecified"),
("C166", "Stomach", "Greater curvature of stomach unspecified"),
("C168", "Stomach", "Overlapping lesion of stomach"),
("C169", "Stomach", "Stomach unspecified"),
("C170", "Small Intestine", "Duodenum"),
("C171", "Small Intestine", "Jejunum"),
("C172", "Small Intestine", "Ileum"),
("C173", "Small Intestine", "Meckel diverticulum"),
("C178", "Small Intestine", "Overlapping lesion of small intestine"),
("C179", "Small Intestine", "Small intestine unspecified"),
("C180", "Colon", "Caecum"),
("C181", "Colon", "Appendix"),
("C182", "Colon", "Ascending colon"),
("C183", "Colon", "Hepatic flexure of colon"),
("C184", "Colon", "Transverse colon"),
("C185", "Colon", "Splenic flexure of colon"),
("C186", "Colon", "Descending colon"),
("C187", "Colon", "Sigmoid colon"),
("C188", "Colon", "Overlapping lesion of colon"),
("C189", "Colon", "Colon unspecified"),
("C199", "Rectosigmoid Junction", "Rectosigmoid junction"),
("C209", "Rectum", "Rectum"),
("C210", "Anus and Anal Canal", "Anus unspecified"),
("C211", "Anus and Anal Canal", "Anal canal"),
("C212", "Anus and Anal Canal", "Cloacogenic zone"),
("C218", "Anus and Anal Canal", "Overlapping lesion of rectum anus and anal canal"),
("C220", "Liver and Intrahepatic Bile Ducts", "Liver"),
("C221", "Liver and Intrahepatic Bile Ducts", "Intrahepatic bile duct"),
("C239", "Gallbladder", "Gallbladder"),
("C240", "Other and Unspecified Parts of Biliary Tract", "Extrahepatic bile duct"),
("C241", "Other and Unspecified Parts of Biliary Tract", "Ampulla of Vater"),
("C248", "Other and Unspecified Parts of Biliary Tract", "Overlapping lesion of biliary tract"),
("C249", "Other and Unspecified Parts of Biliary Tract", "Biliary tract unspecified"),
("C250", "Pancreas", "Head of pancreas"),
("C251", "Pancreas", "Body of pancreas"),
("C252", "Pancreas", "Tail of pancreas"),
("C253", "Pancreas", "Pancreatic duct"),
("C254", "Pancreas", "Islets of Langerhans (endocrine pancreas)"),
("C257", "Pancreas", "Other parts of pancreas"),
("C258", "Pancreas", "Overlapping lesion of pancreas"),
("C259", "Pancreas", "Pancreas unspecified"),
("C260", "Other and Ill-Defined Digestive Organs", "Intestinal tract unspecified"),
("C268", "Other and Ill-Defined Digestive Organs", "Overlapping lesion of digestive system"),
("C269", "Other and Ill-Defined Digestive Organs", "Gastrointestinal tract unspecified"),
("C780", "Respiratory and digestive organs", "Secondary malignant neoplasm of lung"),
("C781", "Respiratory and digestive organs", "Secondary malignant neoplasm of mediastinum"),
("C782", "Respiratory and digestive organs", "Secondary malignant neoplasm of pleura"),
("C783", "Respiratory and digestive organs", "Secondary malignant neoplasm of other and unspecified respiratory organs"),
("C784", "Respiratory and digestive organs", "Secondary malignant neoplasm of small intestine"),
("C785", "Respiratory and digestive organs", "Secondary malignant neoplasm of large intestine and rectum"),
("C786", "Respiratory and digestive organs", "Secondary malignant neoplasm of retroperitoneum and peritoneum"),
("C787", "Respiratory and digestive organs", "Secondary malignant neoplasm of liver and intrahepatic bile duct"),
("C788", "Respiratory and digestive organs", "Secondary malignant neoplasm of other and unspecified digestive organs"),
("C793", "other and unspecified sites", "Secondary malignant neoplasm of brain and cerebral meninges"),
("C794", "other and unspecified sites", "Secondary malignant neoplasm of other and unspecified parts of nervous system"),
("C795", "other and unspecified sites", "Secondary malignant neoplasm of bone and bone marrow");

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

TRUNCATE chus_morphology_coding;
INSERT INTO chus_morphology_coding (tumour_type, tumour_cell_origin, tumour_category, morphology_code, behaviour_code, morphology_description)
VALUES
("Oesophagus", "Epithelial tumours", "Premalignant lesions", "8077/0", "Benign", "Squamous intraepithelial neoplasia (dysplasia), low grade"),
("Oesophagus", "Epithelial tumours", "Premalignant lesions", "8077/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Squamous intraepithelial neoplasia (dysplasia), high grade"),
("Oesophagus", "Epithelial tumours", "Premalignant lesions", "8148/0", "Benign", "Glandular dysplasia (intraepithelial neoplasia), low grade"),
("Oesophagus", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Glandular dysplasia (intraepithelial neoplasia), high grade"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8200/3", "Malignant", "Adenoid cystic carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8083/3", "Malignant", "Basaloid squamous cell carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8430/3", "Malignant", "Mucoepidermoid carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8074/3", "Malignant", "Spindle cell (squamous) carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8051/3", "Malignant", "Verrucous (squamous) carcinoma"),
("Oesophagus", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Oesophagus", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Oesophagus", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Oesophagus", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Oesophagus", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Oesophagus", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Oesophagus", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Oesophagus", "Mesenchymal tumours", "", "9580/0", "Benign", "Granular cell tumour"),
("Oesophagus", "Mesenchymal tumours", "", "9120/0", "Benign", "Haemangioma"),
("Oesophagus", "Mesenchymal tumours", "", "8890/0", "Benign", "Leiomyoma"),
("Oesophagus", "Mesenchymal tumours", "", "8850/0", "Benign", "Lipoma"),
("Oesophagus", "Mesenchymal tumours", "", "8936/3", "Malignant", "Gastrointestinal stromal tumour"),
("Oesophagus", "Mesenchymal tumours", "", "9140/3", "Malignant", "Kaposi sarcoma"),
("Oesophagus", "Mesenchymal tumours", "", "8890/3", "Malignant", "Leiomyosarcoma"),
("Oesophagus", "Mesenchymal tumours", "", "8720/3", "Malignant", "Melanoma"),
("Oesophagus", "Mesenchymal tumours", "", "8900/3", "Malignant", "Rhabdomyosarcoma"),
("Oesophagus", "Mesenchymal tumours", "", "9040/3", "Malignant", "Synovial sarcoma"),
("Oesophagus", "Lymphomas", "", "", "", ""),
("Oesophagus", "Secondary tumours", "", "", "", ""),
("Oesophagogastric junction", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Stomach", "Epithelial tumours", "Premalignant lesions", "8140/0", "Benign", "Adenoma"),
("Stomach", "Epithelial tumours", "Premalignant lesions", "8148/0", "Benign", "Intraepithelial neoplasia (dysplasia), low grade"),
("Stomach", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Intraepithelial neoplasia (dysplasia), high grade"),
("Stomach", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8260/3", "Malignant", "Papillary adenocarcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8211/3", "Malignant", "Tubular adenocarcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8490/3", "Malignant", "Poorly cohesive carcinoma (including signet ring cell carcinoma and other variants)"),
("Stomach", "Epithelial tumours", "Carcinomas", "8255/3", "Malignant", "Mixed adenocarcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8512/3", "Malignant", "Carcinoma with lymphoid stroma (medullary carcinoma)"),
("Stomach", "Epithelial tumours", "Carcinomas", "8576/3", "Malignant", "Hepatoid adenocarcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("Stomach", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8241/3", "Malignant", "EC cell, serotonin-producing neuroendocrine tumour (NET)"),
("Stomach", "Epithelial tumours", "Neuroendocrine neoplasms", "8153/3", "Malignant", "Gastrin-producing neuroendocrine tumour (NET) (gastrinoma)"),
("Stomach", "Mesenchymal tumours", "", "8711/0", "Benign", "Glomus tumour"),
("Stomach", "Mesenchymal tumours", "", "9580/0", "Benign", "Granular cell tumour"),
("Stomach", "Mesenchymal tumours", "", "8890/0", "Benign", "Leiomyoma"),
("Stomach", "Mesenchymal tumours", "", "8811/0", "Benign", "Plexiform fibromyxoma"),
("Stomach", "Mesenchymal tumours", "", "9560/0", "Benign", "Schwannoma"),
("Stomach", "Mesenchymal tumours", "", "8825/1", "Unspecified, borderline or uncertain behaviour", "Inflammatory myofibroblastic tumour"),
("Stomach", "Mesenchymal tumours", "", "8936/3", "Malignant", "Gastrointestinal stromal tumour"),
("Stomach", "Mesenchymal tumours", "", "9140/3", "Malignant", "Kaposi sarcoma"),
("Stomach", "Mesenchymal tumours", "", "8890/3", "Malignant", "Leiomyosarcoma"),
("Stomach", "Mesenchymal tumours", "", "9040/3", "Malignant", "Synovial sarcoma"),
("Stomach", "Lymphomas", "", "", "", ""),
("Stomach", "Secondary tumours", "", "", "", ""),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8144/0", "Benign", "Intestinal-type adenoma"),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8211/0", "Benign", "Tubular adenoma"),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8263/0", "Benign", "Tubulovillous adenoma"),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8261/0", "Benign", "Villous adenoma"),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8163/0", "Benign", "Noninvasive pancreatobiliary papillary neoplasm with low-grade dysplasia (Iow-grade intraepithelial neoplasia)"),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8163/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Noninvasive pancreatobiliary papillary neoplasm with high-grade dysplasia (high-grade intraepithelial neoplasia)"),
("Ampullary region", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Flat intraepithelial neoplasia (dyplasia), high grade"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8144/3", "Malignant", "Adenocarcinoma, invasive intestinal type"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8163/3", "Malignant", "Adenocarcinoma, pancreatobiliary type"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8310/3", "Malignant", "Clear cell carcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8576/3", "Malignant", "Hepatoid adenocarcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8260/3", "Malignant", "Invasive papillary adenocarcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8490/3", "Malignant", "Signet ring cell carcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Ampullary region", "Epithelial tumours", "Carcinomas", "8035/3", "Malignant", "Undifferentiated carcinoma with osteoclast-like giant cells"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8241/3", "Malignant", "EC cell, serotonin-producing neuroendocrine tumour (NET)"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8683/0", "Benign", "Gangliocytic paraganglioma"),
("Ampullary region", "Epithelial tumours", "Neuroendocrine neoplasms", "8156/3", "Malignant", "Somatostatin-producing neuroendocrine tumour (NET)"),
("Ampullary region", "Mesenchymal tumours", "", "", "", ""),
("Ampullary region", "Secondary tumours", "", "", "", ""),
("small intestine", "Epithelial tumours", "Premalignant lesions", "8140/0", "Benign", "Adenoma"),
("small intestine", "Epithelial tumours", "Premalignant lesions", "8211/0", "Benign", "Tubular adenoma"),
("small intestine", "Epithelial tumours", "Premalignant lesions", "8261/0", "Benign", "Villous adenoma"),
("small intestine", "Epithelial tumours", "Premalignant lesions", "8263/0", "Benign", "Tubulovillous adenoma"),
("small intestine", "Epithelial tumours", "Premalignant lesions", "8148/0", "Benign", "Dysplasia (intraepithelial neoplasia), low grade"),
("small intestine", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Dysplasia (intraepithelial neoplasia), high grade"),
("small intestine", "Epithelial tumours", "Hamartomas", "", "", "Juvenile polyp"),
("small intestine", "Epithelial tumours", "Hamartomas", "", "", "Peutz-Jeghers polyp"),
("small intestine", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("small intestine", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("small intestine", "Epithelial tumours", "Carcinomas", "8490/3", "Malignant", "Signet ring cell carcinoma"),
("small intestine", "Epithelial tumours", "Carcinomas", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("small intestine", "Epithelial tumours", "Carcinomas", "8510/3", "Malignant", "Medullary carcinoma"),
("small intestine", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("small intestine", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma");
INSERT INTO chus_morphology_coding (tumour_type, tumour_cell_origin, tumour_category, morphology_code, behaviour_code, morphology_description)
VALUES
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8241/3", "Malignant", "EC cell, serotonin-producing neuroendocrine tumour (NET)"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8683/0", "Benign", "Gangliocytic paraganglioma"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8153/3", "Malignant", "Gastrinoma"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8152/1", "Unspecified, borderline or uncertain behaviour", "L cell, Glucagon-like peptide-producing and PP/PYY-producing NETs"),
("small intestine", "Epithelial tumours", "Neuroendocrine neoplasms", "8156/3", "Malignant", "Somatostatin-producing neuroendocrine tumour (NET)"),
("small intestine", "Mesenchymal tumours", "", "8890/0", "Benign", "Leiomyoma"),
("small intestine", "Mesenchymal tumours", "", "8850/0", "Benign", "Lipoma"),
("small intestine", "Mesenchymal tumours", "", "9120/3", "Malignant", "Angiosarcoma"),
("small intestine", "Mesenchymal tumours", "", "8936/3", "Malignant", "Gastrointestinal stromal tumour"),
("small intestine", "Mesenchymal tumours", "", "9140/3", "Malignant", "Kaposi sarcoma"),
("small intestine", "Mesenchymal tumours", "", "8890/3", "Malignant", "Leiomyosarcoma"),
("small intestine", "Lymphomas", "", "", "", ""),
("small intestine", "Secondary tumours", "", "", "", ""),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8140/0", "Benign", "Adenoma"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8211/0", "Benign", "Tubular adenoma"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8261/0", "Benign", "Villous adenoma"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8263/0", "Benign", "Tubulovillous adenoma"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8148/0", "Benign", "Dysplasia (intraepithelial neoplasia), low grade"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Dysplasia (intraepithelial neoplasia), high grade"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "", "", "Hyperplastic polyp"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8213/0", "Benign", "Sessile serrated adenoma/polyp"),
("Appendix", "Epithelial tumours", "Premalignant lesions", "8213/0", "Benign", "Traditional serrated adenoma"),
("Appendix", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Appendix", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("Appendix", "Epithelial tumours", "Carcinomas", "8480/1", "Unspecified, borderline or uncertain behaviour", "Low-grade appendiceal mucinous neoplasm"),
("Appendix", "Epithelial tumours", "Carcinomas", "8490/3", "Malignant", "Signet ring cell carcinoma"),
("Appendix", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8241/3", "Malignant", "EC cell, serotonin-producing neuroendocrine tumour (NET)"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8243/3", "Malignant", "Goblet cell carcinoid"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8152/1", "Unspecified, borderline or uncertain behaviour", "L cell, Glucagon-like peptide-producing and PP/PYY-producing NETs"),
("Appendix", "Epithelial tumours", "Neuroendocrine neoplasms", "8245/1", "Unspecified, borderline or uncertain behaviour", "Tubular carcinoid"),
("Appendix", "Mesenchymal tumours", "", "8890/0", "Benign", "Leiomyoma"),
("Appendix", "Mesenchymal tumours", "", "8850/0", "Benign", "Lipoma"),
("Appendix", "Mesenchymal tumours", "", "9570/0", "Benign", "Neuroma"),
("Appendix", "Mesenchymal tumours", "", "9140/3", "Malignant", "Kaposi sarcoma"),
("Appendix", "Mesenchymal tumours", "", "8890/3", "Malignant", "Leiomyosarcoma"),
("Appendix", "Lymphomas", "", "", "", ""),
("Appendix", "Secondary tumours", "", "", "", ""),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8140/0", "Benign", "Adenoma"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8211/0", "Benign", "Tubular adenoma"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8261/0", "Benign", "Villous adenoma"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8263/0", "Benign", "Tubulovillous adenoma"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8148/0", "Benign", "Dysplasia (intraepithelial neoplasia), low grade"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Dysplasia (intraepithelial neoplasia), high grade"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "", "", "Hyperplastic polyp"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8213/0", "Benign", "Sessile serrated adenoma/polyp"),
("Colon and rectum", "Epithelial tumours", "Premalignant lesions", "8213/0", "Benign", "Traditional serrated adenoma"),
("Colon and rectum", "Epithelial tumours", "Hamartomas", "", "", "Cowden-associated polyp"),
("Colon and rectum", "Epithelial tumours", "Hamartomas", "", "", "Juvenile polyp"),
("Colon and rectum", "Epithelial tumours", "Hamartomas", "", "", "Peutz-Jeghers polyp"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8201/3", "Malignant", "Cribriform comedo-type adenocarcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8510/3", "Malignant", "Medullary carcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8265/3", "Malignant", "Micropapillary carcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8213/3", "Malignant", "Serrated adenocarcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8490/3", "Malignant", "Signet ring cell carcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8032/3", "Malignant", "Spinole cell carcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("Colon and rectum", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8241/3", "Malignant", "EC cell, serotonin-producing neuroendocrine tumour (NET)"),
("Colon and rectum", "Epithelial tumours", "Neuroendocrine neoplasms", "8152/1", "Unspecified, borderline or uncertain behaviour", "L cell, Glucagon-like peptide-producing and PP/PYY-producing NETs"),
("Colon and rectum", "Mesenchymal tumours", "", "8890/0", "Benign", "Leiomyoma"),
("Colon and rectum", "Mesenchymal tumours", "", "8850/0", "Benign", "Lipoma"),
("Colon and rectum", "Mesenchymal tumours", "", "9120/3", "Malignant", "Angiosarcoma"),
("Colon and rectum", "Mesenchymal tumours", "", "8936/3", "Malignant", "Gastrointestinal stromal tumour"),
("Colon and rectum", "Mesenchymal tumours", "", "9140/3", "Malignant", "Kaposi sarcoma"),
("Colon and rectum", "Mesenchymal tumours", "", "8890/3", "Malignant", "Leiomyosarcoma"),
("Colon and rectum", "Lymphomas", "", "", "", ""),
("Colon and rectum", "Secondary tumours", "", "", "", ""),
("Anal canal", "Epithelial tumours", "Premalignant lesions", "8077/0", "Benign", "Anal intraepithelial neoplasia (dysplasia), low grade"),
("Anal canal", "Epithelial tumours", "Premalignant lesions", "8077/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Anal intraepithelial neoplasia (dysplasia), high grade"),
("Anal canal", "Epithelial tumours", "Premalignant lesions", "", "", "Bowen disease"),
("Anal canal", "Epithelial tumours", "Premalignant lesions", "", "", "Perianal squamous intraepithelial neoplasia"),
("Anal canal", "Epithelial tumours", "Premalignant lesions", "8542/3", "Malignant", "Paget disease"),
("Anal canal", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("Anal canal", "Epithelial tumours", "Carcinomas", "8051/3", "Malignant", "Verrucous carcinoma"),
("Anal canal", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Anal canal", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Anal canal", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("Anal canal", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Anal canal", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Anal canal", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Anal canal", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Anal canal", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Anal canal", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Anal canal", "Mesenchymal tumours", "", "", "", ""),
("Anal canal", "Secondary tumours", "", "", "", "");
INSERT INTO chus_morphology_coding (tumour_type, tumour_cell_origin, tumour_category, morphology_code, behaviour_code, morphology_description)
VALUES
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Benign", "8170/0", "Benign", "Hepatocellular adenoma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Benign", "", "", "Focal nodular hyperplasia"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignancy-associated and premalignant lesions", "", "", "Large cell change (formerly 'dysplasia')"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignancy-associated and premalignant lesions", "", "", "Small cell change (formerly 'dysplasia')"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignancy-associated and premalignant lesions", "", "", "Dysplastic nodules, Low grade"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignancy-associated and premalignant lesions", "", "", "Dysplastic nodules, High grade"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignant", "8170/3", "Malignant", "Hepatocellular carcinoma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignant", "8171/3", "Malignant", "Hepatocellular carcinoma, fibrolamellar variant"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignant", "8970/3", "Malignant", "Hepatoblastoma, epithelial variants"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: hepatocellular", "Malignant", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Benign", "8160/0", "Benign", "Bile duct adenoma (peribiliary gland hamartoma and others)"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Benign", "8202/0", "Benign", "Microcystic adenoma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Benign", "9013/0", "Benign", "Biliary adenofibroma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Biliary intraepithelial neoplasia, grade 3 (BiIlN-3)"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Premalignant lesions", "8503/0", "Benign", "Intraductal papillary neoplasm with low- or intermediate-grade intraepithelial neoplasia"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Premalignant lesions", "8503/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Intraductal papillary neoplasm with high-grade intraepithelial neoplasia"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Premalignant lesions", "8470/0", "Benign", "Mucinous cystic neoplasm with low- or intermediate-grade intraepithelial neoplasia"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Premalignant lesions", "8470/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Mucinous cystic neoplasm with high-grade intraepithelial neoplasia"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Malignant", "8160/3", "Malignant", "Intrahepatic cholangiocarcinoma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Malignant", "8503/3", "Malignant", "Intraductal papillary neoplasm with an associated invasive carcinoma"),
("Liver and intrahepatic bile ducts", "Epithelial tumours: biliary", "Malignant", "8470/3", "Malignant", "Mucinous cystic neoplasm with an associated invasive carcinoma"),
("Liver and intrahepatic bile ducts", "Malignancies of mixed or uncertain origin", "", "8975/1", "Unspecified, borderline or uncertain behaviour", "Calcifying nested epithelial stromal tumour"),
("Liver and intrahepatic bile ducts", "Malignancies of mixed or uncertain origin", "", "8980/3", "Malignant", "Carcinosarcoma"),
("Liver and intrahepatic bile ducts", "Malignancies of mixed or uncertain origin", "", "8180/3", "Malignant", "Combined hepatocellular-cholangiooarcinoma"),
("Liver and intrahepatic bile ducts", "Malignancies of mixed or uncertain origin", "", "8970/3", "Malignant", "Hepatoblastoma, mixed epithelial-mesenchymal"),
("Liver and intrahepatic bile ducts", "Malignancies of mixed or uncertain origin", "", "8963/3", "Malignant", "Malignant rhabdoid tumour"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "8860/0", "Benign", "Angiomyolipoma (PEComa)"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "9121/0", "Benign", "Cavernous haemangioma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "9131/0", "Benign", "Infantile haemangioma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "", "", "Inflammatory pseudotumour"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "9170/0", "Benign", "Lymphangioma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "", "", "Lymphangiomatosis"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "", "", "Mesenchymal hamartoma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Benign", "8815/0", "Benign", "Solitary fibrous tumour"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "9120/3", "Malignant", "Angiosarcoma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "8991/3", "Malignant", "Embryonal sarcoma (undifferentiated sarcoma)"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "9133/3", "Malignant", "Epithelioid haemangioendothelioma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "9140/3", "Malignant", "Kaposi sarcoma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "8890/3", "Malignant", "Leiomyosarcoma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "8900/3", "Malignant", "Rhabdomyosarcoma"),
("Liver and intrahepatic bile ducts", "Mesenchymal tumours", "Malignant", "9040/3", "Malignant", "Synovial sarcoma"),
("Liver and intrahepatic bile ducts", "Germ cell tumours", "", "9080/1", "Unspecified, borderline or uncertain behaviour", "Teratoma"),
("Liver and intrahepatic bile ducts", "Germ cell tumours", "", "9071/3", "Malignant", "Yolk sac tumour (endodermal sinus tumour)"),
("Liver and intrahepatic bile ducts", "Lymphomas", "", "", "", ""),
("Liver and intrahepatic bile ducts", "Secondary tumours", "", "", "", ""),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8140/0", "Benign", "Adenoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8211/0", "Benign", "Tubular adenoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8260/0", "Benign", "Papillary adenoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8263/0", "Benign", "Tubulopapillary adenoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Biliary intraepithelial neoplasia, grade 3 (BiIIN-3)"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8503/0", "Benign", "Intracystic (gallbladder) or intraductal (bile ducts) papillary neoplasm with low- or intermediate-grade intraepithelial neoplasia"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8503/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Intracystic (gallbladder) or intraductal (bile ducts) papillary neoplasm with high-grade intraepithelial neoplasia"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8470/0", "Benign", "Mucinous cystic neoplasm with low- or intermediate-grade intraepithelial neoplasia"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Premalignant lesions", "8470/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Mucinous cystic neoplasm with high-grade intraepithelial neoplasia"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma, biliary type"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8140/3", "Malignant", "Adenocarcinoma, gastric foveolar type"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8144/3", "Malignant", "Adenocarcinoma, intestinal type"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8310/3", "Malignant", "Clear cell adenocarcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8480/3", "Malignant", "Mucinous adenocarcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8490/3", "Malignant", "Signet ring cell carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8503/3", "Malignant", "Intracystic(gallbladder) or intraductal (bile ducts) papillary neoplasm with an associated invasive carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8470/3", "Malignant", "Mucinous cystic neoplasm with an associated invasive carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8070/3", "Malignant", "Squamous cell carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Carcinomas", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1 (carcinoid)"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8244/3", "Malignant", "Mixed adenoneuroendocrine carcinoma"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8243/3", "Malignant", "Goblet cell carcinoid"),
("Gallbladder and extrahepatic bile ducts", "Epithelial tumours", "Neuroendocrine neoplasms", "8245/1", "Unspecified, borderline or uncertain behaviour", "Tubular carcinoid"),
("Gallbladder and extrahepatic bile ducts", "Mesenchymal tumours", "", "9580/0", "Benign", "Granular cell tumour"),
("Gallbladder and extrahepatic bile ducts", "Mesenchymal tumours", "", "8890/0", "Benign", "Leiomyoma"),
("Gallbladder and extrahepatic bile ducts", "Mesenchymal tumours", "", "9140/3", "Malignant", "Kaposi sarcoma"),
("Gallbladder and extrahepatic bile ducts", "Mesenchymal tumours", "", "8890/3", "Malignant", "Leiomyosarcoma"),
("Gallbladder and extrahepatic bile ducts", "Mesenchymal tumours", "", "8900/3", "Malignant", "Rhabdomyosarcoma"),
("Gallbladder and extrahepatic bile ducts", "Lymphomas", "", "", "", ""),
("Gallbladder and extrahepatic bile ducts", "Secondary tumours", "", "", "", ""),
("Pancreas", "Epithelial tumours", "Benign", "8551/0", "Benign", "Acinar cell cystadenoma"),
("Pancreas", "Epithelial tumours", "Benign", "8441/0", "Benign", "Serous cystadenoma"),
("Pancreas", "Epithelial tumours", "Premalignant lesions", "8148/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Pancreatic intraepithelial neoplasia, grade 3 (PanIN-3)"),
("Pancreas", "Epithelial tumours", "Premalignant lesions", "8453/0", "Benign", "Intraductal papillary mucinous neoplasm with low- or intermediate-grade dysplasia"),
("Pancreas", "Epithelial tumours", "Premalignant lesions", "8453/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Intraductal papillary mucinous neoplasm with high-grade dysplasia"),
("Pancreas", "Epithelial tumours", "Premalignant lesions", "8503/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Intraductal tubulopapillary neoplasm"),
("Pancreas", "Epithelial tumours", "Premalignant lesions", "8470/0", "Benign", "Mucinous cystic neoplasm with low- or intermediate-grade dysplasia"),
("Pancreas", "Epithelial tumours", "Premalignant lesions", "8470/2", "Carcinoma in situ and grade III intraepithelial neoplasia", "Mucinous cystic neoplasm with high-grade dysplasia"),
("Pancreas", "Epithelial tumours", "Malignant", "8500/3", "Malignant", "Ductal adenocarcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8560/3", "Malignant", "Adenosquamous carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8480/3", "Malignant", "Colloid carcinoma (mucinous noncystic carcinoma)"),
("Pancreas", "Epithelial tumours", "Malignant", "8576/3", "Malignant", "Hepatoid carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8510/3", "Malignant", "Medullary carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8490/3", "Malignant", "Signet ring cell carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8020/3", "Malignant", "Undifferentiated carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8035/3", "Malignant", "Undifferentiated carcinoma with osteoclast-like giant cells"),
("Pancreas", "Epithelial tumours", "Malignant", "8550/3", "Malignant", "Acinar cell carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8551/3", "Malignant", "Acinar cell cystadenocarcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8453/3", "Malignant", "Intraductal papillary mucinous neoplasm with an associated invasive carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8552/3", "Malignant", "Mixed acinar-ductal carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8154/3", "Malignant", "Mixed acinar-neuroendocrine carcinoma");
INSERT INTO chus_morphology_coding (tumour_type, tumour_cell_origin, tumour_category, morphology_code, behaviour_code, morphology_description)
VALUES
("Pancreas", "Epithelial tumours", "Malignant", "8154/3", "Malignant", "Mixed acinar-neuroendocrine-ductal carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8154/3", "Malignant", "Mixed ductal-neuroendocrine carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8470/3", "Malignant", "Mucinous cystic neoplasm with an associated invasive carcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8971/3", "Malignant", "Pancreatoblastoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8441/3", "Malignant", "Serous cystadenocarcinoma"),
("Pancreas", "Epithelial tumours", "Malignant", "8452/3", "Malignant", "Solid-pseudopapillary neoplasm"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8150/0", "Benign", "Pancreatic neuroendocrine microadenoma"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8150/3", "Malignant", "Nonfunctional pancreatic neuroendocrine tumour (NET ) G1, G2"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8240/3", "Malignant", "Neuroendocrine tumour (NET) G1"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8249/3", "Malignant", "Neuroendocrine tumour (NET) G2"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8246/3", "Malignant", "Neuroendocrine carcinoma (NEC)"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8013/3", "Malignant", "Large cell neuroendocrine carcinoma (NEC)"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8041/3", "Malignant", "Small cell neuroendocrine carcinoma (NEC)"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8241/3", "Malignant", "EC cell, serotonin-producing neuroendocrine tumour (NET) (carcinoid)"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8153/3", "Malignant", "Gastrinoma"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8152/3", "Malignant", "Glucagonoma"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8151/3", "Malignant", "Insulinoma"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8156/3", "Malignant", "Somatostatinoma"),
("Pancreas", "Epithelial tumours", "Neuroendocrine neoplasms", "8155/3", "Malignant", "VIPoma"),
("Pancreas", "Mature teratoma", "", "9080/0", "Benign", ""),
("Pancreas", "Mesenchymal tumours", "", "", "", ""),
("Pancreas", "Lymphomas", "", "", "", ""),
("Pancreas", "Secondary tumours", "", "", "", "");

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

SET @created = (SELECT NOW() FROM users where id = 1);
SET @created_by = (SELECT id FROM users where id = 1);

INSERT INTO drugs (generic_name)
VALUES
("Abraxane"),
("Aflibercept"),
("Bevacizumab"),
("Capecitabine"),
("Carboplatin"),
("Cetuximab"),
("Cisplatin"),
("Cyramza"),
("Docetaxel"),
("Doxorubicin"),
("Epirubicin"),
("Erlotinib"),
("Etoposide"),
("Fluorouracil"),
("Gemcitabine"),
("Imatinib mesylate"),
("Irinotecan"),
("Leucovorin"),
("Mitomycin"),
("Oxaliplatin"),
("Paclitaxel"),
("Panitumumab"),
("RAD001"),
("Regorafenib"),
("Sorafenib"),
("Sunitinib maleate"),
("Trastuzumab"),
("Zaltrap");
UPDATE drugs SET created = @created, created_by = @created_by, modified = @created, modified_by = @created_by;
INSERT INTO drugs_revs (id, generic_name, modified_by, version_created) (SELECT id, generic_name, modified_by, modified FROM drugs);

SET @protocol_control_id = (SELECT id FROM protocol_controls WHERE type = 'systemic therapy');

INSERT INTO protocol_masters (code, protocol_control_id)
VALUES
("Bevacizumab + IFL", @protocol_control_id),
("CAPIRI", @protocol_control_id),
("CAPOX", @protocol_control_id),
("ECF", @protocol_control_id),
("FOLFIRI", @protocol_control_id),
("FOLFIRINOX", @protocol_control_id),
("FOLFOX", @protocol_control_id),
("FOLFOXIRI", @protocol_control_id),
("GEM-CAP", @protocol_control_id),
("GemCis", @protocol_control_id),
("GemIri", @protocol_control_id),
("GemOx", @protocol_control_id),
("IFL", @protocol_control_id),
("LV5FU2", @protocol_control_id);

INSERT INTO chus_pd_systemic_therapies (protocol_master_id) (SELECT id FROM protocol_masters);
UPDATE protocol_masters SET created = @created, created_by = @created_by, modified = @created, modified_by = @created_by;
INSERT INTO protocol_masters_revs (id, code, protocol_control_id, modified_by, version_created) (SELECT id, code, protocol_control_id, modified_by, modified FROM protocol_masters);
INSERT INTO chus_pd_systemic_therapies_revs (protocol_master_id, version_created) (SELECT id, modified FROM protocol_masters);

SET @protocol_extend_control_id = (SELECT id FROM protocol_extend_controls WHERE detail_tablename = 'chus_pe_systemic_therapies');
ALTER TABLE protocol_extend_masters ADD COLUMN temp_drug_id varchar(100);

INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = 'Bevacizumab + IFL' AND Dr.generic_name IN ('Fluorouracil', 'Bevacizumab', 'Leucovorin', 'Irinotecan'));
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = 'xxxx' AND Dr.generic_name IN ('xxx', 'xxx', 'xxx', 'xxx'));
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "FOLFIRI" AND Dr.generic_name IN ("Zaltrap", "Fluorouracil", "Leucovorin", "Irinotecan"));
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "FOLFIRINOX" AND Dr.generic_name IN ("Fluorouracil", "Leucovorin", "Oxaliplatin", "Irinotecan"));
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "ECF" AND Dr.generic_name IN ("Epirubicin", "Fluorouracil", "Cisplatin"));		
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "FOLFOX" AND Dr.generic_name IN ("Fluorouracil", "Leucovorin", "Oxaliplatin"));		
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "FOLFOXIRI" AND Dr.generic_name IN ("Fluorouracil", "Oxaliplatin", "Irinotecan"));		
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "IFL" AND Dr.generic_name IN ("Fluorouracil", "Leucovorin", "Irinotecan"));		
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "GEM-CAP" AND Dr.generic_name IN ("Gemcitabine", "Capecitabine"));				
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "GemCis" AND Dr.generic_name IN ("Cisplatin", "Gemcitabine"));				
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "GemIri" AND Dr.generic_name IN ("Gemcitabine", "Irinotecan"));				
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "GemOx" AND Dr.generic_name IN ("Gemcitabine", "Oxaliplatin"));				
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "CAPIRI" AND Dr.generic_name IN ("Irinotecan", "Capecitabine"));				
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "CAPOX" AND Dr.generic_name IN ("Oxaliplatin", "Capecitabine"));				
INSERT INTO protocol_extend_masters (protocol_extend_control_id, protocol_master_id, temp_drug_id) (SELECT @protocol_extend_control_id, Pr.id, Dr.id FROM protocol_masters Pr, drugs Dr WHERE Pr.code = "LV5FU2" AND Dr.generic_name IN ("Fluorouracil", "Leucovorin"));				

INSERT INTO chus_pe_systemic_therapies (protocol_extend_master_id, drug_id) (SELECT id, temp_drug_id FROM protocol_extend_masters);
ALTER TABLE protocol_extend_masters DROP COLUMN temp_drug_id;
UPDATE protocol_extend_masters SET created = @created, created_by = @created_by, modified = @created, modified_by = @created_by;
INSERT INTO protocol_extend_masters_revs (id, protocol_extend_control_id, protocol_master_id, modified_by, version_created) (SELECT id, protocol_extend_control_id, protocol_master_id, modified_by, modified FROM protocol_extend_masters);
INSERT INTO chus_pe_systemic_therapies_revs (protocol_extend_master_id, drug_id, version_created) (SELECT protocol_extend_master_id, drug_id, @created FROM chus_pe_systemic_therapies);

