#run after custom_post_2.3.6.sql
REPLACE INTO i18n (id, en, fr) VALUES
("cap report - larynx (ld vers.)", "CAP Report - Larynx (ld vers.)", ""),
("cap report - pharynx (ld vers.)", "CAP Report - Pharynx (ld vers.)", ""),
("cap report - lip/oral (ld vers.)", "CAP Report - Lip/Oral (ld vers.)", ""),
("cap report - sal.glands (ld vers.)", "CAP Report - Sal.Glands (ld vers.)", ""),
("cap report - nas/sinus (ld vers.)", "CAP Report - Nas/Sinus (ld vers.)", ""),
("cap report - thyroid (ld vers.)", "CAP Report - Thyroid (ld vers.)", ""),
("cap report - small intestine", "CAP Report - Small Intestine", ""),         
("pt4b: Very advanced local disease (larynx pt mod)", "pt4b: Very advanced local disease. Very advanced local disease. Tumor invades prevertebral space, encases carotid artery, or invades mediastinal structures", "pt4b"),
("pt4a: Moderately advanced local disease (larynx pt mod)", "pt4a: Moderately advanced local disease. Moderately advanced local disease. Tumor invades through the thyroid cartilage and/or invades tissues beyond the larynx.", ""),
("pt4a: Moderately advanced local disease (larynx pt sub mod)", "pt4a: Moderately advanced local disease. Tumor invades cricoid or thyroid cartilage and/or invades tissues beyond the larynx.", ""); 

UPDATE structure_fields SET  `language_label`='squamous cell carcinoma, conventional' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_larynx' AND field='hist_type_squamous' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_formats SET `language_heading`='tumor laterality' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_larynx') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_larynx' AND `field`='laterality_is_right' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `language_heading`='tumor site' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_larynx') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_larynx' AND `field`='site_is_supraglottis' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

DELETE FROM structure_value_domains_permissible_values WHERE structure_value_domain_id=416 AND structure_permissible_value_id=1564;
DELETE FROM structure_value_domains_permissible_values WHERE structure_value_domain_id=416 AND structure_permissible_value_id=1565;
INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("pt4b", "pt4b: Very advanced local disease (larynx pt mod)");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="qc_gastro_cap_larynx_pt_supra"),  (SELECT id FROM structure_permissible_values WHERE value="pt4b" AND language_alias="pt4b: Very advanced local disease (larynx pt mod)"), "0", "1");
INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("pt4a", "pt4a: Moderately advanced local disease (larynx pt mod)");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="qc_gastro_cap_larynx_pt_supra"),  (SELECT id FROM structure_permissible_values WHERE value="pt4a" AND language_alias="pt4a: Moderately advanced local disease (larynx pt mod)"), "0", "1");

DELETE FROM structure_value_domains_permissible_values WHERE structure_value_domain_id=418 AND structure_permissible_value_id=1564;
DELETE FROM structure_value_domains_permissible_values WHERE structure_value_domain_id=418 AND structure_permissible_value_id=1565;
INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("pt4a", "pt4a: Moderately advanced local disease (larynx pt mod)");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="qc_gastro_cap_larynx_pt_sub"),  (SELECT id FROM structure_permissible_values WHERE value="pt4a" AND language_alias="pt4a: Moderately advanced local disease (larynx pt mod)"), "0", "1");
INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("pt4b", "pt4b: Very advanced local disease (larynx pt mod)");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="qc_gastro_cap_larynx_pt_sub"),  (SELECT id FROM structure_permissible_values WHERE value="pt4b" AND language_alias="pt4b: Very advanced local disease (larynx pt mod)"), "0", "1");

INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("pn2c", "pn2c: Metastasis in bilateral or contralateral lymph nodes, none more than 6 cm in greatest dimension");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="qc_gastro_cap_larynx_pn"),  (SELECT id FROM structure_permissible_values WHERE value="pn2c" AND language_alias="pn2c: Metastasis in bilateral or contralateral lymph nodes, none more than 6 cm in greatest dimension"), "0", "1");

UPDATE structure_formats SET `language_heading`='specimen laterality' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_lip_oral') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_lip_oral' AND `field`='laterality_is_right' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `language_heading`='tumor site' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_lip_oral') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_lip_oral' AND `field`='site_is_vermilion_border_upper_lip' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `language_heading`='specimen laterality' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_sal_glands') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_sal_glands' AND `field`='laterality' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='laterality_r_l_b_ns') AND `flag_confidential`='0');
UPDATE structure_formats SET `language_heading`='tumor site' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_sal_glands') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_sal_glands' AND `field`='site_parotid_gland' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_column`='3' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_sal_glands') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_sal_glands' AND `field`='histo_grade_specify' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `language_heading`='specimen laterality' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_nas_sinus') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_nas_sinus' AND `field`='laterality_right' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `language_heading`='tumor site' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_nas_sinus') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_nas_sinus' AND `field`='site_nasal_cavity' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_fields SET  `language_label`='squamous cell carcinoma, conventional' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_pharynx' AND field='histo_squamous_cell_carcinoma' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_formats SET `language_heading`='tumor site' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_pharynx') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_pharynx' AND `field`='site_oropharynx' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='60' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_pharynx') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_pharynx' AND `field`='histo_undifferentiated_carcinoma' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='61' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_pharynx') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_pharynx' AND `field`='histo_differentiated_carcinoma' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='59' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_pharynx') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_pharynx' AND `field`='histo_nonkeratinizing_carcinoma' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `language_heading`='tumor laterality' WHERE structure_id=(SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='laterality_right_lobe' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

ALTER TABLE qc_gastro_dxd_cap_thyroid
ADD COLUMN add_path_adenoma CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_adenomatoid_nodule CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_diffuse_hyperplasia CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_thyroiditis CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_thyroiditis_advanced CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_thyroiditis_focal CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_thyroiditis_palpation CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_thyroiditis_other CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_thyroiditis_other_specify VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN add_path_parathyroid_gland CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_parathyroid_gland_within_normal_limits CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_parathyroid_gland_hypercellular CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_parathyroid_gland_other CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_parathyroid_gland_other_specify VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN add_path_c_cell_hyperplasia CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_none_identified CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_other CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN add_path_other_specify VARCHAR(50) NOT NULL DEFAULT '',
MODIFY COLUMN deleted BOOLEAN NOT NULL DEFAULT false AFTER add_path_other_specify; 
ALTER TABLE qc_gastro_dxd_cap_thyroid_revs
ADD COLUMN adenoma CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN adenomatoid_nodule CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN diffuse_hyperplasia CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN thyroiditis CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN thyroiditis_advanced CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN thyroiditis_focal CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN thyroiditis_palpation CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN thyroiditis_other CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN thyroiditis_other_specify VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN parathyroid_gland CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN parathyroid_gland_within_normal_limits CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN parathyroid_gland_hypercellular CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN parathyroid_gland_other CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN parathyroid_gland_other_specify VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN c_cell_hyperplasia CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN none_identified CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN other CHAR(1) NOT NULL DEFAULT '',
ADD COLUMN other_specify VARCHAR(50) NOT NULL DEFAULT '',
MODIFY version_id INT NOT NULL AFTER other_specify,
MODIFY version_created DATETIME NOT NULL AFTER version_id;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_adenoma', 'checkbox',  NULL , '0', '', '', '', 'adenoma', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_adenomatoid_nodule', 'checkbox',  NULL , '0', '', '', '', 'Adenomatoid nodule(s) or Nodular follicular disease (eg, nodular hyperplasia, goitrous thyroid)', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_diffuse_hyperplasia', 'checkbox',  NULL , '0', '', '', '', 'Diffuse hyperplasia (Graves’ disease)', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_thyroiditis', 'checkbox',  NULL , '0', '', '', '', 'thyroiditis', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_thyroiditis_advanced', 'checkbox',  NULL , '0', '', '', '', '', 'Advanced'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_thyroiditis_focal', 'checkbox',  NULL , '0', '', '', '', '', 'Focal (nonspecific)'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_thyroiditis_palpation', 'checkbox',  NULL , '0', '', '', '', '', 'Palpation'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_thyroiditis_other', 'checkbox',  NULL , '0', '', '', '', '', 'other'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_thyroiditis_other_specify', 'input',  NULL , '0', '', '', '', '', 'specify'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_parathyroid_gland', 'checkbox',  NULL , '0', '', '', '', 'Parathyroid gland(s)', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_parathyroid_gland_within_normal_limits', 'checkbox',  NULL , '0', '', '', '', '', 'Within normal limits'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_parathyroid_gland_hypercellular', 'checkbox',  NULL , '0', '', '', '', '', 'Hypercellular'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_parathyroid_gland_other', 'checkbox',  NULL , '0', '', '', '', '', 'other'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_parathyroid_gland_other_specify', 'input',  NULL , '0', '', '', '', '', 'specify'), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_c_cell_hyperplasia', 'checkbox',  NULL , '0', '', '', '', 'C-cell hyperplasia', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_none_identified', 'checkbox',  NULL , '0', '', '', '', 'None identified', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_other', 'checkbox',  NULL , '0', '', '', '', 'other', ''), 
('Clinicalannotation', 'DiagnosisDetail', 'qc_gastro_dxd_cap_thyroid', 'add_path_other_specify', 'input',  NULL , '0', '', '', '', '', 'specify');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_adenoma' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='adenoma' AND `language_tag`=''), '4', '134', 'additional pathologic findings', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_adenomatoid_nodule' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='Adenomatoid nodule(s) or Nodular follicular disease (eg, nodular hyperplasia, goitrous thyroid)' AND `language_tag`=''), '4', '135', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_diffuse_hyperplasia' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='Diffuse hyperplasia (Graves’ disease)' AND `language_tag`=''), '4', '136', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_thyroiditis' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='thyroiditis' AND `language_tag`=''), '4', '137', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_thyroiditis_advanced' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='Advanced'), '4', '138', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_thyroiditis_focal' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='Focal (nonspecific)'), '4', '139', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_thyroiditis_palpation' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='Palpation'), '4', '140', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_thyroiditis_other' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='other'), '4', '141', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_thyroiditis_other_specify' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='specify'), '4', '142', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_parathyroid_gland' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='Parathyroid gland(s)' AND `language_tag`=''), '4', '143', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_parathyroid_gland_within_normal_limits' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='Within normal limits'), '4', '144', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_parathyroid_gland_hypercellular' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='Hypercellular'), '4', '145', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_parathyroid_gland_other' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='other'), '4', '146', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_parathyroid_gland_other_specify' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='specify'), '4', '147', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_c_cell_hyperplasia' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='C-cell hyperplasia' AND `language_tag`=''), '4', '148', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_none_identified' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='None identified' AND `language_tag`=''), '4', '149', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_other' AND `type`='checkbox' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='other' AND `language_tag`=''), '4', '150', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='qc_gastro_dxd_cap_thyroid'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisDetail' AND `tablename`='qc_gastro_dxd_cap_thyroid' AND `field`='add_path_other_specify' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='specify'), '4', '151', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');

UPDATE structure_fields SET  `language_label`='thyroiditis advanced',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_thyroiditis_advanced' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_fields SET  `language_label`='thyroiditis focal (nonspecific)',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_thyroiditis_focal' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_fields SET  `language_label`='thyroiditis palpation',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_thyroiditis_palpation' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_fields SET  `language_label`='thyroiditis other',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_thyroiditis_other' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_fields SET  `language_label`='Parathyroid gland(s) within normal limits',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_parathyroid_gland_within_normal_limits' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_fields SET  `language_label`='Parathyroid gland(s) hypercellular',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_parathyroid_gland_hypercellular' AND `type`='checkbox' AND structure_value_domain  IS NULL ;
UPDATE structure_fields SET  `language_label`='Parathyroid gland(s) other',  `language_tag`='' WHERE model='DiagnosisDetail' AND tablename='qc_gastro_dxd_cap_thyroid' AND field='add_path_parathyroid_gland_other' AND `type`='checkbox' AND structure_value_domain  IS NULL ;

DELETE FROM structure_value_domains_permissible_values WHERE structure_value_domain_id=418 and structure_permissible_value_id IN(1581, 1758, 1582);
INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("pt4a", "pt4a: Moderately advanced local disease (larynx pt sub mod)");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="qc_gastro_cap_larynx_pt_sub"),  (SELECT id FROM structure_permissible_values WHERE value="pt4a" AND language_alias="pt4a: Moderately advanced local disease (larynx pt sub mod)"), "0", "1");


