<?php
/** **********************************************************************
 * NBI Project..
 * ***********************************************************************
 *
 * InventoryManagement plugin custom code
 *
 * @author N. Luc - CTRNet (nicolas.luc@gmail.com)
 * @since 2018-04-06
 */

// Barcode are generated by the system.
// Generate system's barcodes
$this->AliquotMaster->regenerateAliquotBarcode();