-- ------------------------------------------------------
-- ATiM xxxxx Data Script
-- version: 2.7.2
-- ------------------------------------------------------

-- --------------------------------------------------------------------------------
-- Hide Misc Identifier dates and notes fields
-- --------------------------------------------------------------------------------

UPDATE structure_formats SET `flag_add`='0', `flag_edit`='0', `flag_detail`='0' 
WHERE structure_id IN (SELECT id FROM structures WHERE alias IN ('incrementedmiscidentifiers', 'miscidentifiers'))
AND structure_field_id IN (SELECT id FROM structure_fields WHERE `model`='MiscIdentifier' AND `tablename`='misc_identifiers' AND `field` IN ('effective_date', 'expiry_date','notes'));

-- --------------------------------------------------------------------------------
-- Create unique and auto-generated 'Bank Participant Identifier'
-- ................................................................................
-- Following scripts will create 'Bank Participant Identifier' for prostate,
-- breast and ovary biobanks. These identifiers are unique, generated by the system
-- (incremental) and can only be created once per participant.
-- The format of the identifiers will be generated as follow:
--    - Breast: 'BR9999999'
--    - Prostate: 'PR9999999'
--    - Ovary: 'Ov-Bk-9999999'
-- --------------------------------------------------------------------------------

INSERT INTO `misc_identifier_controls` (`id`, `misc_identifier_name`, `flag_active`, `display_order`, `autoincrement_name`, `misc_identifier_format`, `flag_once_per_participant`, `flag_confidential`, `flag_unique`, `pad_to_length`, `reg_exp_validation`, `user_readable_format`) 
VALUES
(1, 'BR_Nbr', 1, 1, 'br', 'BR%%key_increment%%', 0, 0, 1, 0, '', ''),
(2, 'PR_Nbr', 1, 2, 'pr', 'PR%%key_increment%%', 0, 0, 1, 0, '', ''),
(4, 'Ovary Bank Nbr', 1, 3, 'ov_key', 'OV-Bk-%%key_increment%%', 0, 0, 1, 0, '', '');

INSERT IGNORE INTO i18n (id,en,fr) 
VALUES 
('BR_Nbr', 'Breast - Bank#', 'Sein - Banque #'),
('PR_Nbr', 'Prostate - Bank#', 'Prostate - Banque #'),
('Ovary Bank Nbr', 'Ovary - Bank#', 'Ovaire - Banque #');

INSERT INTO `key_increments` (`key_name`, `key_value`) VALUES
('br', 124),
('ov_key', 1457),
('pr', 5943);

-- --------------------------------------------------------------------------------
-- Create unique 'Participant Identifier' as hospital number, health card number,
-- etc.
-- ................................................................................
-- These identifiers are unique and can only be created once per participant.
-- --------------------------------------------------------------------------------

INSERT INTO `misc_identifier_controls` (`id`, `misc_identifier_name`, `flag_active`, `display_order`, `autoincrement_name`, `misc_identifier_format`, `flag_once_per_participant`, `flag_confidential`, `flag_unique`, `pad_to_length`, `reg_exp_validation`, `user_readable_format`) 
VALUES
(3, 'hospital number', 1, 4, '', '', 1, 1, 1, 0, '', ''),
(6, 'health card', 1, 5, '', '', 1, 1, 1, 0, '', ''),
(7, 'care card', 1, 7, '', '', 1, 1, 1, 0, '', '');

INSERT IGNORE INTO i18n (id,en,fr) 
VALUES 
('RAMQ', 'RAMQ', 'RAMQ'),
('health card', 'Health Card', 'Carte Santé'),
('care card', 'CareCard', '');


-- --------------------------------------------------------------------------------
-- Create a 'Study Participant Identifier'
-- ................................................................................
-- Let user to create identifiers assigned to participants as part of a study.
-- --------------------------------------------------------------------------------

-- Create the new identifier

INSERT INTO `misc_identifier_controls` (`misc_identifier_name`, `flag_active`, `autoincrement_name`, `misc_identifier_format`, `flag_once_per_participant`, `flag_confidential`, `flag_unique`, `pad_to_length`, `reg_exp_validation`, `user_readable_format`, flag_link_to_study) 
VALUES
('patient study id', 1, '', '', 0, 0, 0, 0, '', '', '1');

INSERT INTO i18n (id,en,fr) 
VALUES 
('patient study id', 'Patient Study ID', 'ID Patient - Étude');

-- --------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------

UPDATE versions SET permissions_regenerated = 0;