-- Run before 2.2.0 update.

REPLACE INTO i18n (id, en, fr) VALUES
('core_appname', 'ATiM - Advanced Tissue Management', 'ATiM - Application de gestion avancée des tissus'),
('core_installname', "Hepatobiliary", "Hepato-Bilary");

INSERT INTO structure_permissible_values_customs (control_id, value, en, fr, created, created_by, modified, modified_by, deleted, deleted_date) VALUES
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='type of hepatitis'), 'alcohol', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='type of hepatitis'), 'HBV', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='type of hepatitis'), 'HBV + D', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='type of hepatitis'), 'HCV', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='type of hepatitis'), 'steatohepatitis', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='type of hepatitis'), 'other', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'alcohol', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'alpha1-antitrypsin deficiency', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'auto-immune', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'primary biliary', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'HBV', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'HBV + D', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'HCV', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'hemochromatosis', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'NASH', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'Wilson\'s disease', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='cirrhosis type'), 'other', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : reason of change'), 'toxicity', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : reason of change'), 'progression of the disease', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'cardiac', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'ear and labyrinth', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'endocrine', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'eye', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'gastrointestinal', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'hepatobiliary', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'immune system', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'infection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'metabolism', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'musculoskeletal', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'nervous system', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'psychiatric', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'renal and urinary', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'reproductive and breast', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'respiratory, thoracic and mediastinal', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'skin and subcutaneous tissue', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'social circumstance', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='chemotherapy : toxicity'), 'vascular', '', '', now(), 1, now(), 1, 0, NULL),

#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'right hepatectomy', '', '', now(), 1, now(), 1, 0, NULL),
#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'left hepatectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'right anterior sectionectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'right posterior sectionectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'left medial sectionectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'left lateral sectionectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'right trisectionectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'left trisectionectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'right hepatectomy + segment I', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'left hepatectomy + segment I', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'bisegmentectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'segmentectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'sub-segmentectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'liver biopsy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'hilar lymphadenectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'radiofrequency ablation', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'microwaves ablation', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'alcoholization', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'liver cyst fenestration', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'liver cyst resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'distal splenorenal shunt', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'mesocaval shunt', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'portacaval shunt', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'sugiura procedure', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'biliary drainage', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cholangiography', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cholangioscopy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cholecystectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cholecystostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'choledocoduodenostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'choledocojejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'hepaticojejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'lithotrypsy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'hepaticojejunostomy + gastrojejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'jejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'Whipple', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'distal pancreatectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'distal pancreatectomy + splenectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'central pancreatectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'enucleation', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'sub-total pancreatectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'Beger procedure', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'Frey procedure', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'Wirsungojejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cysto-gastrectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cysto-jejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'cysto-duodenectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'transduodenal Vater papilla resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'transduodenal sphincteroplasty', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'splenectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'splenectomy (partial)', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'portal vein resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'mesenteric artery resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'duodenectomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'colon resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'ileum resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'jejunum resection', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: principal surgery'), 'gastrectomy', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: local treatment type'), 'radiofrequency ablation', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: local treatment type'), 'microwaves ablation', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: local treatment type'), 'alcoholization', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'stomach', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'pancreas', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'jejunum', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'ileum', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'duodenum', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'diaphragm', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: other organ resection'), 'colon', '', '', now(), 1, now(), 1, 0, NULL),

#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Dagenais', '', '', now(), 1, now(), 1, 0, NULL),
#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Lapointe', '', '', now(), 1, now(), 1, 0, NULL),
#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Létourneau', '', '', now(), 1, now(), 1, 0, NULL),
#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Plasse', '', '', now(), 1, now(), 1, 0, NULL),
#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Roy', '', '', now(), 1, now(), 1, 0, NULL),
#((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Vandenbroucke-Menu', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey : surgeon list'), 'Turcotte', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: type of drain'), 'Jackson Pratt', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: type of drain'), 'Penrose', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: type of glue'), 'Bioglue', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: type of glue'), 'Tisseel', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgery: type of glue'), 'Oher', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : liver appearance'), 'cirrhosis', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : liver appearance'), 'fibrosis', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : liver appearance'), 'normal', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : liver appearance'), 'sinusoidal obstruction', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : liver appearance'), 'steatohepatitis', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : liver appearance'), 'steatosis', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : type of vascular occlusion'), 'none', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : type of vascular occlusion'), 'Pringle maneuver', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : type of vascular occlusion'), 'inferior vena cava occlusion', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : type of vascular occlusion'), 'superior vena cava occlusion', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver detail : type of vascular occlusion'), 'total vascular exclusion', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver pancreas : pancreas appearance'), 'soft', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver pancreas : pancreas appearance'), 'firm', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver pancreas : anastomosis type'), 'Wirsungojejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver pancreas : anastomosis type'), 'pancreaticojejunostomy', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='surgey - liver pancreas : anastomosis type'), 'pancreaticogastrostomy', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : hitologic type'), 'colorectal', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : hitologic type'), 'endocrine', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : hitologic type'), 'breast', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : hitologic type'), 'other', '', '', now(), 1, now(), 1, 0, NULL),

((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'bone', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'brain', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'breast ', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'colon', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'ileon', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'jejunum', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'pancreas', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'rectum', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'unknown', '', '', now(), 1, now(), 1, 0, NULL),
((SELECT id FROM structure_permissible_values_custom_controls WHERE name='liver metastasis : tumor site'), 'other', '', '', now(), 1, now(), 1, 0, NULL);

UPDATE structure_fields SET structure_value_domain=(SELECT id FROM structure_value_domains WHERE domain_name='qc_hb_tx_surgery_principal_surgery') WHERE structure_value_domain=(SELECT id FROM structure_value_domains WHERE domain_name='qc_hb_tx_surgery_associated_surgery');
DELETE FROM structure_value_domains WHERE domain_name='qc_hb_tx_surgery_associated_surgery';
DELETE FROM structure_permissible_values_custom_controls WHERE name='surgery: associated surgery';