<?php
/** **********************************************************************
 * UHN Project.
 * ***********************************************************************
 *
 * ClinicalAnnotation plugin custom code
 *
 * @author N. Luc - CTRNet (nicolas.luc@gmail.com)
 * @since 2018-05-04
 */

// Set default values displayed when user access the participant creation page for the first time
//-----------------------------------------------------------------------------------------------

// Get next partricipant identifier generated by Participant Model function.
// See .\app\Plugin\ClinicalAnnotation\Model\Custom\Participant.php
$nextParticipantIdentifier = $this->Participant->getNextParticipantIdentifier();

//Set default values in the defaultParticipantValues variable used in view
//See .\app\Plugin\ClinicalAnnotation\View\Participants\Hook\add.php code
$arryDefaultValues =array(
    'Participant.participant_identifier' => $nextParticipantIdentifier,
    'Participant.first_name' => 'to defined first name',
    'Participant.date_of_birth' => '1945-05'
);
$this->set('defaultParticipantValues', $arryDefaultValues);


