SELECT '****************' as msg
UNION
SELECT ' TODO' as msg
UNION
SELECT '
-- Define with ovcare the way we want to track results generated by other labs using ovcare bank samples
-- Define with ovcare the TMA data to track
-- Add gross image
-- What about barcode and label' as msg
-- TCGA ?
UNION ALL
SELECT '****************' as msg;

UPDATE structure_formats SET `flag_edit_readonly`='0' 
WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') 
AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `field`='aliquot_label');
UPDATE structure_formats SET `flag_override_label`='1', language_label = 'ovcare aliquot barcode'
WHERE structure_field_id IN (SELECT id FROM structure_fields WHERE `model` IN ('AliquotMaster','ViewAliquot') AND `field`='barcode' and language_label = 'barcode')
AND flag_override_label = '0';
UPDATE structure_formats SET language_label = 'used ovcare aliquot barcode' WHERE language_label = 'used aliquot barcode';

INSERT INTO i18n (id,en) VALUES ('ovcare aliquot barcode', 'Aliq. Syst. Code'),('used ovcare aliquot barcode','Used Aliq. Syst. Code');

UPDATE structure_formats SET `flag_add`='0' ,`flag_addgrid`='0' 
WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') 
AND structure_field_id IN (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `field`='barcode');

INSERT INTO `structure_validations` (`id`, `structure_field_id`, `rule`, `on_action`, `language_message`) VALUES
(null, (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `field`='aliquot_label'), 'notEmpty', '', '');




DROP VIEW view_aliquot_uses;
CREATE VIEW view_aliquot_uses AS 

SELECT 
CONCAT(source.id, 1) AS id,
aliq.id AS aliquot_master_id,
'sample derivative creation' AS use_definition, 
samp.sample_code AS use_code,
'' AS use_details,
source.used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
der.creation_datetime AS use_datetime,
der.creation_datetime_accuracy AS use_datetime_accuracy,
der.creation_by AS used_by,
source.created,
CONCAT('|inventorymanagement|aliquot_masters|listAllSourceAliquots|',samp.collection_id ,'|',samp.id) AS detail_url,
samp2.id AS sample_master_id,
samp2.collection_id AS collection_id
FROM source_aliquots AS source
INNER JOIN sample_masters AS samp ON samp.id = source.sample_master_id  AND samp.deleted != 1
INNER JOIN derivative_details AS der ON samp.id = der.sample_master_id  AND der.deleted != 1
INNER JOIN aliquot_masters AS aliq ON aliq.id = source.aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN sample_masters AS samp2 ON samp2.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE source.deleted != 1

UNION ALL

SELECT 
CONCAT(realiq.id, 2) AS id,
aliq.id AS aliquot_master_id,
'realiquoted to' AS use_definition, 
CONCAT(child.aliquot_label, ' (', child.barcode, ')') AS use_code,
'' AS use_details,
realiq.parent_used_volume AS used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
realiq.realiquoting_datetime AS use_datetime,
realiq.realiquoting_datetime_accuracy AS use_datetime_accuracy,
realiq.realiquoted_by AS used_by,
realiq.created,
CONCAT('|inventorymanagement|aliquot_masters|listAllRealiquotedParents|',child.collection_id,'|',child.sample_master_id,'|',child.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM realiquotings AS realiq
INNER JOIN aliquot_masters AS aliq ON aliq.id = realiq.parent_aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN aliquot_masters AS child ON child.id = realiq.child_aliquot_master_id AND child.deleted != 1
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE realiq.deleted != 1

UNION ALL

SELECT 
CONCAT(qc.id, 3) AS id,
aliq.id AS aliquot_master_id,
'quality control' AS use_definition, 
qc.qc_code AS use_code,
'' AS use_details,
qc.used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
qc.date AS use_datetime,
qc.date_accuracy AS use_datetime_accuracy,
qc.run_by AS used_by,
qc.created,
CONCAT('|inventorymanagement|quality_ctrls|detail|',aliq.collection_id,'|',aliq.sample_master_id,'|',qc.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM quality_ctrls AS qc
INNER JOIN aliquot_masters AS aliq ON aliq.id = qc.aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE qc.deleted != 1

UNION ALL

SELECT 
CONCAT(item.id, 4) AS id,
aliq.id AS aliquot_master_id,
'aliquot shipment' AS use_definition, 
sh.shipment_code AS use_code,
'' AS use_details,
'' AS used_volume,
'' AS aliquot_volume_unit,
sh.datetime_shipped AS use_datetime,
sh.datetime_shipped_accuracy AS use_datetime_accuracy,
sh.shipped_by AS used_by,
sh.created,
CONCAT('|order|shipments|detail|',sh.order_id,'|',sh.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM order_items AS item
INNER JOIN aliquot_masters AS aliq ON aliq.id = item.aliquot_master_id AND aliq.deleted != 1
INNER JOIN shipments AS sh ON sh.id = item.shipment_id AND sh.deleted != 1
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE item.deleted != 1

UNION ALL

SELECT 
CONCAT(alr.id, 5) AS id,
aliq.id AS aliquot_master_id,
'specimen review' AS use_definition, 
spr.review_code AS use_code,
'' AS use_details,
'' AS used_volume,
'' AS aliquot_volume_unit,
spr.review_date AS use_datetime,
spr.review_date_accuracy AS use_datetime_accuracy,
'' AS used_by,
alr.created,
CONCAT('|inventorymanagement|specimen_reviews|detail|',aliq.collection_id,'|',aliq.sample_master_id,'|',spr.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM aliquot_review_masters AS alr
INNER JOIN aliquot_masters AS aliq ON aliq.id = alr.aliquot_master_id AND aliq.deleted != 1
INNER JOIN specimen_review_masters AS spr ON spr.id = alr.specimen_review_master_id AND spr.deleted != 1
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE alr.deleted != 1

UNION ALL

SELECT 
CONCAT(aluse.id, 6) AS id,
aliq.id AS aliquot_master_id,
'internal use' AS use_definition, 
aluse.use_code,
aluse.use_details,
aluse.used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
aluse.use_datetime,
aluse.use_datetime_accuracy,
aluse.used_by,
aluse.created,
CONCAT('|inventorymanagement|aliquot_masters|detailAliquotInternalUse|',aliq.id,'|',aluse.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM aliquot_internal_uses AS aluse
INNER JOIN aliquot_masters AS aliq ON aliq.id = aluse.aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE aluse.deleted != 1;

UPDATE structure_fields SET type = 'integer_positive', setting = 'size=10' WHERE field = 'participant_identifier';

ALTER TABLE participants MODIFY participant_identifier INT(7) NOT NULL;
ALTER TABLE participants_revs MODIFY participant_identifier INt(7) NOT NULL;

INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES
("alive/intercurrent disease", "alive/intercurrent disease"), 
("alive/unknown", "alive/unknown");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) 
VALUES
((SELECT id FROM structure_value_domains WHERE domain_name="ovcare_vital_status"),  
(SELECT id FROM structure_permissible_values WHERE value="alive/intercurrent disease" AND language_alias="alive/intercurrent disease"), "2", "1"),
((SELECT id FROM structure_value_domains WHERE domain_name="ovcare_vital_status"),  
(SELECT id FROM structure_permissible_values WHERE value="alive/unknown" AND language_alias="alive/unknown"), "0", "1");
INSERT INTO i18n (id,en) VALUES
("alive/intercurrent disease", "Alive/Intercurrent Disease"), 
("alive/unknown", "Alive/Unknown");

INSERT INTO i18n (id,en) VALUES ("A","A"),("B","B"),("C","C");

ALTER TABLE ovcare_ed_lab_experimental_results 
	ADD COLUMN 05_008_brca1_mccluggage_int varchar(50) DEFAULT NULL AFTER tma_nkap,
	ADD COLUMN 05_008_brca1_mccluggage_per varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_int,
	ADD COLUMN 05_008_core_id varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_per,
	ADD COLUMN tma_parp1 varchar(50) DEFAULT NULL AFTER 05_008_core_id,
	ADD COLUMN tma_notch1 varchar(50) DEFAULT NULL AFTER tma_parp1,
	ADD COLUMN tma_folr1 varchar(50) DEFAULT NULL AFTER tma_notch1,
	ADD COLUMN tma_cxcr4 varchar(50) DEFAULT NULL AFTER tma_folr1;

ALTER TABLE ovcare_ed_lab_experimental_results_revs
	ADD COLUMN 05_008_brca1_mccluggage_int varchar(50) DEFAULT NULL AFTER tma_nkap,
	ADD COLUMN 05_008_brca1_mccluggage_per varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_int,
	ADD COLUMN 05_008_core_id varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_per,
	ADD COLUMN tma_parp1 varchar(50) DEFAULT NULL AFTER 05_008_core_id,
	ADD COLUMN tma_notch1 varchar(50) DEFAULT NULL AFTER tma_parp1,
	ADD COLUMN tma_folr1 varchar(50) DEFAULT NULL AFTER tma_notch1,
	ADD COLUMN tma_cxcr4 varchar(50) DEFAULT NULL AFTER tma_folr1;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', '05_008_brca1_mccluggage_int', 'input',  NULL , '0', 'size=10', '', '', '05_008 brca1 mccluggage int', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', '05_008_brca1_mccluggage_per', 'input',  NULL , '0', 'size=10', '', '', '05_008_brca1 mccluggage per', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', '05_008_core_id', 'input',  NULL , '0', 'size=10', '', '', '05_008 core id', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_parp1', 'input',  NULL , '0', 'size=10', '', '', 'tma parp1', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_notch1', 'input',  NULL , '0', 'size=10', '', '', 'tma notch1', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_folr1', 'input',  NULL , '0', 'size=10', '', '', 'tma folr1', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_cxcr4', 'input',  NULL , '0', 'size=10', '', '', 'tma cxcr4', '');

SET @structure_id = (SELECT id FROM structures WHERE alias = 'ovcare_ed_lab_experimental_results');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='05_008_brca1_mccluggage_int'), '4', '408', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='05_008_brca1_mccluggage_per'), '4', '409', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='05_008_core_id'), '4', '410', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_parp1'), '4', '411', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_notch1'), '4', '412', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_folr1'), '4', '413', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_cxcr4'), '4', '414', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'); 

INSERT INTO i18n (id,en) VALUES
('05_008 brca1 mccluggage int','05_008 BRCA1 McCluggage Intensity'),
('05_008_brca1 mccluggage per','05_008 BRCA1 McCluggage Percent'),
('05_008 core id','05_008 Core ID'),
('tma parp1','TMA_PARP1'),
('tma notch1','TMA_Notch1'),
('tma folr1','TMA_FOLR1'),
('tma cxcr4','TMA_CXCR4');

UPDATE structure_fields SET setting = 'size=25' WHERE tablename = 'ovcare_ed_lab_experimental_results';

ALTER TABLE `ovcare_ed_lab_experimental_results`
  MODIFY `brca1_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca1_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca2_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca1_hypermethylation` varchar(250) DEFAULT NULL,
  MODIFY `brca1_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca2_rna` varchar(250) DEFAULT NULL,
  MODIFY `powerplex` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_wt1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p21` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p53` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cyclin_d1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_brca1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p27` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_eef1a2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cycline` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ecad` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_e2f1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p63` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p16` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_egfr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_er` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_her2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_117` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_n` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_m` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128820745` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128822436` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pten` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_id4_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pakt` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ar` varchar(250) DEFAULT NULL,
  MODIFY `08_001_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_blocks` varchar(250) DEFAULT NULL,
  MODIFY `tma_ret` varchar(250) DEFAULT NULL,
  MODIFY `tma_fascin` varchar(250) DEFAULT NULL,
  MODIFY `tma_wt1` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53` varchar(250) DEFAULT NULL,
  MODIFY `tma_p16` varchar(250) DEFAULT NULL,
  MODIFY `tma_imp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_trka` varchar(250) DEFAULT NULL,
  MODIFY `tma_trkb` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_bin` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_hebo_mrna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_hace1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_hace1` varchar(250) DEFAULT NULL,
  MODIFY `tma_egfr` varchar(250) DEFAULT NULL,
  MODIFY `tma_birc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_cyclind1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75861572` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75921347` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_znf217_position51632374` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_mean` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_1` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_2` varchar(250) DEFAULT NULL,
  MODIFY `tma_cmyc` varchar(250) DEFAULT NULL,
  MODIFY `tma_vegfr2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pdgfr_beta` varchar(250) DEFAULT NULL,
  MODIFY `tma_mras` varchar(250) DEFAULT NULL,
  MODIFY `tma_nasp` varchar(250) DEFAULT NULL,
  MODIFY `tma_rb` varchar(250) DEFAULT NULL,
  MODIFY `tma_vimentin` varchar(250) DEFAULT NULL,
  MODIFY `tma_ckit` varchar(250) DEFAULT NULL,
  MODIFY `tma_kiss1` varchar(250) DEFAULT NULL,
  MODIFY `tma_e_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_alpha` varchar(250) DEFAULT NULL,
  MODIFY `tma_pthlh` varchar(250) DEFAULT NULL,
  MODIFY `tma_ki67` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100` varchar(250) DEFAULT NULL,
  MODIFY `tma_agr2_43` varchar(250) DEFAULT NULL,
  MODIFY `spry2_clid_hsq035516` varchar(250) DEFAULT NULL,
  MODIFY `spry4_clid_hsq027862` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043924` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq011236` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043441` varchar(250) DEFAULT NULL,
  MODIFY `ereg_clid_hsq025201` varchar(250) DEFAULT NULL,
  MODIFY `erbb3_clid_hsq001349` varchar(250) DEFAULT NULL,
  MODIFY `areg_clid_hsq045253` varchar(250) DEFAULT NULL,
  MODIFY `errfi1_clid_hsq001603` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq038313` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq010863` varchar(250) DEFAULT NULL,
  MODIFY `btc_clid_hsq035992` varchar(250) DEFAULT NULL,
  MODIFY `tma_apoj` varchar(250) DEFAULT NULL,
  MODIFY `tma_capg164` varchar(250) DEFAULT NULL,
  MODIFY `tma_he4` varchar(250) DEFAULT NULL,
  MODIFY `tma_hsp10` varchar(250) DEFAULT NULL,
  MODIFY `tma_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_pkm2` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_clid_hsq039972` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd74` varchar(250) DEFAULT NULL,
  MODIFY `tma_mif` varchar(250) DEFAULT NULL,
  MODIFY `mif_clid_hsq038688` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq040723` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq045359` varchar(250) DEFAULT NULL,
  MODIFY `tma_gpr54` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd44v6` varchar(250) DEFAULT NULL,
  MODIFY `tma_hacel_sorensen` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf_r_soslow` varchar(250) DEFAULT NULL,
  MODIFY `tma_gdf15` varchar(250) DEFAULT NULL,
  MODIFY `tma_ogp` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax8` varchar(250) DEFAULT NULL,
  MODIFY `tma_mammaglobin_b` varchar(250) DEFAULT NULL,
  MODIFY `tma_er` varchar(250) DEFAULT NULL,
  MODIFY `tma_epcam` varchar(250) DEFAULT NULL,
  MODIFY `tma_beta_catenin_nuclear` varchar(250) DEFAULT NULL,
  MODIFY `tma_mesothelin` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc5` varchar(250) DEFAULT NULL,
  MODIFY `tma_pten` varchar(250) DEFAULT NULL,
  MODIFY `tma_skp2` varchar(250) DEFAULT NULL,
  MODIFY `tma_her2` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2` varchar(250) DEFAULT NULL,
  MODIFY `tma_nherf1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezrin` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pr` varchar(250) DEFAULT NULL,
  MODIFY `tma_podocalyxin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hdac1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ca125` varchar(250) DEFAULT NULL,
  MODIFY `tma_k_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_p21` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd200` varchar(250) DEFAULT NULL,
  MODIFY `tma_mmp7` varchar(250) DEFAULT NULL,
  MODIFY `itgb7_clid_hsq031618` varchar(250) DEFAULT NULL,
  MODIFY `ccl28_clid_hsq013417` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq006530` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq004393` varchar(250) DEFAULT NULL,
  MODIFY `fkbp7_clid_hsq037241` varchar(250) DEFAULT NULL,
  MODIFY `wdr72_clid_hsq009730` varchar(250) DEFAULT NULL,
  MODIFY `tma_dal1` varchar(250) DEFAULT NULL,
  MODIFY `tma_drosha` varchar(250) DEFAULT NULL,
  MODIFY `tma_tgfb1` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd20` varchar(250) DEFAULT NULL,
  MODIFY `tma_tia1` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_irs` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_irs` varchar(250) DEFAULT NULL,
  MODIFY `kp_ir_pmol_l` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_expression_data` varchar(250) DEFAULT NULL,
  MODIFY `tma_secretory_component_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100a1` varchar(250) DEFAULT NULL,
  MODIFY `tma_dicer` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_tff3` varchar(250) DEFAULT NULL,
  MODIFY `tma_ps6rp` varchar(250) DEFAULT NULL,
  MODIFY `tma_dkk1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd8` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxl2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf1b_restain` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2_restain_08_05_09` varchar(250) DEFAULT NULL,
  MODIFY `tma_phosphoeif4e` varchar(250) DEFAULT NULL,
  MODIFY `tma_arid1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_opn` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezh2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_pstat` varchar(250) DEFAULT NULL,
  MODIFY `tma_lyn` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_score` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_vessels` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_percent_positive` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_numb` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_mean_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_max_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_nuclear_staining` varchar(250) DEFAULT NULL,
  MODIFY `brca1` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh` varchar(250) DEFAULT NULL,
  MODIFY `foxp3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `tia1_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd20_victoria` varchar(250) DEFAULT NULL,
  MODIFY `10_007_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_ephb4` varchar(250) DEFAULT NULL,
  MODIFY `tma_survivin` varchar(250) DEFAULT NULL,
  MODIFY `mdm2` varchar(250) DEFAULT NULL,
  MODIFY `ndrg1` varchar(250) DEFAULT NULL,
  MODIFY `serbp1` varchar(250) DEFAULT NULL,
  MODIFY `anxa4` varchar(250) DEFAULT NULL,
  MODIFY `p10` varchar(250) DEFAULT NULL,
  MODIFY `p53` varchar(250) DEFAULT NULL,
  MODIFY `cycline` varchar(250) DEFAULT NULL,
  MODIFY `p21` varchar(250) DEFAULT NULL,
  MODIFY `p27` varchar(250) DEFAULT NULL,
  MODIFY `p16` varchar(250) DEFAULT NULL,
  MODIFY `pakt` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_nkap` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_int` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_per` varchar(250) DEFAULT NULL,
  MODIFY `05_008_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_parp1` varchar(250) DEFAULT NULL,
  MODIFY `tma_notch1` varchar(250) DEFAULT NULL,
  MODIFY `tma_folr1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cxcr4` varchar(250) DEFAULT NULL;


ALTER TABLE `ovcare_ed_lab_experimental_results_revs`
  MODIFY `brca1_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca1_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca2_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca1_hypermethylation` varchar(250) DEFAULT NULL,
  MODIFY `brca1_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca2_rna` varchar(250) DEFAULT NULL,
  MODIFY `powerplex` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_wt1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p21` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p53` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cyclin_d1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_brca1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p27` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_eef1a2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cycline` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ecad` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_e2f1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p63` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p16` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_egfr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_er` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_her2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_117` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_n` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_m` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128820745` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128822436` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pten` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_id4_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pakt` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ar` varchar(250) DEFAULT NULL,
  MODIFY `08_001_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_blocks` varchar(250) DEFAULT NULL,
  MODIFY `tma_ret` varchar(250) DEFAULT NULL,
  MODIFY `tma_fascin` varchar(250) DEFAULT NULL,
  MODIFY `tma_wt1` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53` varchar(250) DEFAULT NULL,
  MODIFY `tma_p16` varchar(250) DEFAULT NULL,
  MODIFY `tma_imp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_trka` varchar(250) DEFAULT NULL,
  MODIFY `tma_trkb` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_bin` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_hebo_mrna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_hace1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_hace1` varchar(250) DEFAULT NULL,
  MODIFY `tma_egfr` varchar(250) DEFAULT NULL,
  MODIFY `tma_birc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_cyclind1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75861572` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75921347` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_znf217_position51632374` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_mean` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_1` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_2` varchar(250) DEFAULT NULL,
  MODIFY `tma_cmyc` varchar(250) DEFAULT NULL,
  MODIFY `tma_vegfr2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pdgfr_beta` varchar(250) DEFAULT NULL,
  MODIFY `tma_mras` varchar(250) DEFAULT NULL,
  MODIFY `tma_nasp` varchar(250) DEFAULT NULL,
  MODIFY `tma_rb` varchar(250) DEFAULT NULL,
  MODIFY `tma_vimentin` varchar(250) DEFAULT NULL,
  MODIFY `tma_ckit` varchar(250) DEFAULT NULL,
  MODIFY `tma_kiss1` varchar(250) DEFAULT NULL,
  MODIFY `tma_e_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_alpha` varchar(250) DEFAULT NULL,
  MODIFY `tma_pthlh` varchar(250) DEFAULT NULL,
  MODIFY `tma_ki67` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100` varchar(250) DEFAULT NULL,
  MODIFY `tma_agr2_43` varchar(250) DEFAULT NULL,
  MODIFY `spry2_clid_hsq035516` varchar(250) DEFAULT NULL,
  MODIFY `spry4_clid_hsq027862` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043924` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq011236` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043441` varchar(250) DEFAULT NULL,
  MODIFY `ereg_clid_hsq025201` varchar(250) DEFAULT NULL,
  MODIFY `erbb3_clid_hsq001349` varchar(250) DEFAULT NULL,
  MODIFY `areg_clid_hsq045253` varchar(250) DEFAULT NULL,
  MODIFY `errfi1_clid_hsq001603` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq038313` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq010863` varchar(250) DEFAULT NULL,
  MODIFY `btc_clid_hsq035992` varchar(250) DEFAULT NULL,
  MODIFY `tma_apoj` varchar(250) DEFAULT NULL,
  MODIFY `tma_capg164` varchar(250) DEFAULT NULL,
  MODIFY `tma_he4` varchar(250) DEFAULT NULL,
  MODIFY `tma_hsp10` varchar(250) DEFAULT NULL,
  MODIFY `tma_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_pkm2` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_clid_hsq039972` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd74` varchar(250) DEFAULT NULL,
  MODIFY `tma_mif` varchar(250) DEFAULT NULL,
  MODIFY `mif_clid_hsq038688` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq040723` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq045359` varchar(250) DEFAULT NULL,
  MODIFY `tma_gpr54` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd44v6` varchar(250) DEFAULT NULL,
  MODIFY `tma_hacel_sorensen` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf_r_soslow` varchar(250) DEFAULT NULL,
  MODIFY `tma_gdf15` varchar(250) DEFAULT NULL,
  MODIFY `tma_ogp` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax8` varchar(250) DEFAULT NULL,
  MODIFY `tma_mammaglobin_b` varchar(250) DEFAULT NULL,
  MODIFY `tma_er` varchar(250) DEFAULT NULL,
  MODIFY `tma_epcam` varchar(250) DEFAULT NULL,
  MODIFY `tma_beta_catenin_nuclear` varchar(250) DEFAULT NULL,
  MODIFY `tma_mesothelin` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc5` varchar(250) DEFAULT NULL,
  MODIFY `tma_pten` varchar(250) DEFAULT NULL,
  MODIFY `tma_skp2` varchar(250) DEFAULT NULL,
  MODIFY `tma_her2` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2` varchar(250) DEFAULT NULL,
  MODIFY `tma_nherf1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezrin` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pr` varchar(250) DEFAULT NULL,
  MODIFY `tma_podocalyxin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hdac1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ca125` varchar(250) DEFAULT NULL,
  MODIFY `tma_k_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_p21` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd200` varchar(250) DEFAULT NULL,
  MODIFY `tma_mmp7` varchar(250) DEFAULT NULL,
  MODIFY `itgb7_clid_hsq031618` varchar(250) DEFAULT NULL,
  MODIFY `ccl28_clid_hsq013417` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq006530` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq004393` varchar(250) DEFAULT NULL,
  MODIFY `fkbp7_clid_hsq037241` varchar(250) DEFAULT NULL,
  MODIFY `wdr72_clid_hsq009730` varchar(250) DEFAULT NULL,
  MODIFY `tma_dal1` varchar(250) DEFAULT NULL,
  MODIFY `tma_drosha` varchar(250) DEFAULT NULL,
  MODIFY `tma_tgfb1` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd20` varchar(250) DEFAULT NULL,
  MODIFY `tma_tia1` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_irs` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_irs` varchar(250) DEFAULT NULL,
  MODIFY `kp_ir_pmol_l` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_expression_data` varchar(250) DEFAULT NULL,
  MODIFY `tma_secretory_component_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100a1` varchar(250) DEFAULT NULL,
  MODIFY `tma_dicer` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_tff3` varchar(250) DEFAULT NULL,
  MODIFY `tma_ps6rp` varchar(250) DEFAULT NULL,
  MODIFY `tma_dkk1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd8` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxl2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf1b_restain` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2_restain_08_05_09` varchar(250) DEFAULT NULL,
  MODIFY `tma_phosphoeif4e` varchar(250) DEFAULT NULL,
  MODIFY `tma_arid1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_opn` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezh2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_pstat` varchar(250) DEFAULT NULL,
  MODIFY `tma_lyn` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_score` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_vessels` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_percent_positive` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_numb` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_mean_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_max_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_nuclear_staining` varchar(250) DEFAULT NULL,
  MODIFY `brca1` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh` varchar(250) DEFAULT NULL,
  MODIFY `foxp3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `tia1_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd20_victoria` varchar(250) DEFAULT NULL,
  MODIFY `10_007_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_ephb4` varchar(250) DEFAULT NULL,
  MODIFY `tma_survivin` varchar(250) DEFAULT NULL,
  MODIFY `mdm2` varchar(250) DEFAULT NULL,
  MODIFY `ndrg1` varchar(250) DEFAULT NULL,
  MODIFY `serbp1` varchar(250) DEFAULT NULL,
  MODIFY `anxa4` varchar(250) DEFAULT NULL,
  MODIFY `p10` varchar(250) DEFAULT NULL,
  MODIFY `p53` varchar(250) DEFAULT NULL,
  MODIFY `cycline` varchar(250) DEFAULT NULL,
  MODIFY `p21` varchar(250) DEFAULT NULL,
  MODIFY `p27` varchar(250) DEFAULT NULL,
  MODIFY `p16` varchar(250) DEFAULT NULL,
  MODIFY `pakt` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_nkap` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_int` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_per` varchar(250) DEFAULT NULL,
  MODIFY `05_008_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_parp1` varchar(250) DEFAULT NULL,
  MODIFY `tma_notch1` varchar(250) DEFAULT NULL,
  MODIFY `tma_folr1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cxcr4` varchar(250) DEFAULT NULL;

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'ovcare tissue sources');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('other', 'Other', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('other', 'Other', '', 1, @cont_id, @id, NOW());








UPDATE structure_fields SET  `language_label`='',  `language_tag`='-' WHERE model='DiagnosisDetail' AND tablename='ovcare_dxd_ovaries' AND field='substage' AND `type`='select';

DELETE FROM structure_formats WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_spr_tissue_gross_images') 
AND (structure_field_id = (SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='Inventorymanagement' AND `model`='SpecimenReviewDetail' AND `tablename`='ovcare_spr_tissue_gross_images' AND `field`='file_name' AND `language_label`='file name' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0')
OR structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_input' AND `language_label`='image' AND `language_tag`='' AND `type`='file' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0')
OR  structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_link' AND `language_label`='image' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0'));

DELETE FROM structure_fields WHERE `public_identifier`='' AND `plugin`='Inventorymanagement' AND `model`='SpecimenReviewDetail' AND `tablename`='ovcare_spr_tissue_gross_images' AND `field`='file_name' AND `language_label`='file name' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0';
DELETE FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_input' AND `language_label`='image' AND `language_tag`='' AND `type`='file' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0';
DELETE FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_link' AND `language_label`='image' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0';

ALTER TABLE ovcare_spr_tissue_gross_images
  DROP COLUMN file_name,
  DROP COLUMN file_type;
ALTER TABLE ovcare_spr_tissue_gross_images_revs
  DROP COLUMN file_name,
  DROP COLUMN file_type;

UPDATE structure_formats SET `flag_override_label`='1', `language_label`='file name' WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_spr_tissue_gross_images') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `tablename`='specimen_review_masters' AND `field`='review_code' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `flag_override_label` = 1, `language_label` = 'who code (morphology)', `language_heading` = ''
WHERE structure_id = (SELECT id FROM structures WHERE alias = 'dx_primary') AND structure_field_id = (SELECT id FROM structure_fields WHERE model = 'DiagnosisMaster' AND field = 'morphology');
INSERT IGNORE INTO i18n (id,en) VALUES ('who code (morphology)', 'WHO Code (Morphology)');

UPDATE structure_formats SET `flag_add`='1', `flag_edit`='1', `flag_search`='1', `flag_index`='1', `flag_detail`='1', `flag_summary`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_primary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='icd10_code' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_add`='1', `flag_edit`='1', `flag_search`='1', `flag_index`='1', `flag_detail`='1', `flag_summary`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_primary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='topography' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO `diagnosis_controls` (`id`, `category`, `controls_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`, `flag_compare_with_cap`) VALUES
(null, 'primary', 'other', 1, 'diagnosismasters,dx_primary', 'dxd_primaries', 0, 'primary|other', 0);

UPDATE structure_formats SET `flag_add`='0', `flag_edit`='0', `flag_detail`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_secondary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='dx_method' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='dx_method') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_add`='0', `flag_edit`='0', `flag_detail`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_secondary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='information_source' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='information_source') AND `flag_confidential`='0');

INSERT INTO `diagnosis_controls` (`id`, `category`, `controls_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`, `flag_compare_with_cap`) VALUES
(null, 'secondary', 'ovcare', 1, 'diagnosismasters,dx_secondary,ovcare_dx_ovaries', 'ovcare_dxd_ovaries', 0, 'secondary|ovcare', 0);
INSERT INTO `diagnosis_controls` (`id`, `category`, `controls_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`, `flag_compare_with_cap`) VALUES
(null, 'secondary', 'other', 1, 'diagnosismasters,dx_secondary', 'dxd_secondaries', 0, 'secondary|other', 0);
UPDATE diagnosis_controls SET flag_active = 0 WHERE category = 'secondary' AND controls_type = 'undetailed';

INSERT INTO `structure_validations` (`id`, `structure_field_id`, `rule`, `on_action`, `language_message`) VALUES
(null, (SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `field`='review_code'), 'isUnique', '', '');

INSERT INTO i18n (id,en) VALUES ('you are not allowed to add a secondary ovcare to a primary ovcare', "You are not allowed to add an 'OvCaRe' secondary  to an 'OvCaRe' primary!");

UPDATE structure_formats SET `flag_override_label` = 1, `language_label` = 'who code (morphology)', `language_heading` = ''
WHERE structure_id = (SELECT id FROM structures WHERE alias = 'dx_secondary') AND structure_field_id = (SELECT id FROM structure_fields WHERE model = 'DiagnosisMaster' AND field = 'morphology');

UPDATE structure_formats SET `flag_override_help`='0', `language_help`='', `flag_search`='0', `flag_index`='0', `flag_detail`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_primary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='survival_time_months' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='ovcare_dx_ovaries'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='survival_time_months' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0'), '1', '11', '', '0', '', '0', '', '1', 'ovcare_help_survival', '0', '', '0', '', '0', '', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0');

UPDATE datamart_browsing_controls SET flag_active_1_to_2 = 0, flag_active_2_to_1 = 0 WHERE id1 IN (SELECT id FROM datamart_structures WHERE model IN ('FamilyHistory','ParticipantMessage')) OR id2 IN (SELECT id FROM datamart_structures WHERE model IN ('FamilyHistory','ParticipantMessage'));

UPDATE structure_formats SET `flag_search`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='specimen_review_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `tablename`='specimen_review_masters' AND `field`='review_status' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='specimen_review_status') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_search`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='specimen_review_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `tablename`='specimen_review_masters' AND `field`='pathologist' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `flag_index`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='clinicalcollectionlinks') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='icd10_code' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_index`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='clinicalcollectionlinks') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='topography' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'ovcare collection types');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('surgical', 'Surgical', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('surgical', 'Surgical', '', 1, @cont_id, @id, NOW());

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'ovcare tissue sources');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('uterus', 'Uterus', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('uterus', 'Uterus', '', 1, @cont_id, @id, NOW());	
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('fallopian tube', 'Fallopian Tube', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('fallopian tube', 'Fallopian Tube', '', 1, @cont_id, @id, NOW());
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('pelvic mass', 'Pelvic Mass', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('pelvic mass', 'Pelvic Mass', '', 1, @cont_id, @id, NOW());

INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("bilateral", "bilateral");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="tissue_laterality"),  (SELECT id FROM structure_permissible_values WHERE value="bilateral" AND language_alias="bilateral"), "0", "1");

ALTER TABLE sd_spe_tissues
	ADD COLUMN ovcare_tissue_source_precision varchar(250) DEFAULT NULL AFTER tissue_source;
ALTER TABLE sd_spe_tissues_revs
	ADD COLUMN ovcare_tissue_source_precision varchar(250) DEFAULT NULL AFTER tissue_source;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Inventorymanagement', 'SampleDetail', 'sd_spe_tissues', 'ovcare_tissue_source_precision', 'input',  NULL , '0', 'size=30', '', '', '', 'tissue source precision');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='sd_spe_tissues'), (SELECT id FROM structure_fields WHERE `model`='SampleDetail' AND `tablename`='sd_spe_tissues' AND `field`='ovcare_tissue_source_precision' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=30' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='tissue source precision'), '1', '442', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '1', '0');

INSERT INTO i18n (id,en) VALUES ('tissue source precision', 'Precision');








-- TODO


SELECT '
VOA#757: The date of recurrence = 1900-01-05. Please confirm!
Start date accuracy to set for chemo of voa 1082.
Clean up should be done on specimen type because endometrium is written in many ways...
' as MSG;

SELECT '
DATABASE VALIDATION REQUIRED!




vial and block linked to specimen.... don't create if 2 specimens. Just add to comment.
' as TODO_DEV;

SELECT '
DATABASE VALIDATION REQUIRED!

Validate unexported fields from excel.
' as TODO_END;




SELECT 'Parafin blocks are linked to specimen 1 or 2? same question for vial frozen' as Questions_For_OvCaRe 
UNION 
SELECT 'Specimen type list: What about tissue source values coming from specimen type' as Questions_For_OvCaRe
UNION 
SELECT 'Clean up should be done on specimen type because endometrium is written in many ways...' as Questions_For_OvCaRe





  
