SELECT '****************' as msg
UNION
SELECT ' TODO' as msg
UNION
SELECT '
-- Define with ovcare the way we want to track results generated by other labs using ovcare bank samples
-- Define with ovcare the TMA data to track
-- Add gross image
-- What about barcode and label' as msg
-- TCGA ?
UNION ALL
SELECT '****************' as msg;

UPDATE structure_formats SET `flag_edit_readonly`='0' 
WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') 
AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `field`='aliquot_label');
UPDATE structure_formats SET `flag_override_label`='1', language_label = 'ovcare aliquot barcode'
WHERE structure_field_id IN (SELECT id FROM structure_fields WHERE `model` IN ('AliquotMaster','ViewAliquot') AND `field`='barcode' and language_label = 'barcode')
AND flag_override_label = '0';
UPDATE structure_formats SET language_label = 'used ovcare aliquot barcode' WHERE language_label = 'used aliquot barcode';

INSERT INTO i18n (id,en) VALUES ('ovcare aliquot barcode', 'Aliq. Syst. Code'),('used ovcare aliquot barcode','Used Aliq. Syst. Code');

UPDATE structure_formats SET `flag_add`='0' ,`flag_addgrid`='0' 
WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') 
AND structure_field_id IN (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `field`='barcode');

INSERT INTO `structure_validations` (`id`, `structure_field_id`, `rule`, `on_action`, `language_message`) VALUES
(null, (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `field`='aliquot_label'), 'notEmpty', '', '');




DROP VIEW view_aliquot_uses;
CREATE VIEW view_aliquot_uses AS 

SELECT 
CONCAT(source.id, 1) AS id,
aliq.id AS aliquot_master_id,
'sample derivative creation' AS use_definition, 
samp.sample_code AS use_code,
'' AS use_details,
source.used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
der.creation_datetime AS use_datetime,
der.creation_datetime_accuracy AS use_datetime_accuracy,
der.creation_by AS used_by,
source.created,
CONCAT('|inventorymanagement|aliquot_masters|listAllSourceAliquots|',samp.collection_id ,'|',samp.id) AS detail_url,
samp2.id AS sample_master_id,
samp2.collection_id AS collection_id
FROM source_aliquots AS source
INNER JOIN sample_masters AS samp ON samp.id = source.sample_master_id  AND samp.deleted != 1
INNER JOIN derivative_details AS der ON samp.id = der.sample_master_id  AND der.deleted != 1
INNER JOIN aliquot_masters AS aliq ON aliq.id = source.aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN sample_masters AS samp2 ON samp2.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE source.deleted != 1

UNION ALL

SELECT 
CONCAT(realiq.id, 2) AS id,
aliq.id AS aliquot_master_id,
'realiquoted to' AS use_definition, 
CONCAT(child.aliquot_label, ' (', child.barcode, ')') AS use_code,
'' AS use_details,
realiq.parent_used_volume AS used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
realiq.realiquoting_datetime AS use_datetime,
realiq.realiquoting_datetime_accuracy AS use_datetime_accuracy,
realiq.realiquoted_by AS used_by,
realiq.created,
CONCAT('|inventorymanagement|aliquot_masters|listAllRealiquotedParents|',child.collection_id,'|',child.sample_master_id,'|',child.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM realiquotings AS realiq
INNER JOIN aliquot_masters AS aliq ON aliq.id = realiq.parent_aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN aliquot_masters AS child ON child.id = realiq.child_aliquot_master_id AND child.deleted != 1
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE realiq.deleted != 1

UNION ALL

SELECT 
CONCAT(qc.id, 3) AS id,
aliq.id AS aliquot_master_id,
'quality control' AS use_definition, 
qc.qc_code AS use_code,
'' AS use_details,
qc.used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
qc.date AS use_datetime,
qc.date_accuracy AS use_datetime_accuracy,
qc.run_by AS used_by,
qc.created,
CONCAT('|inventorymanagement|quality_ctrls|detail|',aliq.collection_id,'|',aliq.sample_master_id,'|',qc.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM quality_ctrls AS qc
INNER JOIN aliquot_masters AS aliq ON aliq.id = qc.aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE qc.deleted != 1

UNION ALL

SELECT 
CONCAT(item.id, 4) AS id,
aliq.id AS aliquot_master_id,
'aliquot shipment' AS use_definition, 
sh.shipment_code AS use_code,
'' AS use_details,
'' AS used_volume,
'' AS aliquot_volume_unit,
sh.datetime_shipped AS use_datetime,
sh.datetime_shipped_accuracy AS use_datetime_accuracy,
sh.shipped_by AS used_by,
sh.created,
CONCAT('|order|shipments|detail|',sh.order_id,'|',sh.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM order_items AS item
INNER JOIN aliquot_masters AS aliq ON aliq.id = item.aliquot_master_id AND aliq.deleted != 1
INNER JOIN shipments AS sh ON sh.id = item.shipment_id AND sh.deleted != 1
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE item.deleted != 1

UNION ALL

SELECT 
CONCAT(alr.id, 5) AS id,
aliq.id AS aliquot_master_id,
'specimen review' AS use_definition, 
spr.review_code AS use_code,
'' AS use_details,
'' AS used_volume,
'' AS aliquot_volume_unit,
spr.review_date AS use_datetime,
spr.review_date_accuracy AS use_datetime_accuracy,
'' AS used_by,
alr.created,
CONCAT('|inventorymanagement|specimen_reviews|detail|',aliq.collection_id,'|',aliq.sample_master_id,'|',spr.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM aliquot_review_masters AS alr
INNER JOIN aliquot_masters AS aliq ON aliq.id = alr.aliquot_master_id AND aliq.deleted != 1
INNER JOIN specimen_review_masters AS spr ON spr.id = alr.specimen_review_master_id AND spr.deleted != 1
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE alr.deleted != 1

UNION ALL

SELECT 
CONCAT(aluse.id, 6) AS id,
aliq.id AS aliquot_master_id,
'internal use' AS use_definition, 
aluse.use_code,
aluse.use_details,
aluse.used_volume,
aliqc.volume_unit AS aliquot_volume_unit,
aluse.use_datetime,
aluse.use_datetime_accuracy,
aluse.used_by,
aluse.created,
CONCAT('|inventorymanagement|aliquot_masters|detailAliquotInternalUse|',aliq.id,'|',aluse.id) AS detail_url,
samp.id AS sample_master_id,
samp.collection_id AS collection_id
FROM aliquot_internal_uses AS aluse
INNER JOIN aliquot_masters AS aliq ON aliq.id = aluse.aliquot_master_id AND aliq.deleted != 1
INNER JOIN aliquot_controls AS aliqc ON aliq.aliquot_control_id = aliqc.id
INNER JOIN sample_masters AS samp ON samp.id = aliq.sample_master_id  AND samp.deleted != 1
WHERE aluse.deleted != 1;

UPDATE structure_fields SET type = 'integer_positive', setting = 'size=10' WHERE field = 'participant_identifier';

ALTER TABLE participants MODIFY participant_identifier INT(7) NOT NULL;
ALTER TABLE participants_revs MODIFY participant_identifier INt(7) NOT NULL;

INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES
("alive/intercurrent disease", "alive/intercurrent disease"), 
("alive/unknown", "alive/unknown");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) 
VALUES
((SELECT id FROM structure_value_domains WHERE domain_name="ovcare_vital_status"),  
(SELECT id FROM structure_permissible_values WHERE value="alive/intercurrent disease" AND language_alias="alive/intercurrent disease"), "2", "1"),
((SELECT id FROM structure_value_domains WHERE domain_name="ovcare_vital_status"),  
(SELECT id FROM structure_permissible_values WHERE value="alive/unknown" AND language_alias="alive/unknown"), "0", "1");
INSERT INTO i18n (id,en) VALUES
("alive/intercurrent disease", "Alive/Intercurrent Disease"), 
("alive/unknown", "Alive/Unknown");

INSERT INTO i18n (id,en) VALUES ("A","A"),("B","B"),("C","C");

ALTER TABLE ovcare_ed_lab_experimental_results 
	ADD COLUMN 05_008_brca1_mccluggage_int varchar(50) DEFAULT NULL AFTER tma_nkap,
	ADD COLUMN 05_008_brca1_mccluggage_per varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_int,
	ADD COLUMN 05_008_core_id varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_per,
	ADD COLUMN tma_parp1 varchar(50) DEFAULT NULL AFTER 05_008_core_id,
	ADD COLUMN tma_notch1 varchar(50) DEFAULT NULL AFTER tma_parp1,
	ADD COLUMN tma_folr1 varchar(50) DEFAULT NULL AFTER tma_notch1,
	ADD COLUMN tma_cxcr4 varchar(50) DEFAULT NULL AFTER tma_folr1;

ALTER TABLE ovcare_ed_lab_experimental_results_revs
	ADD COLUMN 05_008_brca1_mccluggage_int varchar(50) DEFAULT NULL AFTER tma_nkap,
	ADD COLUMN 05_008_brca1_mccluggage_per varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_int,
	ADD COLUMN 05_008_core_id varchar(50) DEFAULT NULL AFTER 05_008_brca1_mccluggage_per,
	ADD COLUMN tma_parp1 varchar(50) DEFAULT NULL AFTER 05_008_core_id,
	ADD COLUMN tma_notch1 varchar(50) DEFAULT NULL AFTER tma_parp1,
	ADD COLUMN tma_folr1 varchar(50) DEFAULT NULL AFTER tma_notch1,
	ADD COLUMN tma_cxcr4 varchar(50) DEFAULT NULL AFTER tma_folr1;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', '05_008_brca1_mccluggage_int', 'input',  NULL , '0', 'size=10', '', '', '05_008 brca1 mccluggage int', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', '05_008_brca1_mccluggage_per', 'input',  NULL , '0', 'size=10', '', '', '05_008_brca1 mccluggage per', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', '05_008_core_id', 'input',  NULL , '0', 'size=10', '', '', '05_008 core id', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_parp1', 'input',  NULL , '0', 'size=10', '', '', 'tma parp1', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_notch1', 'input',  NULL , '0', 'size=10', '', '', 'tma notch1', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_folr1', 'input',  NULL , '0', 'size=10', '', '', 'tma folr1', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_results', 'tma_cxcr4', 'input',  NULL , '0', 'size=10', '', '', 'tma cxcr4', '');

SET @structure_id = (SELECT id FROM structures WHERE alias = 'ovcare_ed_lab_experimental_results');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='05_008_brca1_mccluggage_int'), '4', '408', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='05_008_brca1_mccluggage_per'), '4', '409', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='05_008_core_id'), '4', '410', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_parp1'), '4', '411', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_notch1'), '4', '412', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_folr1'), '4', '413', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_results' AND `field`='tma_cxcr4'), '4', '414', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'); 

INSERT INTO i18n (id,en) VALUES
('05_008 brca1 mccluggage int','05_008 BRCA1 McCluggage Intensity'),
('05_008_brca1 mccluggage per','05_008 BRCA1 McCluggage Percent'),
('05_008 core id','05_008 Core ID'),
('tma parp1','TMA_PARP1'),
('tma notch1','TMA_Notch1'),
('tma folr1','TMA_FOLR1'),
('tma cxcr4','TMA_CXCR4');

UPDATE structure_fields SET setting = 'size=25' WHERE tablename = 'ovcare_ed_lab_experimental_results';

ALTER TABLE `ovcare_ed_lab_experimental_results`
  MODIFY `brca1_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca1_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca2_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca1_hypermethylation` varchar(250) DEFAULT NULL,
  MODIFY `brca1_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca2_rna` varchar(250) DEFAULT NULL,
  MODIFY `powerplex` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_wt1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p21` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p53` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cyclin_d1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_brca1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p27` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_eef1a2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cycline` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ecad` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_e2f1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p63` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p16` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_egfr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_er` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_her2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_117` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_n` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_m` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128820745` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128822436` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pten` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_id4_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pakt` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ar` varchar(250) DEFAULT NULL,
  MODIFY `08_001_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_blocks` varchar(250) DEFAULT NULL,
  MODIFY `tma_ret` varchar(250) DEFAULT NULL,
  MODIFY `tma_fascin` varchar(250) DEFAULT NULL,
  MODIFY `tma_wt1` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53` varchar(250) DEFAULT NULL,
  MODIFY `tma_p16` varchar(250) DEFAULT NULL,
  MODIFY `tma_imp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_trka` varchar(250) DEFAULT NULL,
  MODIFY `tma_trkb` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_bin` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_hebo_mrna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_hace1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_hace1` varchar(250) DEFAULT NULL,
  MODIFY `tma_egfr` varchar(250) DEFAULT NULL,
  MODIFY `tma_birc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_cyclind1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75861572` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75921347` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_znf217_position51632374` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_mean` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_1` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_2` varchar(250) DEFAULT NULL,
  MODIFY `tma_cmyc` varchar(250) DEFAULT NULL,
  MODIFY `tma_vegfr2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pdgfr_beta` varchar(250) DEFAULT NULL,
  MODIFY `tma_mras` varchar(250) DEFAULT NULL,
  MODIFY `tma_nasp` varchar(250) DEFAULT NULL,
  MODIFY `tma_rb` varchar(250) DEFAULT NULL,
  MODIFY `tma_vimentin` varchar(250) DEFAULT NULL,
  MODIFY `tma_ckit` varchar(250) DEFAULT NULL,
  MODIFY `tma_kiss1` varchar(250) DEFAULT NULL,
  MODIFY `tma_e_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_alpha` varchar(250) DEFAULT NULL,
  MODIFY `tma_pthlh` varchar(250) DEFAULT NULL,
  MODIFY `tma_ki67` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100` varchar(250) DEFAULT NULL,
  MODIFY `tma_agr2_43` varchar(250) DEFAULT NULL,
  MODIFY `spry2_clid_hsq035516` varchar(250) DEFAULT NULL,
  MODIFY `spry4_clid_hsq027862` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043924` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq011236` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043441` varchar(250) DEFAULT NULL,
  MODIFY `ereg_clid_hsq025201` varchar(250) DEFAULT NULL,
  MODIFY `erbb3_clid_hsq001349` varchar(250) DEFAULT NULL,
  MODIFY `areg_clid_hsq045253` varchar(250) DEFAULT NULL,
  MODIFY `errfi1_clid_hsq001603` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq038313` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq010863` varchar(250) DEFAULT NULL,
  MODIFY `btc_clid_hsq035992` varchar(250) DEFAULT NULL,
  MODIFY `tma_apoj` varchar(250) DEFAULT NULL,
  MODIFY `tma_capg164` varchar(250) DEFAULT NULL,
  MODIFY `tma_he4` varchar(250) DEFAULT NULL,
  MODIFY `tma_hsp10` varchar(250) DEFAULT NULL,
  MODIFY `tma_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_pkm2` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_clid_hsq039972` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd74` varchar(250) DEFAULT NULL,
  MODIFY `tma_mif` varchar(250) DEFAULT NULL,
  MODIFY `mif_clid_hsq038688` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq040723` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq045359` varchar(250) DEFAULT NULL,
  MODIFY `tma_gpr54` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd44v6` varchar(250) DEFAULT NULL,
  MODIFY `tma_hacel_sorensen` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf_r_soslow` varchar(250) DEFAULT NULL,
  MODIFY `tma_gdf15` varchar(250) DEFAULT NULL,
  MODIFY `tma_ogp` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax8` varchar(250) DEFAULT NULL,
  MODIFY `tma_mammaglobin_b` varchar(250) DEFAULT NULL,
  MODIFY `tma_er` varchar(250) DEFAULT NULL,
  MODIFY `tma_epcam` varchar(250) DEFAULT NULL,
  MODIFY `tma_beta_catenin_nuclear` varchar(250) DEFAULT NULL,
  MODIFY `tma_mesothelin` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc5` varchar(250) DEFAULT NULL,
  MODIFY `tma_pten` varchar(250) DEFAULT NULL,
  MODIFY `tma_skp2` varchar(250) DEFAULT NULL,
  MODIFY `tma_her2` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2` varchar(250) DEFAULT NULL,
  MODIFY `tma_nherf1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezrin` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pr` varchar(250) DEFAULT NULL,
  MODIFY `tma_podocalyxin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hdac1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ca125` varchar(250) DEFAULT NULL,
  MODIFY `tma_k_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_p21` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd200` varchar(250) DEFAULT NULL,
  MODIFY `tma_mmp7` varchar(250) DEFAULT NULL,
  MODIFY `itgb7_clid_hsq031618` varchar(250) DEFAULT NULL,
  MODIFY `ccl28_clid_hsq013417` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq006530` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq004393` varchar(250) DEFAULT NULL,
  MODIFY `fkbp7_clid_hsq037241` varchar(250) DEFAULT NULL,
  MODIFY `wdr72_clid_hsq009730` varchar(250) DEFAULT NULL,
  MODIFY `tma_dal1` varchar(250) DEFAULT NULL,
  MODIFY `tma_drosha` varchar(250) DEFAULT NULL,
  MODIFY `tma_tgfb1` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd20` varchar(250) DEFAULT NULL,
  MODIFY `tma_tia1` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_irs` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_irs` varchar(250) DEFAULT NULL,
  MODIFY `kp_ir_pmol_l` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_expression_data` varchar(250) DEFAULT NULL,
  MODIFY `tma_secretory_component_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100a1` varchar(250) DEFAULT NULL,
  MODIFY `tma_dicer` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_tff3` varchar(250) DEFAULT NULL,
  MODIFY `tma_ps6rp` varchar(250) DEFAULT NULL,
  MODIFY `tma_dkk1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd8` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxl2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf1b_restain` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2_restain_08_05_09` varchar(250) DEFAULT NULL,
  MODIFY `tma_phosphoeif4e` varchar(250) DEFAULT NULL,
  MODIFY `tma_arid1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_opn` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezh2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_pstat` varchar(250) DEFAULT NULL,
  MODIFY `tma_lyn` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_score` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_vessels` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_percent_positive` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_numb` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_mean_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_max_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_nuclear_staining` varchar(250) DEFAULT NULL,
  MODIFY `brca1` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh` varchar(250) DEFAULT NULL,
  MODIFY `foxp3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `tia1_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd20_victoria` varchar(250) DEFAULT NULL,
  MODIFY `10_007_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_ephb4` varchar(250) DEFAULT NULL,
  MODIFY `tma_survivin` varchar(250) DEFAULT NULL,
  MODIFY `mdm2` varchar(250) DEFAULT NULL,
  MODIFY `ndrg1` varchar(250) DEFAULT NULL,
  MODIFY `serbp1` varchar(250) DEFAULT NULL,
  MODIFY `anxa4` varchar(250) DEFAULT NULL,
  MODIFY `p10` varchar(250) DEFAULT NULL,
  MODIFY `p53` varchar(250) DEFAULT NULL,
  MODIFY `cycline` varchar(250) DEFAULT NULL,
  MODIFY `p21` varchar(250) DEFAULT NULL,
  MODIFY `p27` varchar(250) DEFAULT NULL,
  MODIFY `p16` varchar(250) DEFAULT NULL,
  MODIFY `pakt` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_nkap` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_int` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_per` varchar(250) DEFAULT NULL,
  MODIFY `05_008_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_parp1` varchar(250) DEFAULT NULL,
  MODIFY `tma_notch1` varchar(250) DEFAULT NULL,
  MODIFY `tma_folr1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cxcr4` varchar(250) DEFAULT NULL;


ALTER TABLE `ovcare_ed_lab_experimental_results_revs`
  MODIFY `brca1_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca1_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_germline_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_somatic_nuc_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca2_vus` varchar(250) DEFAULT NULL,
  MODIFY `brca1_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca2_loh` varchar(250) DEFAULT NULL,
  MODIFY `brca1_hypermethylation` varchar(250) DEFAULT NULL,
  MODIFY `brca1_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca2_rna` varchar(250) DEFAULT NULL,
  MODIFY `powerplex` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_wt1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p21` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p53` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cyclin_d1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_brca1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p27` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_eef1a2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cycline` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ecad` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_e2f1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p63` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_p16` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_egfr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pr` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_er` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_her2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_cd_117` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_n` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_b_catenin_m` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128820745` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_position128822436` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_row2` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_c_myc_hebo_mrna_sd` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pik3ca` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_pten` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_id4_rna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_pakt` varchar(250) DEFAULT NULL,
  MODIFY `brca1_somatic_amino_acid` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_ar` varchar(250) DEFAULT NULL,
  MODIFY `08_001_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_blocks` varchar(250) DEFAULT NULL,
  MODIFY `tma_ret` varchar(250) DEFAULT NULL,
  MODIFY `tma_fascin` varchar(250) DEFAULT NULL,
  MODIFY `tma_wt1` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53` varchar(250) DEFAULT NULL,
  MODIFY `tma_p16` varchar(250) DEFAULT NULL,
  MODIFY `tma_imp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_trka` varchar(250) DEFAULT NULL,
  MODIFY `tma_trkb` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_bin` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_imp3_hebo_mrna` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_hace1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_qrt_pcr_hace1` varchar(250) DEFAULT NULL,
  MODIFY `tma_egfr` varchar(250) DEFAULT NULL,
  MODIFY `tma_birc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_cyclind1` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75861572` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_position75921347` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_znf217_position51632374` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_mean` varchar(250) DEFAULT NULL,
  MODIFY `brca_array_mip_emsy_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_mean` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_sd` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_1` varchar(250) DEFAULT NULL,
  MODIFY `mda_cmyc_replicate_2` varchar(250) DEFAULT NULL,
  MODIFY `tma_cmyc` varchar(250) DEFAULT NULL,
  MODIFY `tma_vegfr2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pdgfr_beta` varchar(250) DEFAULT NULL,
  MODIFY `tma_mras` varchar(250) DEFAULT NULL,
  MODIFY `tma_nasp` varchar(250) DEFAULT NULL,
  MODIFY `tma_rb` varchar(250) DEFAULT NULL,
  MODIFY `tma_vimentin` varchar(250) DEFAULT NULL,
  MODIFY `tma_ckit` varchar(250) DEFAULT NULL,
  MODIFY `tma_kiss1` varchar(250) DEFAULT NULL,
  MODIFY `tma_e_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_alpha` varchar(250) DEFAULT NULL,
  MODIFY `tma_pthlh` varchar(250) DEFAULT NULL,
  MODIFY `tma_ki67` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100` varchar(250) DEFAULT NULL,
  MODIFY `tma_agr2_43` varchar(250) DEFAULT NULL,
  MODIFY `spry2_clid_hsq035516` varchar(250) DEFAULT NULL,
  MODIFY `spry4_clid_hsq027862` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043924` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq011236` varchar(250) DEFAULT NULL,
  MODIFY `spry1_clid_hsq043441` varchar(250) DEFAULT NULL,
  MODIFY `ereg_clid_hsq025201` varchar(250) DEFAULT NULL,
  MODIFY `erbb3_clid_hsq001349` varchar(250) DEFAULT NULL,
  MODIFY `areg_clid_hsq045253` varchar(250) DEFAULT NULL,
  MODIFY `errfi1_clid_hsq001603` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq038313` varchar(250) DEFAULT NULL,
  MODIFY `egfr_clid_hsq010863` varchar(250) DEFAULT NULL,
  MODIFY `btc_clid_hsq035992` varchar(250) DEFAULT NULL,
  MODIFY `tma_apoj` varchar(250) DEFAULT NULL,
  MODIFY `tma_capg164` varchar(250) DEFAULT NULL,
  MODIFY `tma_he4` varchar(250) DEFAULT NULL,
  MODIFY `tma_hsp10` varchar(250) DEFAULT NULL,
  MODIFY `tma_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_pkm2` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_clid_hsq039972` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd74` varchar(250) DEFAULT NULL,
  MODIFY `tma_mif` varchar(250) DEFAULT NULL,
  MODIFY `mif_clid_hsq038688` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq040723` varchar(250) DEFAULT NULL,
  MODIFY `cd74_clid_hsq045359` varchar(250) DEFAULT NULL,
  MODIFY `tma_gpr54` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd44v6` varchar(250) DEFAULT NULL,
  MODIFY `tma_hacel_sorensen` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf_r_soslow` varchar(250) DEFAULT NULL,
  MODIFY `tma_gdf15` varchar(250) DEFAULT NULL,
  MODIFY `tma_ogp` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax8` varchar(250) DEFAULT NULL,
  MODIFY `tma_mammaglobin_b` varchar(250) DEFAULT NULL,
  MODIFY `tma_er` varchar(250) DEFAULT NULL,
  MODIFY `tma_epcam` varchar(250) DEFAULT NULL,
  MODIFY `tma_beta_catenin_nuclear` varchar(250) DEFAULT NULL,
  MODIFY `tma_mesothelin` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc6` varchar(250) DEFAULT NULL,
  MODIFY `tma_muc5` varchar(250) DEFAULT NULL,
  MODIFY `tma_pten` varchar(250) DEFAULT NULL,
  MODIFY `tma_skp2` varchar(250) DEFAULT NULL,
  MODIFY `tma_her2` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2` varchar(250) DEFAULT NULL,
  MODIFY `tma_nherf1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezrin` varchar(250) DEFAULT NULL,
  MODIFY `tma_pax2` varchar(250) DEFAULT NULL,
  MODIFY `tma_pr` varchar(250) DEFAULT NULL,
  MODIFY `tma_podocalyxin` varchar(250) DEFAULT NULL,
  MODIFY `tma_hdac1` varchar(250) DEFAULT NULL,
  MODIFY `tma_ca125` varchar(250) DEFAULT NULL,
  MODIFY `tma_k_cadherin` varchar(250) DEFAULT NULL,
  MODIFY `tma_p21` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd200` varchar(250) DEFAULT NULL,
  MODIFY `tma_mmp7` varchar(250) DEFAULT NULL,
  MODIFY `itgb7_clid_hsq031618` varchar(250) DEFAULT NULL,
  MODIFY `ccl28_clid_hsq013417` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq006530` varchar(250) DEFAULT NULL,
  MODIFY `tro_clid_hsq004393` varchar(250) DEFAULT NULL,
  MODIFY `fkbp7_clid_hsq037241` varchar(250) DEFAULT NULL,
  MODIFY `wdr72_clid_hsq009730` varchar(250) DEFAULT NULL,
  MODIFY `tma_dal1` varchar(250) DEFAULT NULL,
  MODIFY `tma_drosha` varchar(250) DEFAULT NULL,
  MODIFY `tma_tgfb1` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxp3` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd20` varchar(250) DEFAULT NULL,
  MODIFY `tma_tia1` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1_irs` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_ccl28_irs` varchar(250) DEFAULT NULL,
  MODIFY `kp_ir_pmol_l` varchar(250) DEFAULT NULL,
  MODIFY `pde5a_expression_data` varchar(250) DEFAULT NULL,
  MODIFY `tma_secretory_component_pigr` varchar(250) DEFAULT NULL,
  MODIFY `tma_s100a1` varchar(250) DEFAULT NULL,
  MODIFY `tma_dicer` varchar(250) DEFAULT NULL,
  MODIFY `tma_p53_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_tff3` varchar(250) DEFAULT NULL,
  MODIFY `tma_ps6rp` varchar(250) DEFAULT NULL,
  MODIFY `tma_dkk1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cd8` varchar(250) DEFAULT NULL,
  MODIFY `tma_foxl2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hnf1b_restain` varchar(250) DEFAULT NULL,
  MODIFY `tma_mdm2_restain_08_05_09` varchar(250) DEFAULT NULL,
  MODIFY `tma_phosphoeif4e` varchar(250) DEFAULT NULL,
  MODIFY `tma_arid1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_opn` varchar(250) DEFAULT NULL,
  MODIFY `tma_ezh2` varchar(250) DEFAULT NULL,
  MODIFY `tma_hif1a` varchar(250) DEFAULT NULL,
  MODIFY `tma_pstat` varchar(250) DEFAULT NULL,
  MODIFY `tma_lyn` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_score` varchar(250) DEFAULT NULL,
  MODIFY `tma_laminin_rp_vessels` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_percent_positive` varchar(250) DEFAULT NULL,
  MODIFY `tma_pcad_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_numb` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_mean_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_max_percent` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_intensity` varchar(250) DEFAULT NULL,
  MODIFY `tma_mps1_nuclear_staining` varchar(250) DEFAULT NULL,
  MODIFY `brca1` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh` varchar(250) DEFAULT NULL,
  MODIFY `foxp3_victoria` varchar(250) DEFAULT NULL,
  MODIFY `tia1_victoria` varchar(250) DEFAULT NULL,
  MODIFY `cd20_victoria` varchar(250) DEFAULT NULL,
  MODIFY `10_007_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_ephb4` varchar(250) DEFAULT NULL,
  MODIFY `tma_survivin` varchar(250) DEFAULT NULL,
  MODIFY `mdm2` varchar(250) DEFAULT NULL,
  MODIFY `ndrg1` varchar(250) DEFAULT NULL,
  MODIFY `serbp1` varchar(250) DEFAULT NULL,
  MODIFY `anxa4` varchar(250) DEFAULT NULL,
  MODIFY `p10` varchar(250) DEFAULT NULL,
  MODIFY `p53` varchar(250) DEFAULT NULL,
  MODIFY `cycline` varchar(250) DEFAULT NULL,
  MODIFY `p21` varchar(250) DEFAULT NULL,
  MODIFY `p27` varchar(250) DEFAULT NULL,
  MODIFY `p16` varchar(250) DEFAULT NULL,
  MODIFY `pakt` varchar(250) DEFAULT NULL,
  MODIFY `cd8_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd8_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_victoria_rescore` varchar(250) DEFAULT NULL,
  MODIFY `cd3_vgh_rescore` varchar(250) DEFAULT NULL,
  MODIFY `tma_nkap` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_int` varchar(250) DEFAULT NULL,
  MODIFY `05_008_brca1_mccluggage_per` varchar(250) DEFAULT NULL,
  MODIFY `05_008_core_id` varchar(250) DEFAULT NULL,
  MODIFY `tma_parp1` varchar(250) DEFAULT NULL,
  MODIFY `tma_notch1` varchar(250) DEFAULT NULL,
  MODIFY `tma_folr1` varchar(250) DEFAULT NULL,
  MODIFY `tma_cxcr4` varchar(250) DEFAULT NULL;

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'ovcare tissue sources');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('other', 'Other', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('other', 'Other', '', 1, @cont_id, @id, NOW());








UPDATE structure_fields SET  `language_label`='',  `language_tag`='-' WHERE model='DiagnosisDetail' AND tablename='ovcare_dxd_ovaries' AND field='substage' AND `type`='select';

DELETE FROM structure_formats WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_spr_tissue_gross_images') 
AND (structure_field_id = (SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='Inventorymanagement' AND `model`='SpecimenReviewDetail' AND `tablename`='ovcare_spr_tissue_gross_images' AND `field`='file_name' AND `language_label`='file name' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0')
OR structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_input' AND `language_label`='image' AND `language_tag`='' AND `type`='file' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0')
OR  structure_field_id=(SELECT id FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_link' AND `language_label`='image' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0'));

DELETE FROM structure_fields WHERE `public_identifier`='' AND `plugin`='Inventorymanagement' AND `model`='SpecimenReviewDetail' AND `tablename`='ovcare_spr_tissue_gross_images' AND `field`='file_name' AND `language_label`='file name' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0';
DELETE FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_input' AND `language_label`='image' AND `language_tag`='' AND `type`='file' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0';
DELETE FROM structure_fields WHERE `public_identifier`='' AND `plugin`='' AND `model`='OvcareFunctionManagement' AND `tablename`='' AND `field`='file_link' AND `language_label`='image' AND `language_tag`='' AND `type`='input' AND `setting`='' AND `default`='' AND `structure_value_domain` IS NULL  AND `language_help`='' AND `validation_control`='open' AND `value_domain_control`='open' AND `field_control`='open' AND `flag_confidential`='0';

ALTER TABLE ovcare_spr_tissue_gross_images
  DROP COLUMN file_name,
  DROP COLUMN file_type;
ALTER TABLE ovcare_spr_tissue_gross_images_revs
  DROP COLUMN file_name,
  DROP COLUMN file_type;

UPDATE structure_formats SET `flag_override_label`='1', `language_label`='file name' WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_spr_tissue_gross_images') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `tablename`='specimen_review_masters' AND `field`='review_code' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `flag_override_label` = 1, `language_label` = 'who code (morphology)', `language_heading` = ''
WHERE structure_id = (SELECT id FROM structures WHERE alias = 'dx_primary') AND structure_field_id = (SELECT id FROM structure_fields WHERE model = 'DiagnosisMaster' AND field = 'morphology');
INSERT IGNORE INTO i18n (id,en) VALUES ('who code (morphology)', 'WHO Code (Morphology)');

UPDATE structure_formats SET `flag_add`='1', `flag_edit`='1', `flag_search`='1', `flag_index`='1', `flag_detail`='1', `flag_summary`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_primary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='icd10_code' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_add`='1', `flag_edit`='1', `flag_search`='1', `flag_index`='1', `flag_detail`='1', `flag_summary`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_primary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='topography' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO `diagnosis_controls` (`id`, `category`, `controls_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`, `flag_compare_with_cap`) VALUES
(null, 'primary', 'other', 1, 'diagnosismasters,dx_primary', 'dxd_primaries', 0, 'primary|other', 0);

UPDATE structure_formats SET `flag_add`='0', `flag_edit`='0', `flag_detail`='0', `flag_summary`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_secondary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='dx_method' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='dx_method') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_add`='0', `flag_edit`='0', `flag_detail`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_secondary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='information_source' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='information_source') AND `flag_confidential`='0');

INSERT INTO `diagnosis_controls` (`id`, `category`, `controls_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`, `flag_compare_with_cap`) VALUES
(null, 'secondary', 'ovcare', 1, 'diagnosismasters,dx_secondary,ovcare_dx_ovaries', 'ovcare_dxd_ovaries', 0, 'secondary|ovcare', 0);
INSERT INTO `diagnosis_controls` (`id`, `category`, `controls_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`, `flag_compare_with_cap`) VALUES
(null, 'secondary', 'other', 1, 'diagnosismasters,dx_secondary', 'dxd_secondaries', 0, 'secondary|other', 0);
UPDATE diagnosis_controls SET flag_active = 0 WHERE category = 'secondary' AND controls_type = 'undetailed';

INSERT INTO `structure_validations` (`id`, `structure_field_id`, `rule`, `on_action`, `language_message`) VALUES
(null, (SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `field`='review_code'), 'isUnique', '', '');

INSERT INTO i18n (id,en) VALUES ('you are not allowed to add a secondary ovcare to a primary ovcare', "You are not allowed to add an 'OvCaRe' secondary  to an 'OvCaRe' primary!");

UPDATE structure_formats SET `flag_override_label` = 1, `language_label` = 'who code (morphology)', `language_heading` = ''
WHERE structure_id = (SELECT id FROM structures WHERE alias = 'dx_secondary') AND structure_field_id = (SELECT id FROM structure_fields WHERE model = 'DiagnosisMaster' AND field = 'morphology');

UPDATE structure_formats SET `flag_override_help`='0', `language_help`='', `flag_search`='0', `flag_index`='0', `flag_detail`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_primary') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='survival_time_months' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='ovcare_dx_ovaries'), (SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='survival_time_months' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0'), '1', '11', '', '0', '', '0', '', '1', 'ovcare_help_survival', '0', '', '0', '', '0', '', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0');

UPDATE datamart_browsing_controls SET flag_active_1_to_2 = 0, flag_active_2_to_1 = 0 WHERE id1 IN (SELECT id FROM datamart_structures WHERE model IN ('FamilyHistory','ParticipantMessage')) OR id2 IN (SELECT id FROM datamart_structures WHERE model IN ('FamilyHistory','ParticipantMessage'));

UPDATE structure_formats SET `flag_search`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='specimen_review_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `tablename`='specimen_review_masters' AND `field`='review_status' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='specimen_review_status') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_search`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='specimen_review_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='SpecimenReviewMaster' AND `tablename`='specimen_review_masters' AND `field`='pathologist' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE structure_formats SET `flag_index`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='clinicalcollectionlinks') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='icd10_code' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_index`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='clinicalcollectionlinks') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='DiagnosisMaster' AND `tablename`='diagnosis_masters' AND `field`='topography' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'ovcare collection types');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('surgical', 'Surgical', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('surgical', 'Surgical', '', 1, @cont_id, @id, NOW());

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'ovcare tissue sources');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('uterus', 'Uterus', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('uterus', 'Uterus', '', 1, @cont_id, @id, NOW());	
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('fallopian tube', 'Fallopian Tube', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('fallopian tube', 'Fallopian Tube', '', 1, @cont_id, @id, NOW());
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `fr`, `use_as_input`, `control_id`) VALUES 
('pelvic mass', 'Pelvic Mass', '', 1, @cont_id);
SET @id = LAST_INSERT_ID();
INSERT INTO `structure_permissible_values_customs_revs` (`value`, `en`, `fr`, `use_as_input`, `control_id`,`id`, `version_created`) 
VALUES 
('pelvic mass', 'Pelvic Mass', '', 1, @cont_id, @id, NOW());

INSERT IGNORE INTO structure_permissible_values (`value`, `language_alias`) VALUES("bilateral", "bilateral");
INSERT INTO structure_value_domains_permissible_values (`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`) VALUES((SELECT id FROM structure_value_domains WHERE domain_name="tissue_laterality"),  (SELECT id FROM structure_permissible_values WHERE value="bilateral" AND language_alias="bilateral"), "0", "1");

ALTER TABLE sd_spe_tissues
	ADD COLUMN ovcare_tissue_source_precision varchar(250) DEFAULT NULL AFTER tissue_source;
ALTER TABLE sd_spe_tissues_revs
	ADD COLUMN ovcare_tissue_source_precision varchar(250) DEFAULT NULL AFTER tissue_source;

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Inventorymanagement', 'SampleDetail', 'sd_spe_tissues', 'ovcare_tissue_source_precision', 'input',  NULL , '0', 'size=30', '', '', '', 'tissue source precision');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='sd_spe_tissues'), (SELECT id FROM structure_fields WHERE `model`='SampleDetail' AND `tablename`='sd_spe_tissues' AND `field`='ovcare_tissue_source_precision' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=30' AND `default`='' AND `language_help`='' AND `language_label`='' AND `language_tag`='tissue source precision'), '1', '442', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '1', '1', '0');

INSERT INTO i18n (id,en) VALUES ('tissue source precision', 'Precision');

INSERT INTO `aliquot_controls` (`id`, `sample_control_id`, `aliquot_type`, `aliquot_type_precision`, `form_alias`, `detail_tablename`, `volume_unit`, `flag_active`, `comment`, `display_order`, `databrowser_label`) VALUES
(null, (SELECT id FROM sample_controls WHERE sample_type = 'ascite cell' ), 'block', NULL, 'aliquot_masters,ad_der_ascite_cell_blocks', 'ad_blocks', NULL, 1, 'Ascite cell block', 0, 'block');

INSERT INTO structures(`alias`) VALUES ('ad_der_ascite_cell_blocks');

INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='ad_der_ascite_cell_blocks'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='creat_to_stor_spent_time_msg' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=30' AND `default`='' AND `language_help`='' AND `language_label`='creation to storage spent time' AND `language_tag`=''), '1', '60', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
((SELECT id FROM structures WHERE alias='ad_der_ascite_cell_blocks'), (SELECT id FROM structure_fields WHERE `model`='Generated' AND `tablename`='' AND `field`='coll_to_stor_spent_time_msg' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='size=30' AND `default`='' AND `language_help`='' AND `language_label`='collection to storage spent time' AND `language_tag`=''), '1', '59', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0');

-- EXPERIMENTAL RESULTS REBUILD ----------------------------------------------------------------------------------------

INSERT INTO `event_controls` (`disease_site`, `event_group`, `event_type`, `flag_active`, `form_alias`, `detail_tablename`, `display_order`, `databrowser_label`) VALUES
('ovcare', 'lab', 'experimental tests', 1, 'eventmasters,ovcare_ed_lab_experimental_tests', 'ovcare_ed_lab_experimental_tests', 0, 'lab|ovcare|experimental tests');
INSERT INTO i18n (id,en) VALUEs ('experimental tests', 'Experimental Tests');

CREATE TABLE IF NOT EXISTS `ovcare_ed_lab_experimental_tests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  
  `test` varchar(250) DEFAULT NULL,
  `result` varchar(250) DEFAULT NULL,
  
  `event_master_id` int(11) DEFAULT NULL,
  `deleted` tinyint(3) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `event_master_id` (`event_master_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `ovcare_ed_lab_experimental_tests_revs` (
  `id` int(11) NOT NULL,
  
  `test` varchar(250) DEFAULT NULL,
  `result` varchar(250) DEFAULT NULL,
  
  `event_master_id` int(11) DEFAULT NULL,
  `version_id` int(11) NOT NULL AUTO_INCREMENT,
  `version_created` datetime NOT NULL,
  PRIMARY KEY (`version_id`),
  KEY `event_master_id` (`event_master_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

ALTER TABLE `ovcare_ed_lab_experimental_tests`
  ADD CONSTRAINT `ovcare_ed_lab_experimental_tests_ibfk_1` FOREIGN KEY (`event_master_id`) REFERENCES `event_masters` (`id`);

INSERT INTO structures(`alias`) VALUES ('ovcare_ed_lab_experimental_tests');

INSERT INTO `structure_permissible_values_custom_controls` VALUES (null,'experimental tests',1,250);
INSERT INTO `structure_value_domains` VALUES (null,'ovcare_experimental_tests','open','','StructurePermissibleValuesCustom::getCustomDropdown(\'experimental tests\')');

INSERT INTO structure_fields(`plugin`, `model`, `tablename`, `field`, `type`, `structure_value_domain`, `flag_confidential`, `setting`, `default`, `language_help`, `language_label`, `language_tag`) VALUES
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_tests', 'test', 'select',  (SELECT id FROM structure_value_domains WHERE domain_name = 'ovcare_experimental_tests') , '0', '', '', '', 'experimental test', ''), 
('Clinicalannotation', 'EventDetail', 'ovcare_ed_lab_experimental_tests', 'result', 'input',  NULL , '0', 'size=50', '', '', '', '='); 
SET @structure_id = (SELECT id FROM structures WHERE alias = 'ovcare_ed_lab_experimental_tests');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='test'), '2', '51', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'), 
(@structure_id, (SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='result'), '2', '52', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0'); 

INSERT INTO `structure_validations` (`id`, `structure_field_id`, `rule`, `on_action`, `language_message`) VALUES
(null, (SELECT id FROM structure_fields WHERE `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='test'), 'notEmpty', '', '');

SET @cont_id = (SELECT id FROM structure_permissible_values_custom_controls WHERE name = 'experimental tests');
INSERT INTO `structure_permissible_values_customs` (`value`, `en`, `use_as_input`, `control_id`) 
VALUES
('05_008 brca1 mccluggage intensity', '05_008 BRCA1 McCluggage Intensity', '1', @cont_id),
('05_008 brca1 mccluggage percent', '05_008 BRCA1 McCluggage Percent', '1', @cont_id),
('05_008 core id', '05_008 Core ID', '1', @cont_id),
('08_001 core id', '08_001 Core ID', '1', @cont_id),
('10_007 core id', '10_007 Core ID', '1', @cont_id),
('anxa4', 'ANXA4', '1', @cont_id),
('areg clid: hsq045253', 'AREG CLID: hSQ045253', '1', @cont_id),
('brca array ar', 'BRCA Array AR', '1', @cont_id),
('brca array b_catenin_m', 'BRCA Array B_Catenin_M', '1', @cont_id),
('brca array b_catenin_n', 'BRCA Array B_Catenin_N', '1', @cont_id),
('brca array brca1', 'BRCA Array BRCA1', '1', @cont_id),
('brca array cd 117', 'BRCA Array CD 117', '1', @cont_id),
('brca array cd 3', 'BRCA Array CD 3', '1', @cont_id),
('brca array cyclin d1', 'BRCA Array Cyclin D1', '1', @cont_id),
('brca array cycline', 'BRCA Array CyclinE', '1', @cont_id),
('brca array e2f1', 'BRCA Array E2F1', '1', @cont_id),
('brca array ecad', 'BRCA Array Ecad', '1', @cont_id),
('brca array eef1a2', 'BRCA Array EEF1a2', '1', @cont_id),
('brca array egfr', 'BRCA Array EGFR', '1', @cont_id),
('brca array er', 'BRCA Array ER', '1', @cont_id),
('brca array foxp3', 'BRCA Array FOXP3', '1', @cont_id),
('brca array her2', 'BRCA Array HER2', '1', @cont_id),
('brca array mip_c_myc hebo mrna mean', 'BRCA Array MIP_C_Myc HEBO mRNA Mean', '1', @cont_id),
('brca array mip_c_myc hebo mrna row1', 'BRCA Array MIP_C_Myc HEBO mRNA Row1', '1', @cont_id),
('brca array mip_c_myc hebo mrna row2', 'BRCA Array MIP_C_Myc HEBO mRNA Row2', '1', @cont_id),
('brca array mip_c_myc hebo mrna sd', 'BRCA Array MIP_C_Myc HEBO mRNA SD', '1', @cont_id),
('brca array mip_c_myc mean', 'BRCA Array MIP_C_Myc Mean', '1', @cont_id),
('brca array mip_c_myc position128820745', 'BRCA Array MIP_C_Myc Position128820745', '1', @cont_id),
('brca array mip_c_myc position128822436', 'BRCA Array MIP_C_Myc Position128822436', '1', @cont_id),
('brca array mip_c_myc sd', 'BRCA Array MIP_C_Myc SD', '1', @cont_id),
('brca array mip_emsy mean', 'BRCA Array MIP_EMSY Mean', '1', @cont_id),
('brca array mip_emsy position75861572', 'BRCA Array MIP_EMSY Position75861572', '1', @cont_id),
('brca array mip_emsy position75921347', 'BRCA Array MIP_EMSY Position75921347', '1', @cont_id),
('brca array mip_emsy sd', 'BRCA Array MIP_EMSY SD', '1', @cont_id),
('brca array mip_hace1', 'BRCA Array MIP_Hace1', '1', @cont_id),
('brca array mip_imp3', 'BRCA Array MIP_IMP3', '1', @cont_id),
('brca array mip_imp3 bin', 'BRCA Array MIP_IMP3 Bin', '1', @cont_id),
('brca array mip_imp3 hebo mrna', 'BRCA Array MIP_IMP3 HEBO mRNA', '1', @cont_id),
('brca array mip_pik3ca', 'BRCA Array MIP_PIK3CA', '1', @cont_id),
('brca array p16', 'BRCA Array p16', '1', @cont_id),
('brca array p21', 'BRCA Array p21', '1', @cont_id),
('brca array p27', 'BRCA Array p27', '1', @cont_id),
('brca array p53', 'BRCA Array p53', '1', @cont_id),
('brca array p63', 'BRCA Array p63', '1', @cont_id),
('brca array pakt', 'BRCA Array pAKT', '1', @cont_id),
('brca array pr', 'BRCA Array PR', '1', @cont_id),
('brca array qrt_pcr_hace1', 'BRCA Array qRT_PCR_Hace1', '1', @cont_id),
('brca array qrt_pcr_id4 rna', 'BRCA Array qRT_PCR_ID4 RNA', '1', @cont_id),
('brca array qrt_pcr_pik3ca', 'BRCA Array qRT_PCR_PIK3CA', '1', @cont_id),
('brca array qrt_pcr_pten', 'BRCA Array qRT_PCR_PTEN', '1', @cont_id),
('brca array wt1', 'BRCA Array WT1', '1', @cont_id),
('brca array znf217 position51632374', 'BRCA Array ZNF217 Position51632374', '1', @cont_id),
('brca1', 'BRCA1', '1', @cont_id),
('brca1 germline amino acid', 'BRCA1 Germline Amino Acid', '1', @cont_id),
('brca1 germline nuc acid', 'BRCA1 Germline Nuc Acid', '1', @cont_id),
('brca1 hypermethylation', 'BRCA1 Hypermethylation', '1', @cont_id),
('brca1 loh', 'BRCA1 LOH', '1', @cont_id),
('brca1 rna', 'BRCA1 RNA', '1', @cont_id),
('brca1 somatic amino acid', 'BRCA1 Somatic Amino Acid', '1', @cont_id),
('brca1 somatic nuc acid', 'BRCA1 Somatic Nuc Acid', '1', @cont_id),
('brca1 vus', 'BRCA1 VUS', '1', @cont_id),
('brca2 germline amino acid', 'BRCA2 Germline Amino Acid', '1', @cont_id),
('brca2 germline nuc acid', 'BRCA2 Germline Nuc Acid', '1', @cont_id),
('brca2 loh', 'BRCA2 LOH', '1', @cont_id),
('brca2 rna', 'BRCA2 RNA', '1', @cont_id),
('brca2 somatic nuc acid', 'BRCA2 Somatic Nuc Acid', '1', @cont_id),
('brca2 vus', 'BRCA2 VUS', '1', @cont_id),
('btc clid: hsq035992', 'BTC CLID: hSQ035992', '1', @cont_id),
('ccl28 clid: hsq013417', 'CCL28 CLID: hSQ013417', '1', @cont_id),
('cd20 victoria', 'CD20 Victoria', '1', @cont_id),
('cd3 vgh', 'CD3 VGH', '1', @cont_id),
('cd3 vgh rescore', 'CD3 VGH Rescore', '1', @cont_id),
('cd3 victoria', 'CD3 Victoria', '1', @cont_id),
('cd3 victoria rescore', 'CD3 Victoria Rescore', '1', @cont_id),
('cd74 clid: hsq040723', 'CD74 CLID: hSQ040723', '1', @cont_id),
('cd74 clid: hsq045359', 'CD74 CLID: hSQ045359', '1', @cont_id),
('cd8 vgh', 'CD8 VGH', '1', @cont_id),
('cd8 vgh rescore', 'CD8 VGH Rescore', '1', @cont_id),
('cd8 victoria', 'CD8 Victoria', '1', @cont_id),
('cd8 victoria rescore', 'CD8 Victoria Rescore', '1', @cont_id),
('cycline', 'CyclinE', '1', @cont_id),
('egfr clid: hsq010863', 'EGFR CLID: hSQ010863', '1', @cont_id),
('egfr clid: hsq038313', 'EGFR CLID: hSQ038313', '1', @cont_id),
('erbb3 clid: hsq001349', 'ERBB3 CLID: hSQ001349', '1', @cont_id),
('ereg clid: hsq025201', 'EREG CLID: hSQ025201', '1', @cont_id),
('errfi1 clid: hsq001603', 'ERRFI1 CLID: hSQ001603', '1', @cont_id),
('fkbp7 clid: hsq037241', 'FKBP7 CLID: hSQ037241', '1', @cont_id),
('foxp3 victoria', 'FoxP3 Victoria', '1', @cont_id),
('itgb7 clid: hsq031618', 'ITGB7 CLID: hSQ031618', '1', @cont_id),
('kp_ir pmol_l', 'KP_IR pmol_l', '1', @cont_id),
('mda cmyc mean', 'MDA CMyc Mean', '1', @cont_id),
('mda cmyc replicate 1', 'MDA CMyc Replicate 1', '1', @cont_id),
('mda cmyc replicate 2', 'MDA CMyc Replicate 2', '1', @cont_id),
('mda cmyc sd', 'MDA CMyc SD', '1', @cont_id),
('mdm2', 'MDM2', '1', @cont_id),
('mif clid: hsq038688', 'MIF CLID: hSQ038688', '1', @cont_id),
('ndrg1', 'NDRG1', '1', @cont_id),
('p10', 'p10', '1', @cont_id),
('p16', 'p16', '1', @cont_id),
('p21', 'p21', '1', @cont_id),
('p27', 'p27', '1', @cont_id),
('p53', 'p53', '1', @cont_id),
('pakt', 'pAKT', '1', @cont_id),
('pde5a clid: hsq039972', 'PDE5A CLID: hSQ039972', '1', @cont_id),
('pde5a expression data', 'PDE5a Expression Data', '1', @cont_id),
('powerplex', 'Powerplex', '1', @cont_id),
('serbp1', 'SERBP1', '1', @cont_id),
('spry1 clid: hsq011236', 'SPRY1 CLID: hSQ011236', '1', @cont_id),
('spry1 clid: hsq043441', 'SPRY1 CLID: hSQ043441', '1', @cont_id),
('spry1 clid: hsq043924', 'SPRY1 CLID: hSQ043924', '1', @cont_id),
('spry2 clid: hsq035516', 'SPRY2 CLID: hSQ035516', '1', @cont_id),
('spry4 clid: hsq027862', 'SPRY4 CLID: hSQ027862', '1', @cont_id),
('tia1 victoria', 'TIA1 Victoria', '1', @cont_id),
('tma_agr2_43', 'TMA_AGR2_43', '1', @cont_id),
('tma_apoj', 'TMA_APOJ', '1', @cont_id),
('tma_arid1a', 'TMA_ARID1A', '1', @cont_id),
('tma_beta_catenin nuclear', 'TMA_Beta_Catenin Nuclear', '1', @cont_id),
('tma_birc6', 'TMA_BIRC6', '1', @cont_id),
('tma_ca125', 'TMA_CA125', '1', @cont_id),
('tma_capg164', 'TMA_CAPG164', '1', @cont_id),
('tma_ccl28 intensity', 'TMA_CCL28 Intensity', '1', @cont_id),
('tma_ccl28 irs', 'TMA_CCL28 IRS', '1', @cont_id),
('tma_ccl28 percent', 'TMA_CCL28 Percent', '1', @cont_id),
('tma_cd20', 'TMA_CD20', '1', @cont_id),
('tma_cd200', 'TMA_CD200', '1', @cont_id),
('tma_cd44v6', 'TMA_CD44v6', '1', @cont_id),
('tma_cd74', 'TMA_CD74', '1', @cont_id),
('tma_cd8', 'TMA_CD8', '1', @cont_id),
('tma_ckit', 'TMA_cKit', '1', @cont_id),
('tma_cmyc', 'TMA_CMyc', '1', @cont_id),
('tma_cxcr4', 'TMA_CXCR4', '1', @cont_id),
('tma_cyclind1', 'TMA_CyclinD1', '1', @cont_id),
('tma_dal1', 'TMA_Dal1', '1', @cont_id),
('tma_dicer', 'TMA_Dicer', '1', @cont_id),
('tma_dkk1', 'TMA_DKK1', '1', @cont_id),
('tma_drosha', 'TMA_Drosha', '1', @cont_id),
('tma_e_cadherin', 'TMA_E_Cadherin', '1', @cont_id),
('tma_egfr', 'TMA_EGFR', '1', @cont_id),
('tma_epcam', 'TMA_EpCam', '1', @cont_id),
('tma_ephb4', 'TMA_EPHB4', '1', @cont_id),
('tma_er', 'TMA_ER', '1', @cont_id),
('tma_ezh2', 'TMA_EZH2', '1', @cont_id),
('tma_ezrin', 'TMA_Ezrin', '1', @cont_id),
('tma_fascin', 'TMA_Fascin', '1', @cont_id),
('tma_folr1', 'TMA_FOLR1', '1', @cont_id),
('tma_foxl2', 'TMA_FOXL2', '1', @cont_id),
('tma_foxp3', 'TMA_FoxP3', '1', @cont_id),
('tma_gdf15', 'TMA_GDF15', '1', @cont_id),
('tma_gpr54', 'TMA_GPR54', '1', @cont_id),
('tma_hacel_sorensen', 'TMA_Hacel_Sorensen', '1', @cont_id),
('tma_hdac1', 'TMA_HDAC1', '1', @cont_id),
('tma_he4', 'TMA_HE4', '1', @cont_id),
('tma_her2', 'TMA_HER2', '1', @cont_id),
('tma_hif1 alpha', 'TMA_HIF1 Alpha', '1', @cont_id),
('tma_hif1 intensity', 'TMA_HIF1 Intensity', '1', @cont_id),
('tma_hif1 irs', 'TMA_HIF1 IRS', '1', @cont_id),
('tma_hif1 percent', 'TMA_HIF1 Percent', '1', @cont_id),
('tma_hif1a', 'TMA_HIF1A', '1', @cont_id),
('tma_hnf_r_soslow', 'TMA_HNF_R_Soslow', '1', @cont_id),
('tma_hnf1b restain', 'TMA_HNF1B Restain', '1', @cont_id),
('tma_hsp10', 'TMA_HSP10', '1', @cont_id),
('tma_imp3', 'TMA_IMP3', '1', @cont_id),
('tma_k_cadherin', 'TMA_K_Cadherin', '1', @cont_id),
('tma_ki67', 'TMA_Ki67', '1', @cont_id),
('tma_kiss1', 'TMA_KISS1', '1', @cont_id),
('tma_laminin rp score', 'TMA_Laminin RP Score', '1', @cont_id),
('tma_laminin rp vessels', 'TMA_Laminin RP Vessels', '1', @cont_id),
('tma_lyn', 'TMA_LYN', '1', @cont_id),
('tma_mammaglobin b', 'TMA_Mammaglobin B', '1', @cont_id),
('tma_mdm2', 'TMA_MDM2', '1', @cont_id),
('tma_mdm2 restain 08.05.09', 'TMA_MDM2 restain 08.05.09', '1', @cont_id),
('tma_mesothelin', 'TMA_Mesothelin', '1', @cont_id),
('tma_mif', 'TMA_MIF', '1', @cont_id),
('tma_mmp7', 'TMA_MMP7', '1', @cont_id),
('tma_mps1 intensity', 'TMA_MPS1 Intensity', '1', @cont_id),
('tma_mps1 max percent', 'TMA_MPS1 Max Percent', '1', @cont_id),
('tma_mps1 mean percent', 'TMA_MPS1 Mean Percent', '1', @cont_id),
('tma_mps1 nuclear staining', 'TMA_MPS1 Nuclear Staining', '1', @cont_id),
('tma_mras', 'TMA_MRAS', '1', @cont_id),
('tma_muc5', 'TMA_MUC5', '1', @cont_id),
('tma_muc6', 'TMA_MUC6', '1', @cont_id),
('tma_nasp', 'TMA_NASP', '1', @cont_id),
('tma_nherf1', 'TMA_NHERF1', '1', @cont_id),
('tma_nkap', 'TMA_NKAP', '1', @cont_id),
('tma_notch1', 'TMA_Notch1', '1', @cont_id),
('tma_numb', 'TMA_NUMB', '1', @cont_id),
('tma_ogp', 'TMA_OGP', '1', @cont_id),
('tma_opn', 'TMA_OPN', '1', @cont_id),
('tma_p16', 'TMA_p16', '1', @cont_id),
('tma_p21', 'TMA_p21', '1', @cont_id),
('tma_p53', 'TMA_p53', '1', @cont_id),
('tma_p53 rescore', 'TMA_p53 Rescore', '1', @cont_id),
('tma_parp1', 'TMA_PARP1', '1', @cont_id),
('tma_pax2', 'TMA_PAX2', '1', @cont_id),
('tma_pax8', 'TMA_PAX8', '1', @cont_id),
('tma_pcad intensity', 'TMA_pcad Intensity', '1', @cont_id),
('tma_pcad percent positive', 'TMA_pcad Percent Positive', '1', @cont_id),
('tma_pdgfr beta', 'TMA_PDGFR Beta', '1', @cont_id),
('tma_phosphoeif4e', 'TMA_PhosphoEIF4E', '1', @cont_id),
('tma_pigr', 'TMA_PIGR', '1', @cont_id),
('tma_pkm2', 'TMA_PKM2', '1', @cont_id),
('tma_podocalyxin', 'TMA_Podocalyxin', '1', @cont_id),
('tma_pr', 'TMA_PR', '1', @cont_id),
('tma_ps6rp', 'TMA_pS6rp', '1', @cont_id),
('tma_pstat', 'TMA_PSTAT', '1', @cont_id),
('tma_pten', 'TMA_PTEN', '1', @cont_id),
('tma_pthlh', 'TMA_PTHLH', '1', @cont_id),
('tma_rb', 'TMA_Rb', '1', @cont_id),
('tma_ret', 'TMA_Ret', '1', @cont_id),
('tma_s100', 'TMA_S100', '1', @cont_id),
('tma_s100a1', 'TMA_S100A1', '1', @cont_id),
('tma_secretory component_pigr', 'TMA_Secretory Component_PIGR', '1', @cont_id),
('tma_skp2', 'TMA_SKP2', '1', @cont_id),
('tma_survivin', 'TMA_Survivin', '1', @cont_id),
('tma_tff3', 'TMA_TFF3', '1', @cont_id),
('tma_tgfb1', 'TMA_TGFB1', '1', @cont_id),
('tma_tia1', 'TMA_TIA1', '1', @cont_id),
('tma_trka', 'TMA_TRKA', '1', @cont_id),
('tma_trkb', 'TMA_TRKB', '1', @cont_id),
('tma_vegfr2', 'TMA_VEGFR2', '1', @cont_id),
('tma_vimentin', 'TMA_Vimentin', '1', @cont_id),
('tma_wt1', 'TMA_WT1', '1', @cont_id);

INSERT IGNORE INTO i18n (id,en) 
VALUES 
('experimental test','Test'),
('in batch', 'In Batch'),
('experimental test result can not be empty', 'Experimental test result can not be empty!'),
('at least one test result has to be completed','At least one test result has to be completed!');

UPDATE structure_formats SET `flag_addgrid`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_ed_lab_experimental_tests') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='test' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='ovcare_experimental_tests') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_addgrid`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_ed_lab_experimental_tests') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='result' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`) VALUES 
((SELECT id FROM structures WHERE alias='ovcare_ed_lab_experimental_tests'), (SELECT id FROM structure_fields WHERE `model`='FunctionManagement' AND `tablename`='' AND `field`='CopyCtrl' AND `type`='checkbox' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='yes_no_checkbox')  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='copy control' AND `language_tag`=''), '2', '10000', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '0', '0', '0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '0', '0');

UPDATE structure_formats SET `flag_search`='1', `flag_index`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_ed_lab_experimental_tests') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='test' AND `structure_value_domain` =(SELECT id FROM structure_value_domains WHERE domain_name='ovcare_experimental_tests') AND `flag_confidential`='0');
UPDATE structure_formats SET `flag_search`='1', `flag_index`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='ovcare_ed_lab_experimental_tests') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='EventDetail' AND `tablename`='ovcare_ed_lab_experimental_tests' AND `field`='result' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

DROP TABLE ovcare_ed_lab_experimental_results;
DROP TABLE ovcare_ed_lab_experimental_results_revs;

DELETE FROM i18n WHERE id IN (SELECT sf.language_label FROM structure_fields AS sf WHERE sf.tablename = 'ovcare_ed_lab_experimental_results');

DELETE FROM structure_formats WHERE structure_id = (SELECT id FROM structures WHERE alias = 'ovcare_ed_lab_experimental_results');
DELETE FROM structures WHERE alias = 'ovcare_ed_lab_experimental_results';
DELETE FROM structure_fields WHERE tablename = 'ovcare_ed_lab_experimental_results';

DELETE FROM event_controls WHERE detail_tablename LIKE '%ovcare_ed_lab_experimental_results%';

UPDATE structure_fields SET  `language_label`='result',  `language_tag`='' WHERE model='EventDetail' AND tablename='ovcare_ed_lab_experimental_tests' AND field='result' AND `type`='input' AND structure_value_domain  IS NULL ;

-- EXPERIMENTAL RESULTS END








-- TODO

SELECT '
VOA#757: The date of recurrence = 1900-01-05. Please confirm!
VOA#1082: Start date accuracy to set for chemo.
' as MSG;

SELECT '
DATABASE VALIDATION REQUIRED!
Validate unexported fields from excel.
' as TODO_DEV;
