-- BCCH Customization Script
-- Version 0.7.0
-- ATiM Version: 2.6.7

-- Update bank name for version tracking during customization
REPLACE INTO `i18n` (`id`, `en`, `fr`)
	VALUES ('core_installname', "BCCH Biobank - BCCH v0.7.0", '');

-- BB-192

-- Updating the Neurology Diagnosis Form

ALTER TABLE `dxd_bcch_neurology`
	ADD COLUMN `cond_seizure_and_epilepsy` VARCHAR(50) DEFAULT NULL AFTER `diagnosis_master_id`,
	ADD COLUMN `s_sym_epil_unclassifiable` VARCHAR(50) DEFAULT NULL AFTER `cond_seizure_and_epilepsy`,
	ADD COLUMN `s_sym_epil_other_defn_location_etiology` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_unclassifiable`,
	ADD COLUMN `s_sym_epil_benign_chilhood_centrotemporal_spikes` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_other_defn_location_etiology`,
	ADD COLUMN `s_sym_epil_general_febrile_seizures` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_benign_chilhood_centrotemporal_spikes`, 
	ADD COLUMN `s_sym_other_spec_convulsions` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_general_febrile_seizures`, 
	ADD COLUMN `s_sym_febrile_seizures` VARCHAR(50) DEFAULT NULL AFTER `s_sym_other_spec_convulsions`, 
	ADD COLUMN `s_sym_juvenile_myoclonic_epil` VARCHAR(50) DEFAULT NULL AFTER `s_sym_febrile_seizures`,
	ADD COLUMN `s_sym_west_syndrome` VARCHAR(50) DEFAULT NULL AFTER `s_sym_juvenile_myoclonic_epil`,
	ADD COLUMN `s_sym_epil_genetic_idiopathic` VARCHAR(50) DEFAULT NULL AFTER `s_sym_west_syndrome`,
	ADD COLUMN `s_sym_symptomatic_focal_epil` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_genetic_idiopathic`,  
	ADD COLUMN `s_sym_childhood_absence_epil` VARCHAR(50) DEFAULT NULL AFTER `s_sym_symptomatic_focal_epil`,
	ADD COLUMN `s_sym_neonatal_seizures` VARCHAR(50) DEFAULT NULL AFTER `s_sym_childhood_absence_epil`,

	ADD COLUMN `cond_headaches` VARCHAR(50) DEFAULT NULL AFTER `s_sym_neonatal_seizures`,
	ADD COLUMN `h_sym_chronic_daily_headache` VARCHAR(50) DEFAULT NULL AFTER `cond_headaches`,  
	ADD COLUMN `h_sym_migraine_without_aura` VARCHAR(50) DEFAULT NULL AFTER `h_sym_chronic_daily_headache`, 
	ADD COLUMN `h_sym_pseudotumour_cerebri` VARCHAR(50) DEFAULT NULL AFTER `h_sym_migraine_without_aura`, 
	ADD COLUMN `h_sym_migraine_with_aura` VARCHAR(50) DEFAULT NULL AFTER `h_sym_pseudotumour_cerebri`, 
	ADD COLUMN `h_sym_headache_unspecified` VARCHAR(50) DEFAULT NULL AFTER `h_sym_migraine_with_aura`, 
	ADD COLUMN `h_sym_migraine_variants` VARCHAR(50) DEFAULT NULL AFTER `h_sym_headache_unspecified`, 
	ADD COLUMN `h_sym_tension_headache` VARCHAR(50) DEFAULT NULL AFTER `h_sym_migraine_variants`, 

	ADD COLUMN `cond_infectious_inflammatory_immune_mediated` VARCHAR(50) DEFAULT NULL AFTER `h_sym_tension_headache`,
	ADD COLUMN `i_viral_encephalitis` VARCHAR(50) DEFAULT NULL AFTER `cond_infectious_inflammatory_immune_mediated`,
	ADD COLUMN `i_autoimmune_encephalitis` VARCHAR(50) DEFAULT NULL AFTER `i_viral_encephalitis`,
	ADD COLUMN `i_cns_vasculitis` VARCHAR(50) DEFAULT NULL AFTER `i_autoimmune_encephalitis`,
	ADD COLUMN `i_transverse_myelitis` VARCHAR(50) DEFAULT NULL AFTER `i_cns_vasculitis`,
	ADD COLUMN `i_bacterial_meningitis` VARCHAR(50) DEFAULT NULL AFTER `i_transverse_myelitis`,
	ADD COLUMN `i_acute_disseminated_encephalomyelitis` VARCHAR(50) DEFAULT NULL AFTER `i_bacterial_meningitis`,
	ADD COLUMN `i_multiple_sclerosis` VARCHAR(50) DEFAULT NULL AFTER `i_acute_disseminated_encephalomyelitis`,

	ADD COLUMN `cond_neonatal_and_neuromuscular` VARCHAR(50) DEFAULT NULL AFTER `i_multiple_sclerosis`,
	ADD COLUMN `n_spinal_muscular_atrophy` VARCHAR(50) DEFAULT NULL AFTER `cond_neonatal_and_neuromuscular`,
	ADD COLUMN `n_hypoxic_ischemic_encephalopathy` VARCHAR(50) DEFAULT NULL AFTER `n_spinal_muscular_atrophy`,
	ADD COLUMN `n_inborn_error_of_metabolism` VARCHAR(50) DEFAULT NULL AFTER `n_hypoxic_ischemic_encephalopathy`,
	ADD COLUMN `n_myotonic_dystrophy` VARCHAR(50) DEFAULT NULL AFTER `n_inborn_error_of_metabolism`,
	ADD COLUMN `n_stroke` VARCHAR(50) DEFAULT NULL AFTER `n_myotonic_dystrophy`,
	ADD COLUMN `n_disorders_of_neuromuscular_junction` VARCHAR(50) DEFAULT NULL AFTER `n_stroke`,
	ADD COLUMN `n_neuropathy` VARCHAR(50) DEFAULT NULL AFTER `n_disorders_of_neuromuscular_junction`,
	ADD COLUMN `n_muscle_disease_unspecified` VARCHAR(50) DEFAULT NULL AFTER `n_neuropathy`,
	ADD COLUMN `n_hypoglycemia` VARCHAR(50) DEFAULT NULL AFTER `n_muscle_disease_unspecified`,
	ADD COLUMN `n_anterior_horn_cell_disease` VARCHAR(50) DEFAULT NULL AFTER `n_hypoglycemia`,
	ADD COLUMN `n_congenital_myopathy` VARCHAR(50) DEFAULT NULL AFTER `n_anterior_horn_cell_disease`,

	ADD COLUMN `cond_developmental_intellect_psychiartic` VARCHAR(50) DEFAULT NULL AFTER `n_congenital_myopathy`,
	ADD COLUMN `d_developmental_delay` VARCHAR(50) DEFAULT NULL AFTER `cond_developmental_intellect_psychiartic`,
	ADD COLUMN `d_conversion_disorder` VARCHAR(50) DEFAULT NULL AFTER `d_developmental_delay`,
	ADD COLUMN `d_add_adhd` VARCHAR(50) DEFAULT NULL AFTER `d_conversion_disorder`,
	ADD COLUMN `d_anxiety` VARCHAR(50) DEFAULT NULL AFTER `d_add_adhd`,
	ADD COLUMN `d_autism_spectrum_disorder` VARCHAR(50) DEFAULT NULL AFTER `d_anxiety`,
	ADD COLUMN `d_depression` VARCHAR(50) DEFAULT NULL AFTER `d_autism_spectrum_disorder`,
	ADD COLUMN `d_learning_disability` VARCHAR(50) DEFAULT NULL AFTER `d_depression`,
	ADD COLUMN `d_mild_mental_retardation` VARCHAR(50) DEFAULT NULL AFTER `d_learning_disability`,
	ADD COLUMN `d_moderate_mental_retardation` VARCHAR(50) DEFAULT NULL AFTER `d_mild_mental_retardation`,
	ADD COLUMN `d_severe_mental_retardation` VARCHAR(50) DEFAULT NULL AFTER `d_moderate_mental_retardation`,

	ADD COLUMN `cond_others` VARCHAR(50) DEFAULT NULL AFTER `d_severe_mental_retardation`,
	ADD COLUMN `o_ataxia` VARCHAR(50) DEFAULT NULL AFTER `cond_others`,
	ADD COLUMN `o_syncope` VARCHAR(50) DEFAULT NULL AFTER `o_ataxia`,
	ADD COLUMN `o_hypotonia` VARCHAR(50) DEFAULT NULL AFTER `o_syncope`,
	ADD COLUMN `o_chromosome_abnormality` VARCHAR(50) DEFAULT NULL AFTER `o_hypotonia`,
	ADD COLUMN `o_cerebral_dysgenesis` VARCHAR(50) DEFAULT NULL AFTER `o_chromosome_abnormality`,
	ADD COLUMN `o_movement_disorder_unspecified` VARCHAR(50) DEFAULT NULL AFTER `o_cerebral_dysgenesis`,
	ADD COLUMN `o_microcephaly` VARCHAR(50) DEFAULT NULL AFTER `o_movement_disorder_unspecified`,
	ADD COLUMN `o_cerebral_palsy` VARCHAR(50) DEFAULT NULL AFTER `o_microcephaly`,
	ADD COLUMN `o_hydrocephalus` VARCHAR(50) DEFAULT NULL AFTER `o_cerebral_palsy`,
	ADD COLUMN `o_post_concussion_syndrome` VARCHAR(50) DEFAULT NULL AFTER `o_hydrocephalus`,
	ADD COLUMN `o_single_gene_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_post_concussion_syndrome`,
	ADD COLUMN `o_genetic_disorder_nos` VARCHAR(50) DEFAULT NULL AFTER `o_single_gene_disorder`,
	ADD COLUMN `o_hyperkinetic_movement_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_genetic_disorder_nos`,
	ADD COLUMN `o_tremor` VARCHAR(50) DEFAULT NULL AFTER `o_hyperkinetic_movement_disorder`,
	ADD COLUMN `o_neurocutaneous_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_tremor`,
	ADD COLUMN `o_tic_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_neurocutaneous_disorder`,
	ADD COLUMN `o_cns_tumour` VARCHAR(50) DEFAULT NULL AFTER `o_tic_disorder`,
	ADD COLUMN `o_tumour_other` VARCHAR(50) DEFAULT NULL AFTER `o_cns_tumour`;


ALTER TABLE `dxd_bcch_neurology_revs`
	ADD COLUMN `diagnosis_master_id` INT(11) AFTER `diagnosis_department`,
	ADD COLUMN `cond_seizure_and_epilepsy` VARCHAR(50) DEFAULT NULL AFTER `diagnosis_master_id`,
	ADD COLUMN `s_sym_epil_unclassifiable` VARCHAR(50) DEFAULT NULL AFTER `cond_seizure_and_epilepsy`,
	ADD COLUMN `s_sym_epil_other_defn_location_etiology` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_unclassifiable`,
	ADD COLUMN `s_sym_epil_benign_chilhood_centrotemporal_spikes` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_other_defn_location_etiology`,
	ADD COLUMN `s_sym_epil_general_febrile_seizures` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_benign_chilhood_centrotemporal_spikes`, 
	ADD COLUMN `s_sym_other_spec_convulsions` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_general_febrile_seizures`, 
	ADD COLUMN `s_sym_febrile_seizures` VARCHAR(50) DEFAULT NULL AFTER `s_sym_other_spec_convulsions`, 
	ADD COLUMN `s_sym_juvenile_myoclonic_epil` VARCHAR(50) DEFAULT NULL AFTER `s_sym_febrile_seizures`,
	ADD COLUMN `s_sym_west_syndrome` VARCHAR(50) DEFAULT NULL AFTER `s_sym_juvenile_myoclonic_epil`,
	ADD COLUMN `s_sym_epil_genetic_idiopathic` VARCHAR(50) DEFAULT NULL AFTER `s_sym_west_syndrome`,
	ADD COLUMN `s_sym_symptomatic_focal_epil` VARCHAR(50) DEFAULT NULL AFTER `s_sym_epil_genetic_idiopathic`,  
	ADD COLUMN `s_sym_childhood_absence_epil` VARCHAR(50) DEFAULT NULL AFTER `s_sym_symptomatic_focal_epil`,
	ADD COLUMN `s_sym_neonatal_seizures` VARCHAR(50) DEFAULT NULL AFTER `s_sym_childhood_absence_epil`,

	ADD COLUMN `cond_headaches` VARCHAR(50) DEFAULT NULL AFTER `s_sym_neonatal_seizures`,
	ADD COLUMN `h_sym_chronic_daily_headache` VARCHAR(50) DEFAULT NULL AFTER `cond_headaches`,  
	ADD COLUMN `h_sym_migraine_without_aura` VARCHAR(50) DEFAULT NULL AFTER `h_sym_chronic_daily_headache`, 
	ADD COLUMN `h_sym_pseudotumour_cerebri` VARCHAR(50) DEFAULT NULL AFTER `h_sym_migraine_without_aura`, 
	ADD COLUMN `h_sym_migraine_with_aura` VARCHAR(50) DEFAULT NULL AFTER `h_sym_pseudotumour_cerebri`, 
	ADD COLUMN `h_sym_headache_unspecified` VARCHAR(50) DEFAULT NULL AFTER `h_sym_migraine_with_aura`, 
	ADD COLUMN `h_sym_migraine_variants` VARCHAR(50) DEFAULT NULL AFTER `h_sym_headache_unspecified`, 
	ADD COLUMN `h_sym_tension_headache` VARCHAR(50) DEFAULT NULL AFTER `h_sym_migraine_variants`, 

	ADD COLUMN `cond_infectious_inflammatory_immune_mediated` VARCHAR(50) DEFAULT NULL AFTER `h_sym_tension_headache`,
	ADD COLUMN `i_viral_encephalitis` VARCHAR(50) DEFAULT NULL AFTER `cond_infectious_inflammatory_immune_mediated`,
	ADD COLUMN `i_autoimmune_encephalitis` VARCHAR(50) DEFAULT NULL AFTER `i_viral_encephalitis`,
	ADD COLUMN `i_cns_vasculitis` VARCHAR(5010) DEFAULT NULL AFTER `i_autoimmune_encephalitis`,
	ADD COLUMN `i_transverse_myelitis` VARCHAR(50) DEFAULT NULL AFTER `i_cns_vasculitis`,
	ADD COLUMN `i_bacterial_meningitis` VARCHAR(50) DEFAULT NULL AFTER `i_transverse_myelitis`,
	ADD COLUMN `i_acute_disseminated_encephalomyelitis` VARCHAR(50) DEFAULT NULL AFTER `i_bacterial_meningitis`,
	ADD COLUMN `i_multiple_sclerosis` VARCHAR(50) DEFAULT NULL AFTER `i_acute_disseminated_encephalomyelitis`,

	ADD COLUMN `cond_neonatal_and_neuromuscular` VARCHAR(50) DEFAULT NULL AFTER `i_multiple_sclerosis`,
	ADD COLUMN `n_spinal_muscular_atrophy` VARCHAR(50) DEFAULT NULL AFTER `cond_neonatal_and_neuromuscular`,
	ADD COLUMN `n_hypoxic_ischemic_encephalopathy` VARCHAR(50) DEFAULT NULL AFTER `n_spinal_muscular_atrophy`,
	ADD COLUMN `n_inborn_error_of_metabolism` VARCHAR(50) DEFAULT NULL AFTER `n_hypoxic_ischemic_encephalopathy`,
	ADD COLUMN `n_myotonic_dystrophy` VARCHAR(50) DEFAULT NULL AFTER `n_inborn_error_of_metabolism`,
	ADD COLUMN `n_stroke` VARCHAR(50) DEFAULT NULL AFTER `n_myotonic_dystrophy`,
	ADD COLUMN `n_disorders_of_neuromuscular_junction` VARCHAR(50) DEFAULT NULL AFTER `n_stroke`,
	ADD COLUMN `n_neuropathy` VARCHAR(50) DEFAULT NULL AFTER `n_disorders_of_neuromuscular_junction`,
	ADD COLUMN `n_muscle_disease_unspecified` VARCHAR(50) DEFAULT NULL AFTER `n_neuropathy`,
	ADD COLUMN `n_hypoglycemia` VARCHAR(50) DEFAULT NULL AFTER `n_muscle_disease_unspecified`,
	ADD COLUMN `n_anterior_horn_cell_disease` VARCHAR(50) DEFAULT NULL AFTER `n_hypoglycemia`,
	ADD COLUMN `n_congenital_myopathy` VARCHAR(50) DEFAULT NULL AFTER `n_anterior_horn_cell_disease`,

	ADD COLUMN `cond_developmental_intellect_psychiartic` VARCHAR(50) DEFAULT NULL AFTER `n_congenital_myopathy`,
	ADD COLUMN `d_developmental_delay` VARCHAR(50) DEFAULT NULL AFTER `cond_developmental_intellect_psychiartic`,
	ADD COLUMN `d_conversion_disorder` VARCHAR(50) DEFAULT NULL AFTER `d_developmental_delay`,
	ADD COLUMN `d_add_adhd` VARCHAR(50) DEFAULT NULL AFTER `d_conversion_disorder`,
	ADD COLUMN `d_anxiety` VARCHAR(50) DEFAULT NULL AFTER `d_add_adhd`,
	ADD COLUMN `d_autism_spectrum_disorder` VARCHAR(50) DEFAULT NULL AFTER `d_anxiety`,
	ADD COLUMN `d_depression` VARCHAR(50) DEFAULT NULL AFTER `d_autism_spectrum_disorder`,
	ADD COLUMN `d_learning_disability` VARCHAR(50) DEFAULT NULL AFTER `d_depression`,
	ADD COLUMN `d_mild_mental_retardation` VARCHAR(50) DEFAULT NULL AFTER `d_learning_disability`,
	ADD COLUMN `d_moderate_mental_retardation` VARCHAR(50) DEFAULT NULL AFTER `d_mild_mental_retardation`,
	ADD COLUMN `d_severe_mental_retardation` VARCHAR(50) DEFAULT NULL AFTER `d_moderate_mental_retardation`,

	ADD COLUMN `cond_others` VARCHAR(50) DEFAULT NULL AFTER `d_severe_mental_retardation`,
	ADD COLUMN `o_ataxia` VARCHAR(50) DEFAULT NULL AFTER `cond_others`,
	ADD COLUMN `o_syncope` VARCHAR(50) DEFAULT NULL AFTER `o_ataxia`,
	ADD COLUMN `o_hypotonia` VARCHAR(50) DEFAULT NULL AFTER `o_syncope`,
	ADD COLUMN `o_chromosome_abnormality` VARCHAR(50) DEFAULT NULL AFTER `o_hypotonia`,
	ADD COLUMN `o_cerebral_dysgenesis` VARCHAR(50) DEFAULT NULL AFTER `o_chromosome_abnormality`,
	ADD COLUMN `o_movement_disorder_unspecified` VARCHAR(50) DEFAULT NULL AFTER `o_cerebral_dysgenesis`,
	ADD COLUMN `o_microcephaly` VARCHAR(50) DEFAULT NULL AFTER `o_movement_disorder_unspecified`,
	ADD COLUMN `o_cerebral_palsy` VARCHAR(50) DEFAULT NULL AFTER `o_microcephaly`,
	ADD COLUMN `o_hydrocephalus` VARCHAR(50) DEFAULT NULL AFTER `o_cerebral_palsy`,
	ADD COLUMN `o_post_concussion_syndrome` VARCHAR(50) DEFAULT NULL AFTER `o_hydrocephalus`,
	ADD COLUMN `o_single_gene_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_post_concussion_syndrome`,
	ADD COLUMN `o_genetic_disorder_nos` VARCHAR(50) DEFAULT NULL AFTER `o_single_gene_disorder`,
	ADD COLUMN `o_hyperkinetic_movement_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_genetic_disorder_nos`,
	ADD COLUMN `o_tremor` VARCHAR(50) DEFAULT NULL AFTER `o_hyperkinetic_movement_disorder`,
	ADD COLUMN `o_neurocutaneous_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_tremor`,
	ADD COLUMN `o_tic_disorder` VARCHAR(50) DEFAULT NULL AFTER `o_neurocutaneous_disorder`,
	ADD COLUMN `o_cns_tumour` VARCHAR(50) DEFAULT NULL AFTER `o_tic_disorder`,
	ADD COLUMN `o_tumour_other` VARCHAR(50) DEFAULT NULL AFTER `o_cns_tumour`;

INSERT INTO structure_value_domains (`domain_name`, `override`, `source`) VALUES
('neuro_cond_status', 'open', ''),
('neuro_symptoms_status', 'open', '');

INSERT INTO structure_permissible_values (`value`, `language_alias`) VALUES
('require physician verification', 'Require Physician Verification');

INSERT INTO structure_value_domains_permissible_values
(`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`, `use_as_input`)
VALUES
((SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), (SELECT `id` FROM structure_permissible_values WHERE `value` = 'yes' AND `language_alias` = 'bcch_yes'), 1, 1, 1),
((SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), (SELECT `id` FROM structure_permissible_values WHERE `value` = 'no' AND `language_alias` = 'bcch_no'), 2, 1, 1);


INSERT INTO structure_value_domains_permissible_values
(`structure_value_domain_id`, `structure_permissible_value_id`, `display_order`, `flag_active`, `use_as_input`)
VALUES
((SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), (SELECT `id` FROM structure_permissible_values WHERE `value` = 'yes' AND `language_alias` = 'bcch_yes'), 1, 1, 1),
((SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), (SELECT `id` FROM structure_permissible_values WHERE `value` = 'require physician verification' AND `language_alias` = 'Require Physician Verification'), 2, 1, 1);


INSERT INTO structure_fields
(`plugin`, `model`, `tablename`, `field`, `language_label`, `language_tag`, `type`, `setting`, `structure_value_domain`, `language_help`, `validation_control`, `value_domain_control`, `field_control`, `flag_confidential`)
VALUES
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'cond_seizure_and_epilepsy', 'Seizure and Epilepsy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_epil_unclassifiable', 'Epilepsy, unclassifiable/unspecified', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_epil_other_defn_location_etiology', 'Epilepsy, other, defined by location and etiology', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_epil_benign_chilhood_centrotemporal_spikes', 'Benign childhood epilepsy with centrotemporal spikes', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_epil_general_febrile_seizures', 'Generalized epilepsy with febrile seizures', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_other_spec_convulsions', 'Other specified convulsions', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_febrile_seizures', 'Febrile seizures', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_juvenile_myoclonic_epil', 'Juvenile mycolonic epilepsy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_west_syndrome', 'West syndrome', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_epil_genetic_idiopathic', 'Epilepsy, genetic/idiopathic', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_symptomatic_focal_epil', 'Symptomatic focal epilepsy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_childhood_absence_epil', 'Childhood absence epilepsy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 's_sym_neonatal_seizures', 'Neonatal seizures', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),

('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'cond_headaches', 'Headaches Conditions', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_chronic_daily_headache', 'Chronic daily headache', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_migraine_without_aura', 'Migraine without aura', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_pseudotumour_cerebri', 'Pseudotumour cerebri', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_migraine_with_aura', 'Migraine with aura', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_headache_unspecified', 'Headache, unspecified', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_migraine_variants', 'Migraine variants', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'h_sym_tension_headache', 'Tension headache', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),

('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'cond_infectious_inflammatory_immune_mediated', 'Infectious, Inflammatory, and Immune-mediated', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_viral_encephalitis', 'Viral encephalitis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_autoimmune_encephalitis', 'Autoimmune encephalitis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_cns_vasculitis', 'CNS vasculitis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_transverse_myelitis', 'Transverse myelitis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_bacterial_meningitis', 'Bacterial meningitis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_acute_disseminated_encephalomyelitis', 'Acute disseminated encephalomyelitis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'i_multiple_sclerosis', 'Multiple sclerosis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),

('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'cond_neonatal_and_neuromuscular', 'Neonatal & Neuromuscular', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_spinal_muscular_atrophy', 'Spinal muscular atrophy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_hypoxic_ischemic_encephalopathy', 'Hypoxic ischemic encephalopathy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_inborn_error_of_metabolism', 'Inborn error of metabolism', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_myotonic_dystrophy', 'Myotonic dystrophy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_stroke', 'Stroke', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_disorders_of_neuromuscular_junction', 'Disorders of neuromuscular junction', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_neuropathy', 'Neuropathy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_muscle_disease_unspecified', 'Muscle disease, unspecified', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_hypoglycemia', 'Hypoglycemia', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_anterior_horn_cell_disease', 'Anterior horn cell disease, other', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'n_congenital_myopathy', 'Congenital myopathy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),


('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'cond_developmental_intellect_psychiartic', 'Developmental, Intellectual, and Psychiatric', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_developmental_delay', 'Developmental delay', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_conversion_disorder', 'Conversion disorder', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_add_adhd', 'ADD/ADHD', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_anxiety', 'Anxiety', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_autism_spectrum_disorder', 'Autism spectrum disorder', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_depression', 'Depression', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_learning_disability', 'Learning disability', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_mild_mental_retardation', 'Mild mental retardation', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_moderate_mental_retardation', 'Moderate mental retardation', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'd_severe_mental_retardation', 'Severe mental retardation', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),

('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'cond_others', 'Others', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_cond_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_ataxia', 'Ataxia', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_syncope', 'Syncope', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_hypotonia', 'Hypotonia', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_chromosome_abnormality', 'Chromosome abnormality', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_cerebral_dysgenesis', 'Cerebral dysgenesis', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_movement_disorder_unspecified', 'Movement disorder, unspecified', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_microcephaly', 'Microcephaly', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_cerebral_palsy', 'Cerebral Palsy', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_hydrocephalus', 'Hydrocephalus', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_post_concussion_syndrome', 'Post-concussion syndrome', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_single_gene_disorder', 'Single gene disorder', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_genetic_disorder_nos', 'Genetic disorder NOS', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_hyperkinetic_movement_disorder', 'Hyperkinetic movement disorder', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_tremor', 'Tremor', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_neurocutaneous_disorder', 'Neurocutaneous disorder', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_tic_disorder', 'Tic disorder', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_cns_tumour', 'CNS tumour', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0),
('ClinicalAnnotation', 'DiagnosisDetail', 'dxd_bcch_neurology', 'o_tumour_other', 'Tumour, other', '', 'select', '', (SELECT `id` FROM structure_value_domains WHERE `domain_name` = 'neuro_symptoms_status'), '', 'open', 'open', 'open', 0);




INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='cond_seizure_and_epilepsy'),
1, 25, 'Symptom Categories', 0, '', 0, 0,
0, 0, 0, '',
0, 1, 0, 1, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='cond_headaches'),
1, 27, '', 0, '', 0, 0,
0, 0, 0, '',
0, 1, 0, 1, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='cond_infectious_inflammatory_immune_mediated'),
1, 29, '', 0, '', 0, 0,
0, 0, 0, '',
0, 1, 0, 1, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='cond_neonatal_and_neuromuscular'),
1, 31, '', 0, '', 0, 0,
0, 0, 0, '',
0, 1, 0, 1, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='cond_developmental_intellect_psychiartic'),
1, 33, '', 0, '', 0, 0,
0, 0, 0, '',
0, 1, 0, 1, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='cond_others'),
1, 35, '', 0, '', 0, 0,
0, 0, 0, '',
0, 1, 0, 1, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);


INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_epil_unclassifiable'),
2, 50, 'Specific Symptoms: Seizure and Epilepsy Symptoms', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_epil_other_defn_location_etiology'),
2, 52, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_epil_benign_chilhood_centrotemporal_spikes'),
2, 54, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_epil_general_febrile_seizures'),
2, 56, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_other_spec_convulsions'),
2, 58, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_febrile_seizures'),
2, 60, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_juvenile_myoclonic_epil'),
2, 62, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_west_syndrome'),
2, 64, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_epil_genetic_idiopathic'),
2, 66, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_symptomatic_focal_epil'),
2, 68, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_childhood_absence_epil'),
2, 70, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='s_sym_neonatal_seizures'),
2, 72, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);


INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_chronic_daily_headache'),
2, 74, 'Specific Symptoms: Headaches', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_migraine_without_aura'),
2, 76, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_pseudotumour_cerebri'),
2, 78, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_migraine_with_aura'),
2, 80, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_headache_unspecified'),
2, 82, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_migraine_variants'),
2, 84, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='h_sym_tension_headache'),
2, 86, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);

INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_viral_encephalitis'),
2, 92, 'Specific Symptoms: Infectious, inflammatory, and immune-mediated', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_autoimmune_encephalitis'),
2, 94, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_cns_vasculitis'),
2, 96, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_transverse_myelitis'),
2, 98, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_bacterial_meningitis'),
2, 100, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_acute_disseminated_encephalomyelitis'),
2, 102, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='i_multiple_sclerosis'),
2, 104, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);



INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_spinal_muscular_atrophy'),
2, 110, 'Specific Symptoms: Neonatal and neuromuscular', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_hypoxic_ischemic_encephalopathy'),
2, 112, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_inborn_error_of_metabolism'),
2, 114, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_myotonic_dystrophy'),
2, 116, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_stroke'),
2, 118, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_disorders_of_neuromuscular_junction'),
2, 120, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_neuropathy'),
2, 122, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_muscle_disease_unspecified'),
2, 124, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_hypoglycemia'),
2, 126, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_anterior_horn_cell_disease'),
2, 128, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='n_congenital_myopathy'),
2, 130, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);



INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_developmental_delay'),
2, 140, 'Specific Symptoms: Developmental, intellectual, and psychiatric', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_conversion_disorder'),
2, 142, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_add_adhd'),
2, 144, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_anxiety'),
2, 146, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_autism_spectrum_disorder'),
2, 148, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_depression'),
2, 150, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_learning_disability'),
2, 152, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_mild_mental_retardation'),
2, 154, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_moderate_mental_retardation'),
2, 156, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='d_severe_mental_retardation'),
2, 158, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);





INSERT INTO structure_formats
(`structure_id`, `structure_field_id`,
`display_column`, `display_order`, `language_heading`, `flag_override_label`, `language_label`, `flag_override_tag`, `flag_override_help`,
`flag_override_type`, `flag_override_setting`, `flag_override_default`, `default`,
`flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_editgrid`, `flag_editgrid_readonly`,
`flag_summary`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_float`, `margin`) VALUES
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_ataxia'),
2, 160, 'Specific Symptoms: Others', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_syncope'),
2, 162, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_hypotonia'),
2, 164, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_chromosome_abnormality'),
2, 166, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_cerebral_dysgenesis'),
2, 168, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_movement_disorder_unspecified'),
2, 170, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_microcephaly'),
2, 172, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_cerebral_palsy'),
2, 174, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_hydrocephalus'),
2, 176, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_post_concussion_syndrome'),
2, 178, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_single_gene_disorder'),
2, 180, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_genetic_disorder_nos'),
2, 182, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_hyperkinetic_movement_disorder'),
2, 184, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_tremor'),
2, 186, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_neurocutaneous_disorder'),
2, 188, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_tic_disorder'),
2, 190, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_cns_tumour'),
2, 192, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0),
((SELECT `id` FROM structures WHERE `alias`='dx_bcch_neurology'),
(SELECT `id` FROM structure_fields WHERE `plugin`='ClinicalAnnotation' AND `model`='DiagnosisDetail' AND `tablename`='dxd_bcch_neurology' AND `field`='o_tumour_other'),
2, 194, '', 0, '', 0, 0,
0, 0, 0, '',
1, 0, 1, 0, 1, 0, 0, 0,
0, 0, 0, 0, 1, 0, 0);



REPLACE INTO `i18n` (`id`, `en`, `fr`) VALUES
('Require Physician Verification', 'Require Physician Verification', ''),
('Specific Symptoms: Seizure and Epilepsy', 'Specific Symptoms: Seizure and Epilepsy', ''),
('Specific Symptoms: Headaches', 'Specific Symptoms: Headaches', ''),
('Specific Symptoms: Infectious, inflammatory, and immune-mediated', 'Specific Symptoms: Infectious, inflammatory, and immune-mediated', '');


-- Coding Table:

CREATE TABLE coding_icd_10_neurology (
	`id` VARCHAR(10) NOT NULL,
	`field_name` VARCHAR(100) NOT NULL,
	`category` VARCHAR(100) NOT NULL,
	`en_description` VARCHAR(300) NOT NULL,
	`fr_description` VARCHAR(300) DEFAULT NULL,
	`source` VARCHAR(100) DEFAULT NULL,
	`validation` TINYINT(1) DEFAULT 0,
	`validation_source` VARCHAR(100) DEFAULT NULL
);

INSERT INTO coding_icd_10_neurology (`id`, `field_name`, `category`, `en_description`, `fr_description`, `source`, `validation`, `validation_source`) 
VALUES
('G40.9', 's_sym_epil_unclassifiable','Seizure and Epilepsy', 'Epilepsy, unclassifiable/unspecified', '', 'BCCH Neurology', 1, 'WHO'),
('G40.8', 's_sym_epil_other_defn_location_etiology', 'Seizure and Epilepsy', 'Epilepsy, other, defined by location and etiology', '', 'BCCH Neurology', 1, 'WHO'),
('G40.0', 's_sym_epil_benign_chilhood_centrotemporal_spikes', 'Seizure and Epilepsy', 'Benign chilhood epilepsy with centrotemporal spikes', '', 'BCCH Neurology', 1, 'WHO'),
('G40.3', 's_sym_epil_general_febrile_seizures', 'Seizure and Epilepsy', 'Generalized epilepsy with febrile seizures', '', 'BCCH Neurology', 0, ''),
('R56.8', 's_sym_other_spec_convulsions', 'Seizure and Epilepsy', 'Other specified convulsions', '', 'BCCH Neurology', 1, 'WHO'),
('R56.0', 's_sym_febrile_seizures', 'Seizure and Epilepsy', 'Febrile seizures', '', 'BCCH Neurology', 1, 'WHO'),
('G40.3', 's_sym_juvenile_myoclonic_epil', 'Seizure and Epilepsy', 'Juvenile mycolonic epilepsy', '', 'BCCH Neurology', 1, 'WHO'),
('G40.4', 's_sym_west_syndrome', 'Seizure and Epilepsy', 'West syndrome', '', 'BCCH Neurology', 1, 'WHO'),
('G40.0', 's_sym_epil_genetic_idiopathic', 'Seizure and Epilepsy', 'Epilepsy, genetic/idiopathic', '', 'BCCH Neurology', 1, 'WHO'),
('G40.8', 's_sym_symptomatic_focal_epil', 'Seizure and Epilepsy', 'Symptomatic focal epilepsy', '', 'BCCH Neurology', 1, 'WHO'),
('G40.3', 's_sym_childhood_absence_epil', 'Seizure and Epilepsy', 'Childhood absence epilepsy', '', 'BCCH Neurology', 1, 'WHO'),
('P90', 's_sym_neonatal_seizures', 'Seizure and Epilepsy', 'Neonatal seizures', '', 'BCCH Neurology', 1, 'WHO');

INSERT INTO coding_icd_10_neurology (`id`, `field_name`, `category`, `en_description`, `fr_description`, `source`, `validation`, `validation_source`) 
VALUES
('G44.0', 'h_sym_chronic_daily_headache', 'Headaches', 'Chronic daily headache', '', 'BCCH Neurology', 1, 'WHO'),
('G43.0', 'h_sym_migraine_without_aura', 'Headaches', 'Migraine without aura', '', 'BCCH Neurology', 1, 'WHO'),
('G93.2', 'h_sym_pseudotumour_cerebri', 'Headaches', 'Pseudotumour cerebri', '', 'BCCH Neurology', 0, ''),
('G43.1', 'h_sym_migraine_with_aura', 'Headaches', 'Migraine with aura', '', 'BCCH Neurology', 1, 'WHO'),
('R51', 'h_sym_headache_unspecified', 'Headaches', 'Headache, unspecified', '', 'BCCH Neurology', 1, 'WHO'),
('G43.9', 'h_sym_migraine_variants', 'Headaches', 'Migraine variants', '', 'BCCH Neurology', 1, 'WHO'),
('G44.2', 'h_sym_tension_headache', 'Headaches', 'Tension headache', '', 'BCCH Neurology', 1, 'WHO');


INSERT INTO coding_icd_10_neurology (`id`, `field_name`, `category`, `en_description`, `fr_description`, `source`, `validation`, `validation_source`) 
VALUES
('A86', 'i_viral_encephalitis', 'Infectious, Inflammatory, and Immune-mediated', 'Viral encephalitis', '', 'BCCH Neurology', 1, 'WHO'),
('G04.8', 'i_autoimmune_encephalitis', 'Infectious, Inflammatory, and Immune-mediated', 'Autoimmune encephalitis', '', 'BCCH Neurology', 0, ''),
('I67.7', 'i_cns_vasculitis', 'Infectious, Inflammatory, and Immune-mediated', 'CNS vasculitis', '', 'BCCH Neurology', 0, ''),
('G37.3', 'i_transverse_myelitis', 'Infectious, Inflammatory, and Immune-mediated', 'Transverse myelitis', '', 'BCCH Neurology', 1, 'WHO'),
('G00.9', 'i_bacterial_meningitis', 'Infectious, Inflammatory, and Immune-mediated', 'Bacterial meningitis', '', 'BCCH Neurology', 1, 'WHO'),
('G04.0', 'i_acute_disseminated_encephalomyelitis', 'Infectious, Inflammatory, and Immune-mediated', 'Acute disseminated encephalomyelitis', '', 'BCCH Neurology', 1, 'WHO'),
('G35', 'i_multiple_sclerosis', 'Infectious, Inflammatory, and Immune-mediated', 'Multiple sclerosis', '', 'BCCH Neurology', 1, 'WHO');


INSERT INTO coding_icd_10_neurology (`id`, `field_name`, `category`, `en_description`, `fr_description`, `source`, `validation`, `validation_source`) 
VALUES
('G12.9', 'n_spinal_muscular_atrophy', 'Neonatal & Neuromuscular', 'Spinal muscular atrophy', '', 'BCCH Neurology', 1, 'WHO'),
('G93.1', 'n_hypoxic_ischemic_encephalopathy', 'Neonatal & Neuromuscular', 'Hypoxic ischemic encephalopathy', '', 'BCCH Neurology', 0, ''),
('E72.9', 'n_inborn_error_of_metabolism', 'Neonatal & Neuromuscular', 'Inborn error of metabolism', '', 'BCCH Neurology', 0, 'WHO'),
('G71.1', 'n_myotonic_dystrophy', 'Neonatal & Neuromuscular', 'Myotonic dystrophy', '', 'BCCH Neurology', 1, 'WHO'),
('I64', 'n_stroke', 'Neonatal & Neuromuscular', 'Stroke', '', 'BCCH Neurology', 1, 'WHO'),
('G70.9', 'n_disorders_of_neuromuscular_junction', 'Neonatal & Neuromuscular', 'Disorders of neuromuscular junction', '', 'BCCH Neurology', 0, ''),
('G64', 'n_neuropathy', 'Neonatal & Neuromuscular', 'Neuropathy', '', 'BCCH Neurology', 0, 'WHO'),
('M62.99', 'n_muscle_disease_unspecified', 'Neonatal & Neuromuscular', 'Muscle disease, unspecified', '', 'BCCH Neurology', 0, ''),
('E16.2', 'n_hypoglycemia', 'Neonatal & Neuromuscular', 'Hypoglycemia', '', 'BCCH Neurology', 1, 'WHO'),
('G12.28', 'n_anterior_horn_cell_disease', 'Neonatal & Neuromuscular', 'Anterior horn cell disease, other', '', 'BCCH Neurology', 0, ''),
('G71.2', 'n_congenital_myopathy', 'Neonatal & Neuromuscular', 'Congenital myopathy', '', 'BCCH Neurology', 1, 'WHO');

INSERT INTO coding_icd_10_neurology (`id`, `field_name`, `category`, `en_description`, `fr_description`, `source`, `validation`, `validation_source`) 
VALUES
('R62.9', 'd_developmental_delay', 'Developmental, Intellectual, and Psychiatric', 'Developmental delay', '', 'BCCH Neurology', 1, 'WHO'),
('F44.9', 'd_conversion_disorder', 'Developmental, Intellectual, and Psychiatric', 'Conversion disorder', '', 'BCCH Neurology', 1, 'WHO'),
('F90.0', 'd_add_adhd', 'Developmental, Intellectual, and Psychiatric', 'ADD/ADHD', '', 'BCCH Neurology', 1, 'WHO'),
('F41.9', 'd_anxiety', 'Developmental, Intellectual, and Psychiatric', 'Anxiety', '', 'BCCH Neurology', 1, 'WHO'),
('F84.0', 'd_autism_spectrum_disorder', 'Developmental, Intellectual, and Psychiatric', 'Austism spectrum disorder', '', 'BCCH Neurology', 1, 'WHO'),
('F32.9', 'd_depression', 'Developmental, Intellectual, and Psychiatric', 'Depression', '', 'BCCH Neurology', 1, 'WHO'),
('F81.9', 'd_learning_disability', 'Developmental, Intellectual, and Psychiatric', 'Learning disability', '', 'BCCH Neurology', 1, 'WHO'),
('F70.9', 'd_mild_mental_retardation', 'Developmental, Intellectual, and Psychiatric', 'Mild mental retardation', '', 'BCCH Neurology', 1, 'WHO'),
('F71.9', 'd_moderate_mental_retardation', 'Developmental, Intellectual, and Psychiatric', 'Moderate mental retardation', '', 'BCCH Neurology', 1, 'WHO'),
('F72.9', 'd_severe_mental_retardation', 'Developmental, Intellectual, and Psychiatric', 'Severe mental retardation', '', 'BCCH Neurology', 1, 'WHO');

INSERT INTO coding_icd_10_neurology (`id`, `field_name`, `category`, `en_description`, `fr_description`, `source`, `validation`, `validation_source`) 
VALUES
('R27.0', 'o_ataxia', 'Others', 'Ataxia', '', 'BCCH Neurology', 1, 'WHO'),
('R55', 'o_syncope', 'Others', 'Syncope', '', 'BCCH Neurology', 1, 'WHO'),
('R29.8', 'o_hypotonia', 'Others', 'Hypotonia', '', 'BCCH Neurology', 0, ''),
('Q99.9', 'o_chromosome_abnormality', 'Others', 'Chromosome abnormality', '', 'BCCH Neurology', 1, 'WHO'),
('Q04.3', 'o_cerebral_dysgenesis', 'Others', 'Cerebral dysgenesis', '', 'BCCH Neurology', 0, 'WHO'),
('F98.4', 'o_movement_disorder_unspecified', 'Others', 'Movement disorder, unspecified', '', 'BCCH Neurology', 1, 'WHO'),
('Q02', 'o_microcephaly', 'Others', 'Microcephaly', '', 'BCCH Neurology', 1, 'WHO'),
('G80.9', 'o_cerebral_palsy', 'Others', 'Cerebral palsy', '', 'BCCH Neurology', 1, 'WHO'),
('G91.9', 'o_hydrocephalus', 'Others', 'Hydrocephalus', '', 'BCCH Neurology', 1, 'WHO'),
('F07.2', 'o_post_concussion_syndrome', 'Others', 'Post-concussion syndrome', '', 'BCCH Neurology', 1, 'WHO'),
('Q99.9', 'o_single_gene_disorder', 'Others', 'Single gene disorder', '', 'BCCH Neurology', 0, ''),
('Q99.9', 'o_genetic_disorder_nos', 'Others', 'Genetic disorder NOS', '', 'BCCH Neurology', 0, ''),
('G25.9', 'o_hyperkinetic_movement_disorder', 'Others', 'Hyperkinetic movement disorder', '', 'BCCH Neurology', 0, ''),
('R25.1', 'o_tremor', 'Others', 'Tremor', '', 'BCCH Neurology', 1, 'WHO'),
('Q85.8', 'o_neurocutaneous_disorder', 'Others', 'Neurocutaneous disorder', '', 'BCCH Neurology', 0, 'WHO'),
('F95.9', 'o_tic_disorder', 'Others', 'Tic disorder', '', 'BCCH Neurology', 1, 'WHO'),
('D43.9', 'o_cns_tumour', 'Others', 'CNS tumour', '', 'BCCH Neurology', 0, ''),
('D48.9', 'o_tumour_other', 'Others', 'Tumour, other', '', 'BCCH Neurology', 1, 'WHO');


-- BB-237

INSERT INTO misc_identifier_controls
(`misc_identifier_name`, `flag_active`, `display_order`, `flag_once_per_participant`, `flag_confidential`, `flag_unique`, `pad_to_length`, `flag_link_to_study`)
VALUES
('BCSICR ID', 1, 10, 1, 1, 1, 0, 1);

-- BB-238

INSERT INTO misc_identifier_controls
(`misc_identifier_name`, `flag_active`, `display_order`, `flag_once_per_participant`, `flag_confidential`, `flag_unique`, `pad_to_length`, `flag_link_to_study`)
VALUES
('BTIC ID', 1, 10, 1, 1, 1, 0, 1);


REPLACE INTO `i18n` (`id`, `en`, `fr`)
VALUES 
('there are no blood sample labels to print', "There are no blood sample labels to print", ''),
('there are no barcodes to print', "There are no barcodes to print", ''),
('manual deletion of neurology diagnosis code is not allowed', "Manual deletion of neurology diagnosis code is not allowed", ''),
('print easyblood labels', "Print EasyBlood Labels", '');




