<?php

if(in_array($misc_identifier_data['MiscIdentifierControl']['misc_identifier_name'], array('VOA#', 'pathology number'))) {
	$this->flash(__('this identifier is a copy generated by the system'),'/ClinicalAnnotation/Participants/profile/'.$participant_id.'/' );
	return;
}

?>