<?php

if(in_array($misc_identifier_data['MiscIdentifierControl']['misc_identifier_name'], array('VOA#', 'pathology number'))) {
	$arr_allow_deletion = array('allow_deletion' => false, 'msg' => 'this identifier is a copy generated by the system');
}

?>