<?php
require_once 'sardoToAtim.php';
SardoToAtim::$columns = array(
	"No de dossier"						=> 1,
    "Nom"								=> 2,
    "Prénom"							=> 3,
    "No banque de tissus"				=> 4,
    "No patient SARDO"					=> 5,
    "RAMQ"								=> 6,
    "Sexe"								=> 7,
    "Race"								=> 8,
    "Date de naissance"					=> 9,
    "Age actuel"						=> 10,
    "Date du diagnostic"				=> 11,
    "Age au diagnostic"					=> 12,
    "Antécédents familiaux ce cancer"	=> 13,
    "Ménopause"							=> 14,
    "Gravida Para Aborta"				=> 15,
    "No DX SARDO"						=> 16,
    "Diagnostic"						=> 17,
    "Latéralité"						=> 18,
    "Code topographique"				=> 19,
    "Topographie"						=> 20,
    "Code morphologique"				=> 21,
    "Morphologie"						=> 22,
    "TNM clinique"						=> 23,
    "TNM pT"							=> 24,
    "TNM pN"							=> 25,
    "TNM pM"							=> 26,
    "TNM pathologique"					=> 27,
    "TNM G"								=> 28,
    "BIOP+ 1 Tx00 - date"				=> 29,
    "BIOP+ 1 Tx00"						=> 30,
    "CHIR 1 Tx00 - date"				=> 31,
    "CHIR 1 Tx00"						=> 32,
    "CHIR 1 Tx00 - no patho"			=> 33,
    "Atteinte multicentrique"			=> 34,
    "Atteinte multifocale"				=> 35,
    "Ganglions régionaux"				=> 36,
    "Ganglions régionaux - prop"		=> 37,
    "Ganglions régionaux - sent"		=> 38,
    "Grade de Nottingham"				=> 39,
    "Grade histologique sur 3"			=> 40,
    "Grade nucléaire"					=> 41,
    "HER2NEU"							=> 42,
    "HER2NEU FISH"						=> 43,
    "HER2NEU Herceptest"				=> 44,
    "HER2NEU TAB 250"					=> 45,
    "Index mitotique"					=> 46,
    "Marges de résection"				=> 47,
    "Récepteurs oestrogènes"			=> 48,
    "Récepteurs progestatifs"			=> 49,
    "Récepteurs hormonaux"				=> 50,
    "Taille tumeur (mm)"				=> 51,
    "Taille tumeur (mm) - num"			=> 52,
    "CHIMIO néo-adjuvante Tx00"			=> 53,
    "CHIMIO adjuvante Tx00"				=> 54,
    "HORM néo-adjuvante Tx00"			=> 55,
    "HORM adjuvante Tx00"				=> 56,
    "RADIO néo-adjuvante Tx00"			=> 57,
    "RADIO adjuvante Tx00"				=> 58,
    "Pr00 - sites d'atteinte"			=> 59,
    "Pr01 - date"						=> 60,
    "Pr01 - sites"						=> 61,
    "Délai DX-Pr01 (M)"					=> 62,
    "Délai DX-Pr01 (J)"					=> 63,
    "Pr02 - date"						=> 64,
    "Pr02 - sites"						=> 65,
    "Délai Pr01-Pr02 (M)"				=> 66,
    "Délai Pr01-Pr02 (J)"				=> 67,
    "Pr03 - date"						=> 68,
    "Pr03 - sites"						=> 69,
    "Délai Pr02-Pr03 (M)"				=> 70,
    "Délai Pr02-Pr03 (J)"				=> 71,
    "Date dernier contact"				=> 72,
    "Censure (0 = vivant, 1 = mort)"	=> 73,
    "Survie (mois)"						=> 74,
    "Date du décès"						=> 75,
    "Cause de décès"					=> 76
);

SardoToAtim::$bank_identifier_ctrl_ids_column_name = 'No banque de tissus';
SardoToAtim::$hospital_identifier_ctrl_ids_column_name = 'No de dossier';

//$xls_reader->read('/Users/francois-michellheureux/Documents/CTRNet/sardo/data/2011-11-15 Export complet sein.XLS');
$xls_reader->read('/Users/francois-michellheureux/Documents/CTRNet/sardo/data/2011-11-18 export sein recherche.XLS');
$cells = $xls_reader->sheets[0]['cells'];

SardoToAtim::basicChecks($cells);
