-- Coding System: ICD-O-3 (Morphology)
-- Filename Source: ICD10CA_Code_Eng_Desc2010_V2_0.txt and ICD10CA_Code_Fra_Desc2010_V2_0.txt
-- Obtained From: Purchased from the CIHI publications department
-- Notes: 

--
-- Table structure for table `coding_icd_o_3_morphology`
--

DROP TABLE IF EXISTS `coding_icd_o_3_morphology`;
CREATE TABLE `coding_icd_o_3_morphology` (
  `id` int(11) NOT NULL,
  `en_description` text,
  `fr_description` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `coding_icd_o_3_morphology`
--

INSERT INTO `coding_icd_o_3_morphology` VALUES
(80000, 'Neoplasm, benign', 'Tumeur bénigne'),
(80001, 'Neoplasm, uncertain whether benign or malignant', 'Tumeur, type non déterminé (bénin ou malin)'),
(80003, 'Neoplasm, malignant', 'Tumeur maligne'),
(80006, 'Neoplasm, metastatic', 'Tumeur métastatique'),
(80010, 'Tumour cells, benign', 'Cellules tumorales bénignes'),
(80011, 'Tumour cells, uncertain whether benign or malignant', 'Cellules tumorales, type non déterminé (bénin ou malin)'),
(80013, 'Tumour cells, malignant', 'Cellules tumorales malignes'),
(80023, 'Malignant tumour, small cell type', 'Tumeur maligne, à petites cellules'),
(80033, 'Malignant tumour, giant cell type', 'Tumeur maligne, à cellules géantes'),
(80043, 'Malignant tumour, fusiform cell type', 'Tumeur maligne, à cellules fusiformes'),
(80100, 'Epithelial tumour, benign', 'Tumeur épithéliale, bénigne'),
(80102, 'Carcinoma in situ NOS', 'Carcinome in situ SAI'),
(80103, 'Carcinoma NOS', 'Carcinome SAI'),
(80106, 'Carcinoma, metastatic NOS', 'Carcinome métastatique SAI'),
(80110, 'Epithelioma, benign', 'Épithélioma bénin'),
(80113, 'Epithelioma, malignant', 'Épithélioma malin'),
(80123, 'Large cell carcinoma NOS', 'Carcinome à grandes cellules SAI'),
(80203, 'Carcinoma, undifferentiated NOS', 'Carcinome indifférencié SAI'),
(80213, 'Carcinoma, anaplastic NOS', 'Carcinome anaplasique SAI'),
(80223, 'Pleomorphic carcinoma', 'Carcinome pléomorphe'),
(80303, 'Giant cell and spindle cell carcinoma', 'Carcinome à cellules géantes et à cellules fusiformes'),
(80313, 'Giant cell carcinoma', 'Carcinome à cellules géantes'),
(80323, 'Spindle cell carcinoma', 'Carcinome à cellules fusiformes'),
(80333, 'Pseudosarcomatous carcinoma', 'Carcinome pseudosarcomateux'),
(80343, 'Polygonal cell carcinoma', 'Carcinome à cellules polygonales'),
(80401, 'Tumorlet', 'Tumorlet'),
(80413, 'Small cell carcinoma NOS', 'Carcinome à petites cellules (anaplasique) SAI'),
(80423, 'Oat cell carcinoma', 'Carcinome à cellules en grain d''avoine'),
(80433, 'Small cell carcinoma, fusiform cell', 'Carcinome à petites cellules (anaplasique), type fusiforme'),
(80443, 'Small cell carcinoma, intermediatecell', 'Carcinome à petites cellules (anaplasique), type intermédiaire'),
(80453, 'Small cell-large cell carcinoma', 'Carcinome à petites cellules (anaplasique) et à grandes cellules'),
(80500, 'Papilloma NOS', 'Papillome SAI (sauf Papillome de la vessie)'),
(80502, 'Papillary carcinoma in situ', 'Carcinome papillaire in situ'),
(80503, 'Papillary carcinoma NOS', 'Carcinome papillaire SAI'),
(80510, 'Verrucous papilloma', 'Papillome verruqueux'),
(80513, 'Verrucous carcinoma NOS', 'Carcinome verruqueux SAI'),
(80520, 'Squamous cell papilloma', 'Papillome épidermoïde'),
(80523, 'Papillary squamous cell carcinoma', 'Carcinome épidermoïde papillaire'),
(80530, 'Inverted papilloma', 'Papillome inversé'),
(80600, 'Papillomatosis NOS', 'Papillomatose SAI'),
(80702, 'Squamous cell carcinoma in situ NOS', 'Carcinome épidermoïde in situ SAI'),
(80703, 'Squamous cell carcinoma NOS', 'Carcinome épidermoïde SAI'),
(80706, 'Squamous cell carcinoma, metastatic NOS', 'Carcinome épidermoïde métastatique SAI'),
(80713, 'Squamous cell carcinoma, keratinizing NOS', 'Carcinome épidermoïde kératinisant SAI'),
(80723, 'Squamous cell carcinoma, large cell, nonkeratinizing', 'Carcinome épidermoïde, à grandes cellules, non kératinisant'),
(80733, 'Squamous cell carcinoma, small cell, nonkeratinizing', 'Carcinome épidermoïde, à petites cellules, non kératinisant'),
(80743, 'Squamous cell carcinoma, spindle cell', 'Carcinome épidermoïde, à cellules fusiformes'),
(80753, 'Adenoid squamous cell carcinoma', 'Carcinome épidermoïde adénoïde'),
(80762, 'Squamous cell carcinoma in situ with questionable stromal invasion', 'Carcinome épidermoïde in situ avec envahissement stromal discutable'),
(80763, 'Squamous cell carcinoma, microinvasive', 'Carcinome épidermoïde micro-invasif'),
(80772, 'Intraepithelial neoplasia, grade III, of cervix, vulva and vagina', 'Néoplasie intra-épithéliale du col de l''utérus, de la vulve et du vagin, stade (type) III (avec dysplasie sévère)'),
(80802, 'Queyrat''s erythroplasia', 'Érythroplasie de Queyrat'),
(80812, 'Bowen''s disease', 'Maladie de Bowen'),
(80823, 'Lymphoepithelial carcinoma', 'Carcinome lympho-épithélial'),
(80901, 'Basal cell tumour', 'Tumeur basocellulaire'),
(80903, 'Basal cell carcinoma NOS', 'Carcinome basocellulaire (pigmenté) SAI'),
(80913, 'Multicentric basal cell carcinoma', 'Carcinome basocellulaire (pigmenté) multicentrique'),
(80923, 'Basal cell carcinoma, morphoea', 'Carcinome basocellulaire (pigmenté) morphéiforme'),
(80933, 'Basal cell carcinoma, fibroepithelial', 'Carcinome basocellulaire (pigmenté), type fibro-épithélial'),
(80943, 'Basosquamous carcinoma', 'Carcinome baso-spinocellulaire, mixte'),
(80953, 'Metatypical carcinoma', 'Carcinome métatypique'),
(80960, 'Intraepidermal epithelioma of Jadassohn', 'Épithélioma intra-épidermique de Jadassohn'),
(81000, 'Trichoepithelioma', 'Tricho-épithéliome'),
(81010, 'Trichofolliculoma', 'Trichofolliculome'),
(81020, 'Tricholemmoma', 'Tricholemmome'),
(81100, 'Pilomatrixoma NOS', 'Épithélioma momifié de Malherbe'),
(81103, 'Pilomatrix carcinoma', 'Carcinome pilomatrix'),
(81200, 'Transitional cell papilloma NOS', 'Papillome à cellules transitionnelles SAI'),
(81201, 'Urothelial papilloma', 'Papillome urothélial'),
(81202, 'Transitional cell carcinoma in situ', 'Carcinome in situ à cellules transitionnelles'),
(81203, 'Transitional cell carcinoma NOS', 'Carcinome à cellules transitionnelles SAI'),
(81210, 'Schneiderian papilloma', 'Papillome schneidérien'),
(81211, 'Transitional cell papilloma, inverted', 'Papillome à cellules transitionnelles, type inversé'),
(81213, 'Schneiderian carcinoma', 'Carcinome schneidérien'),
(81223, 'Transitional cell carcinoma, spindle cell', 'Carcinome à cellules transitionnelles, type fusiforme'),
(81233, 'Basaloid carcinoma', 'Carcinome basaloïde'),
(81243, 'Cloacogenic carcinoma', 'Carcinome cloacogénique'),
(81303, 'Papillary transitional cell carcinoma', 'Carcinome papillaire, à cellules transitionnelles'),
(81400, 'Adenoma NOS', 'Adénome SAI'),
(81401, 'Bronchial adenoma NOS', 'Adénome bronchique SAI'),
(81402, 'Adenocarcinoma in situ NOS', 'Adénocarcinome in situ SAI'),
(81403, 'Adenocarcinoma NOS', 'Adénocarcinome SAI'),
(81406, 'Adenocarcinoma, metastatic NOS', 'Adénocarcinome métastatique SAI'),
(81413, 'Scirrhous adenocarcinoma', 'Adénocarcinome squirrheux'),
(81423, 'Linitis plastica', 'Linite plastique'),
(81433, 'Superficial spreading adenocarcinoma', 'Adénocarcinome à diffusion superficielle'),
(81443, 'Adenocarcinoma, intestinal type', 'Adénocarcinome, type intestinal'),
(81453, 'Carcinoma, diffuse type', 'Carcinome, type diffus'),
(81460, 'Monomorphic adenoma', 'Adénome monomorphe'),
(81470, 'Basal cell adenoma', 'Adénome basocellulaire'),
(81473, 'Basal cell adenocarcinoma', 'Adénocarcinome basocellulaire'),
(81500, 'Islet cell adenoma', 'Adénome insulaire (actif)'),
(81503, 'Islet cell carcinoma', 'Carcinome insulaire'),
(81510, 'Insulinoma NOS', 'Insulinome SAI'),
(81513, 'Insulinoma, malignant', 'Insulinome malin'),
(81520, 'Glucagonoma NOS', 'Glucagonome SAI'),
(81523, 'Glucagonoma, malignant', 'Glucagonome malin'),
(81531, 'Gastrinoma NOS', 'Gastrinome SAI'),
(81533, 'Gastrinoma, malignant', 'Gastrinome malin'),
(81543, 'Mixed islet cell and exocrine adenocarcinoma', 'Adénocarcinome insulaire et exocrine, mixte'),
(81553, 'Vipoma', 'Vipome'),
(81600, 'Bile duct adenoma', 'Adénome des voies biliaires'),
(81603, 'Cholangiocarcinoma', 'Cholangiocarcinome'),
(81610, 'Bile duct cystadenoma', 'Cystadénome biliaire'),
(81613, 'Bile duct cystadenocarcinoma', 'Cystadénocarcinome biliaire'),
(81623, 'Klatskin''s tumour', 'Tumeur de Klatskin'),
(81700, 'Liver cell adenoma', 'Adénome à cellules hépatiques'),
(81703, 'Hepatocellular carcinoma NOS', 'Carcinome hépatocellulaire SAI'),
(81713, 'Hepatocellular carcinoma, fibrolamellar', 'Carcinome hépatocellulaire, type fibrolamellaire'),
(81803, 'Combined hepatocellular carcinomaand cholangiocarcinoma', 'Cholangiocarcinome et carcinome hépatocellulaire, mixte'),
(81900, 'Trabecular adenoma', 'Adénome trabéculaire'),
(81903, 'Trabecular adenocarcinoma', 'Adénocarcinome trabéculaire'),
(81910, 'Embryonal adenoma', 'Adénome embryonnaire'),
(82000, 'Eccrine dermal cylindroma', 'Cylindrome eccrine dermique'),
(82003, 'Adenoid cystic carcinoma', 'Carcinome adénoïde kystique'),
(82013, 'Cribriform carcinoma', 'Carcinome cribriforme'),
(82020, 'Microcystic adenoma', 'Adénome microkystique'),
(82100, 'Adenomatous polyp NOS', 'Polype adénomateux SAI'),
(82102, 'Adenocarcinoma in situ in adenomatous polyp', 'Adénocarcinome in situ sur polype adénomateux'),
(82103, 'Adenocarcinoma in adenomatous polyp', 'Adénocarcinome sur polype adénomateux'),
(82110, 'Tubular adenoma NOS', 'Adénome tubuleux SAI'),
(82113, 'Tubular adenocarcinoma', 'Adénocarcinome tubuleux'),
(82200, 'Adenomatous polyposis coli', 'Polypose adénomateuse du côlon'),
(82203, 'Adenocarcinoma in adenomatous polyposis coli', 'Adénocarcinome sur polypose adénomateuse du côlon'),
(82210, 'Multiple adenomatous polyps', 'Polypes adénomateux multiples'),
(82213, 'Adenocarcinoma in multiple adenomatous polyps', 'Adénocarcinome sur polypes adénomateux multiples'),
(82303, 'Solid carcinoma NOS', 'Carcinome solide SAI'),
(82313, 'Carcinoma simplex', 'Carcinome simplex'),
(82401, 'Carcinoid tumour NOS, of appendix', 'Tumeur carcinoïde de l''appendice SAI'),
(82403, 'Carcinoid tumour NOS', 'Tumeur carcinoïde SAI (sauf de l''appendice)'),
(82411, 'Carcinoid tumour, argentaffin NOS', 'Tumeur carcinoïde argentaffine SAI'),
(82413, 'Carcinoid tumour, argentaffin, malignant', 'Tumeur carcinoïde maligne argentaffine'),
(82433, 'Goblet cell carcinoid', 'Carcinoïde à cellules caliciformes'),
(82443, 'Composite carcinoid', 'Carcinoïde composite'),
(82453, 'Adenocarcinoid tumour', 'Tumeur adénocarcinoïde'),
(82463, 'Neuroendocrine carcinoma', 'Carcinome neuro-endocrinien'),
(82473, 'Merkel cell carcinoma', 'Carcinome à cellules de Merkel'),
(82481, 'Apudoma', 'Apudome'),
(82501, 'Pulmonary adenomatosis', 'Adénomatose pulmonaire'),
(82503, 'Bronchiolo-alveolar adenocarcinoma', 'Adénocarcinome bronchiolo-alvéolaire'),
(82510, 'Alveolar adenoma', 'Adénome alvéolaire'),
(82513, 'Alveolar adenocarcinoma', 'Adénocarcinome alvéolaire'),
(82600, 'Papillary adenoma NOS', 'Adénome papillaire SAI'),
(82603, 'Papillary adenocarcinoma NOS', 'Adénocarcinome papillaire SAI'),
(82611, 'Villous adenoma NOS', 'Adénome villeux SAI'),
(82612, 'Adenocarcinoma in situ in villousadenoma', 'Adénocarcinome in situ sur adénome villeux'),
(82613, 'Adenocarcinoma in villous adenoma', 'Adénocarcinome sur adénome villeux'),
(82623, 'Villous adenocarcinoma', 'Adénocarcinome villeux'),
(82630, 'Tubulovillous adenoma NOS', 'Adénome tubulovilleux SAI'),
(82632, 'Adenocarcinoma in situ in tubulovillous adenoma', 'Adénocarcinome in situ sur adénome tubulovilleux'),
(82633, 'Adenocarcinoma in tubulovillous adenoma', 'Adénocarcinome sur adénome tubulovilleux'),
(82700, 'Chromophobe adenoma', 'Adénome chromophobe'),
(82703, 'Chromophobe carcinoma', 'Carcinome chromophobe'),
(82710, 'Prolactinoma', 'Prolactinome'),
(82800, 'Acidophil adenoma', 'Adénome acidophile'),
(82803, 'Acidophil carcinoma', 'Carcinome acidophile'),
(82810, 'Mixed acidophil-basophil adenoma', 'Adénome acidophile et basophile, mixte'),
(82813, 'Mixed acidophil-basophil carcinoma', 'Carcinome acidophile et basophile, mixte'),
(82900, 'Oxyphilic adenoma', 'Adénome oxyphile'),
(82903, 'Oxyphilic adenocarcinoma', 'Adénocarcinome oxyphile'),
(83000, 'Basophil adenoma', 'Adénome basophile'),
(83003, 'Basophil carcinoma', 'Carcinome basophile'),
(83100, 'Clear cell adenoma', 'Adénome à cellules claires'),
(83103, 'Clear cell adenocarcinoma NOS', 'Adénocarcinome à cellules claires SAI'),
(83111, 'Hypernephroid tumour', 'Tumeur hypernéphroïde'),
(83123, 'Renal cell carcinoma', 'Carcinome à cellules rénales'),
(83130, 'Clear cell adenofibroma', 'Adénofibrome à cellules claires'),
(83143, 'Lipid-rich carcinoma', 'Carcinome riche en lipides'),
(83153, 'Glycogen-rich carcinoma', 'Carcinome riche en glycogène'),
(83203, 'Granular cell carcinoma', 'Carcinome à cellules granuleuses'),
(83210, 'Chief cell adenoma', 'Adénome à cellules principales'),
(83220, 'Water-clear cell adenoma', 'Adénome à cellules eau de roche'),
(83223, 'Water-clear cell adenocarcinoma', 'Adénocarcinome à cellules eau de roche'),
(83230, 'Mixed cell adenoma', 'Adénome à cellules mixtes (à cellules principales et à cellules eau de roche)'),
(83233, 'Mixed cell adenocarcinoma', 'Adénocarcinome à cellules mixtes'),
(83240, 'Lipoadenoma', 'Lipo-adénome'),
(83300, 'Follicular adenoma', 'Adénome folliculaire'),
(83303, 'Follicular adenocarcinoma NOS', 'Adénocarcinome vésiculaire SAI'),
(83313, 'Follicular adenocarcinoma, well differentiated', 'Adénocarcinome vésiculaire, bien différencié'),
(83323, 'Follicular adenocarcinoma, trabecular', 'Adénocarcinome vésiculaire, type trabéculaire'),
(83330, 'Microfollicular adenoma', 'Adénome microvésiculaire'),
(83340, 'Macrofollicular adenoma', 'Adénome macrovésiculaire'),
(83403, 'Papillary carcinoma, follicular variant', 'Carcinome papillaire, à variante vésiculaire'),
(83503, 'Nonencapsulated sclerosing carcinoma', 'Carcinome sclérosant non encapsulé'),
(83601, 'Multiple endocrine adenomas', 'Adénome endocrinien multiple'),
(83611, 'Juxtaglomerular tumour', 'Tumeur juxtaglomérulaire'),
(83700, 'Adrenal cortical adenoma NOS', 'Adénome corticosurrénalien (actif) SAI'),
(83703, 'Adrenal cortical carcinoma', 'Carcinome corticosurrénalien'),
(83710, 'Adrenal cortical adenoma, compactcell', 'Adénome corticosurrénalien, à cellules compactes'),
(83720, 'Adrenal cortical adenoma, heavilypigmented variant', 'Adénome corticosurrénalien, type très pigmenté'),
(83730, 'Adrenal cortical adenoma, clear cell', 'Adénome corticosurrénalien, à cellules claires'),
(83740, 'Adrenal cortical adenoma, glomerulosa cell', 'Adénome corticosurrénalien, à cellules glomérulaires'),
(83750, 'Adrenal cortical adenoma, mixed cell', 'Adénome corticosurrénalien, à cellules mixtes'),
(83800, 'Endometrioid adenoma NOS', 'Adénome endométrioïde SAI'),
(83801, 'Endometrioid adenoma, borderline malignancy', 'Adénome endométrioïde, à la limite de la malignité'),
(83803, 'Endometrioid carcinoma', 'Carcinome endométrioïde'),
(83810, 'Endometrioid adenofibroma NOS', 'Adénofibrome endométrioïde SAI'),
(83811, 'Endometrioid adenofibroma, borderline malignancy', 'Adénofibrome endométrioïde, à la limite de la malignité'),
(83813, 'Endometrioid adenofibroma, malignant', 'Adénofibrome endométrioïde, malin'),
(83900, 'Skin appendage adenoma', 'Adénome des annexes cutanées'),
(83903, 'Skin appendage carcinoma', 'Carcinome des annexes cutanées'),
(84000, 'Sweat gland adenoma', 'Adénome des glandes sudoripares'),
(84001, 'Sweat gland tumour NOS', 'Tumeur des glandes sudoripares SAI'),
(84003, 'Sweat gland adenocarcinoma', 'Adénocarcinome des glandes sudoripares'),
(84010, 'Apocrine adenoma', 'Adénome apocrine'),
(84013, 'Apocrine adenocarcinoma', 'Adénocarcinome apocrine'),
(84020, 'Eccrine acrospiroma', 'Acrospirome eccrine'),
(84030, 'Eccrine spiradenoma', 'Spiradénome eccrine'),
(84040, 'Hidrocystoma', 'Hidrocystome'),
(84050, 'Papillary hidradenoma', 'Hidradénome papillaire'),
(84060, 'Papillary syringadenoma', 'Syringo-adénome papillaire'),
(84070, 'Syringoma NOS', 'Syringome SAI'),
(84080, 'Eccrine papillary adenoma', 'Adénome eccrine papillaire'),
(84100, 'Sebaceous adenoma', 'Adénome sébacé'),
(84103, 'Sebaceous adenocarcinoma', 'Adénocarcinome sébacé'),
(84200, 'Ceruminous adenoma', 'Adénome cérumineux'),
(84203, 'Ceruminous adenocarcinoma', 'Adénocarcinome cérumineux'),
(84301, 'Mucoepidermoid tumour', 'Néoplasme muco-épidermoïde'),
(84303, 'Mucoepidermoid carcinoma', 'Carcinome muco-épidermoïde'),
(84400, 'Cystadenoma NOS', 'Cystadénome SAI'),
(84403, 'Cystadenocarcinoma NOS', 'Cystadénocarcinome SAI'),
(84410, 'Serous cystadenoma NOS', 'Cystadénome séreux SAI'),
(84413, 'Serous cystadenocarcinoma NOS', 'Cystadénocarcinome séreux SAI'),
(84423, 'Serous cystadenoma, borderline malignancy', 'Cystadénome séreux, à la limite de la malignité'),
(84500, 'Papillary cystadenoma NOS', 'Cystadénome papillaire SAI'),
(84503, 'Papillary cystadenocarcinoma NOS', 'Cystadénocarcinome papillaire SAI'),
(84513, 'Papillary cystadenoma, borderlinemalignancy', 'Cystadénome papillaire, à faible potentiel malin'),
(84521, 'Papillary cystic tumour', 'Tumeur kystique papillaire'),
(84600, 'Papillary serous cystadenoma NOS', 'Cystadénome papillaire séreux SAI'),
(84603, 'Papillary serous cystadenocarcinoma', 'Cystadénocarcinome papillaire séreux'),
(84610, 'Serous surface papilloma', 'Papillome séreux de surface'),
(84613, 'Serous surface papillary carcinoma', 'Carcinome papillaire séreux de surface'),
(84623, 'Papillary serous cystadenoma, borderline malignancy', 'Cystadénome papillaire séreux, à faible potentiel malin'),
(84700, 'Mucinous cystadenoma NOS', 'Cystadénome mucineux SAI'),
(84703, 'Mucinous cystadenocarcinoma NOS', 'Cystadénocarcinome mucineux SAI'),
(84710, 'Papillary mucinous cystadenoma NOS', 'Cystadénome mucineux papillaire SAI'),
(84713, 'Papillary mucinous cystadenocarcinoma', 'Cystadénocarcinome papillaire mucineux'),
(84723, 'Mucinous cystadenoma, borderline malignancy', 'Cystadénome mucineux, à faible potentiel malin'),
(84733, 'Papillary mucinous cystadenoma, borderline malignancy', 'Cystadénome papillaire mucineux, à faible potentiel malin'),
(84800, 'Mucinous adenoma', 'Adénome mucineux'),
(84803, 'Mucinous adenocarcinoma', 'Adénocarcinome mucineux'),
(84806, 'Mucinous adenocarcinoma, metastatic [Pseudomyxoma peritonei]', 'Adénocarcinome mucineux, métastatique [Pseudomyxome du péritoine]'),
(84813, 'Mucin-producing adenocarcinoma', 'Adénocarcinome mucosécrétant'),
(84903, 'Signet ring cell carcinoma', 'Carcinome à cellules en bague à chaton'),
(84906, 'Metastatic signet ring cell carcinoma', 'Carcinome à cellules en bague à chaton, métastatique'),
(85002, 'Intraductal carcinoma, noninfiltrating NOS', 'Carcinome intracanalaire, non infiltrant'),
(85003, 'Infiltrating duct carcinoma', 'Carcinome canalaire, infiltrant'),
(85012, 'Comedocarcinoma, noninfiltrating', 'Comédocarcinome, non infiltrant'),
(85013, 'Comedocarcinoma NOS', 'Comédocarcinome SAI'),
(85023, 'Juvenile carcinoma of breast', 'Carcinome juvénile du sein'),
(85030, 'Intraductal papilloma', 'Papillome intracanalaire'),
(85032, 'Noninfiltrating intraductal papillary adenocarcinoma', 'Adénocarcinome intracanalaire, non infiltrant, papillaire'),
(85033, 'Intraductal papillary adenocarcinoma with invasion', 'Adénocarcinome intracanalaire, papillaire, invasif'),
(85040, 'Intracystic papillary adenoma', 'Adénome intrakystique papillaire'),
(85042, 'Noninfiltrating intracystic carcinoma', 'Carcinome intrakystique non infiltrant'),
(85043, 'Intracystic carcinoma NOS', 'Carcinome intrakystique SAI'),
(85050, 'Intraductal papillomatosis NOS', 'Papillomatose intracanalaire (diffuse) SAI'),
(85060, 'Adenoma of nipple', 'Adénome du mamelon'),
(85103, 'Medullary carcinoma NOS', 'Carcinome médullaire SAI'),
(85113, 'Medullary carcinoma with amyloid stroma', 'Carcinome médullaire à stroma amyloïde'),
(85123, 'Medullary carcinoma with lymphoidstroma', 'Carcinome médullaire à stroma lymphoïde'),
(85202, 'Lobular carcinoma in situ', 'Carcinome in situ lobulaire'),
(85203, 'Lobular carcinoma NOS', 'Carcinome lobulaire SAI'),
(85213, 'Infiltrating ductular carcinoma', 'Carcinome canaliculaire, infiltrant'),
(85222, 'Intraductal carcinoma and lobularcarcinoma in situ', 'Carcinome in situ lobulaire avec carcinome intracanalaire'),
(85223, 'Infiltrating duct and lobular carcinoma', 'Carcinome canalaire infiltrant avec carcinome lobulaire (in situ)'),
(85303, 'Inflammatory carcinoma', 'Carcinome inflammatoire'),
(85403, 'Paget''s disease, mammary', 'Maladie de Paget du mamelon'),
(85413, 'Paget''s disease and infiltrating duct carcinoma of breast', 'Maladie de Paget et carcinome canalaire infiltrant du sein'),
(85423, 'Paget''s disease, extramammary', 'Maladie de Paget, extramammaire (sauf la maladie osseuse de Paget)'),
(85433, 'Paget''s disease and intraductal carcinoma of breast', 'Maladie de Paget et carcinome intracanalaire du sein'),
(85500, 'Acinar cell adenoma', 'Adénome à cellules acineuses'),
(85501, 'Acinar cell tumour', 'Néoplasme à cellules acineuses'),
(85503, 'Acinar cell carcinoma', 'Carcinome à cellules acineuses'),
(85603, 'Adenosquamous carcinoma', 'Carcinome adénosquameux'),
(85610, 'Adenolymphoma', 'Adénolymphome'),
(85623, 'Epithelial-myoepithelial carcinoma', 'Carcinome épithélial et myoépithélial'),
(85703, 'Adenocarcinoma with squamous metaplasia', 'Adéno-acanthome'),
(85713, 'Adenocarcinoma with cartilaginousand osseous metaplasia', 'Adénocarcinome avec métaplasie cartilagineuse et osseuse'),
(85723, 'Adenocarcinoma with spindle cell metaplasia', 'Adénocarcinome avec métaplasie fusocellulaire'),
(85733, 'Adenocarcinoma with apocrine metaplasia', 'Adénocarcinome avec métaplasie apocrine'),
(85800, 'Thymoma, benign', 'Thymome bénin'),
(85803, 'Thymoma, malignant', 'Thymome malin'),
(85901, 'Sex cord-stromal tumour', 'Tumeur des cordons sexuels et du stroma gonadique'),
(86000, 'Thecoma NOS', 'Thécome SAI'),
(86003, 'Thecoma, malignant', 'Thécome malin'),
(86010, 'Thecoma, luteinized', 'Thécome lutéinisé'),
(86020, 'Sclerosing stromal tumour', 'Tumeur stromale sclérosante'),
(86100, 'Luteoma NOS', 'Lutéome SAI'),
(86201, 'Granulosa cell tumour NOS', 'Tumeur de la granulosa SAI'),
(86203, 'Granulosa cell tumour, malignant', 'Tumeur maligne de la granulosa'),
(86211, 'Granulosa cell-theca cell tumour', 'Tumeur de la granulosa et de la thèque'),
(86221, 'Juvenile granulosa cell tumour', 'Tumeur de la granulosa juvénile'),
(86231, 'Sex cord tumour with annular tubules', 'Tumeur des cordons sexuels à tubules annelés'),
(86300, 'Androblastoma, benign', 'Androblastome bénin'),
(86301, 'Androblastoma NOS', 'Androblastome SAI'),
(86303, 'Androblastoma, malignant', 'Androblastome malin'),
(86310, 'Sertoli-Leydig cell tumour', 'Tumeur à cellules de Sertoli-Leydig'),
(86321, 'Gynandroblastoma', 'Gynandroblastome'),
(86400, 'Sertoli cell tumour NOS', 'Tumeur à cellules de Sertoli SAI'),
(86403, 'Sertoli cell carcinoma', 'Carcinome à cellules de Sertoli'),
(86410, 'Sertoli cell tumour with lipid storage', 'Tumeur à cellules de Sertoli avec lipoïdose'),
(86500, 'Leydig cell tumour, benign', 'Tumeur bénigne à cellules de Leydig'),
(86501, 'Leydig cell tumour NOS', 'Tumeur à cellules de Leydig SAI'),
(86503, 'Leydig cell tumour, malignant', 'Tumeur maligne à cellules de Leydig'),
(86600, 'Hilus cell tumour', 'Tumeur à cellules du hile'),
(86700, 'Lipid cell tumour of ovary', 'Tumeur à cellules lipoïdiques de l''ovaire'),
(86710, 'Adrenal rest tumour', 'Tumeur des vestiges surrénaliens'),
(86801, 'Paraganglioma NOS', 'Paragangliome SAI'),
(86803, 'Paraganglioma, malignant', 'Paragangliome malin'),
(86811, 'Sympathetic paraganglioma', 'Paragangliome sympathique'),
(86821, 'Parasympathetic paraganglioma', 'Paragangliome parasympathique'),
(86830, 'Gangliocytic paraganglioma', 'Paragangliome gangliocytaire'),
(86901, 'Glomus jugulare tumour', 'Tumeur du glomus jugulaire'),
(86911, 'Aortic body tumour', 'Tumeur du glomus aortique'),
(86921, 'Carotid body tumour', 'Tumeur du glomus carotidien'),
(86931, 'Extra-adrenal paraganglioma NOS', 'Paragangliome extrasurrénalien SAI'),
(86933, 'Extra-adrenal paraganglioma, malignant', 'Paragangliome extrasurrénalien malin'),
(87000, 'Phaeochromocytoma NOS', 'Phéochromocytome SAI'),
(87003, 'Phaeochromocytoma, malignant', 'Phéochromocytome malin'),
(87103, 'Glomangiosarcoma', 'Glomangiosarcome'),
(87110, 'Glomus tumour', 'Tumeur glomique'),
(87120, 'Glomangioma', 'Glomangiome'),
(87130, 'Glomangiomyoma', 'Glomangiomyome'),
(87200, 'Pigmented naevus NOS', 'Naevus pigmentaire SAI'),
(87202, 'Melanoma in situ', 'Mélanome in situ'),
(87203, 'Malignant melanoma NOS', 'Mélanome malin SAI'),
(87213, 'Nodular melanoma', 'Mélanome nodulaire'),
(87220, 'Balloon cell naevus', 'Naevus à cellules ballonnisantes, ballonnisées'),
(87223, 'Balloon cell melanoma', 'Mélanome à cellules ballonnisantes, ballonnisées'),
(87230, 'Halo naevus', 'Naevus en halo'),
(87233, 'Malignant melanoma, regressing', 'Mélanome malin en voie de régression'),
(87240, 'Fibrous papule of nose', 'Papule fibreuse du nez'),
(87250, 'Neuronaevus', 'Neuronaevus'),
(87260, 'Magnocellular naevus', 'Naevus à grandes cellules'),
(87270, 'Dysplastic naevus', 'Naevus dysplasique'),
(87300, 'Nonpigmented naevus', 'Naevus non pigmentaire'),
(87303, 'Amelanotic melanoma', 'Mélanome achromique'),
(87400, 'Junctional naevus NOS', 'Naevus jonctionnel SAI'),
(87403, 'Malignant melanoma in junctional naevus', 'Mélanome malin présent sur naevus jonctionnel'),
(87412, 'Precancerous melanosis NOS', 'Mélanose précancéreuse SAI'),
(87413, 'Malignant melanoma in precancerousmelanosis', 'Mélanome malin présent sur mélanose précancéreuse'),
(87422, 'Hutchinson''s melanotic freckle NOS', 'Éphélide mélanique de Hutchinson SAI'),
(87423, 'Malignant melanoma in Hutchinson''smelanotic freckle', 'Mélanome malin présent sur éphélide mélanique de Hutchinson'),
(87433, 'Superficial spreading melanoma', 'Mélanome à extension superficielle'),
(87443, 'Acral lentiginous melanoma, malignant', 'Mélanome lentigineux malin des extrémités'),
(87453, 'Desmoplastic melanoma, malignant', 'Mélanome desmoplasique, malin'),
(87500, 'Intradermal naevus', 'Naevus intradermique'),
(87600, 'Compound naevus', 'Naevus composé'),
(87611, 'Giant pigmented naevus NOS', 'Naevus pigmentaire géant SAI'),
(87613, 'Malignant melanoma in giant pigmented naevus', 'Mélanome malin présent sur naevus pigmentaire géant'),
(87700, 'Epithelioid and spindle cell naevus', 'Naevus épithélioïde et fusocellulaire'),
(87703, 'Mixed epithelioid and spindle cellmelanoma', 'Mélanome mixte à cellules épithélioïdes et fusiformes'),
(87710, 'Epithelioid cell naevus', 'Naevus à cellules épithélioïdes'),
(87713, 'Epithelioid cell melanoma', 'Mélanome à cellules épithélioïdes'),
(87720, 'Spindle cell naevus', 'Naevus à cellules fusiformes'),
(87723, 'Spindle cell melanoma NOS', 'Mélanome à cellules fusiformes SAI'),
(87733, 'Spindle cell melanoma, type A', 'Mélanome à cellules fusiformes, type A'),
(87743, 'Spindle cell melanoma, type B', 'Mélanome à cellules fusiformes, type B'),
(87800, 'Blue naevus NOS', 'Naevus bleu SAI'),
(87803, 'Blue naevus, malignant', 'Naevus bleu, malin'),
(87900, 'Cellular blue naevus', 'Naevus bleu cellulaire'),
(88000, 'Soft tissue tumour, benign', 'Tumeur des tissus mous, bénigne'),
(88003, 'Sarcoma NOS', 'Sarcome SAI'),
(88006, 'Sarcomatosis NOS', 'Sarcomatose SAI'),
(88013, 'Spindle cell sarcoma', 'Sarcome à cellules fusiformes'),
(88023, 'Giant cell sarcoma', 'Sarcome à cellules géantes (à l''exception de l''os)'),
(88033, 'Small cell sarcoma', 'Sarcome à petites cellules'),
(88043, 'Epithelioid sarcoma', 'Sarcome à cellules épithélioïdes'),
(88100, 'Fibroma NOS', 'Fibrome SAI'),
(88103, 'Fibrosarcoma NOS', 'Fibrosarcome SAI'),
(88110, 'Fibromyxoma', 'Fibromyxome'),
(88113, 'Fibromyxosarcoma', 'Fibromyxosarcome'),
(88120, 'Periosteal fibroma', 'Fibrome périostéal'),
(88123, 'Periosteal fibrosarcoma', 'Fibrosarcome périostéal'),
(88130, 'Fascial fibroma', 'Fibrome aponévrotique'),
(88133, 'Fascial fibrosarcoma', 'Fibrosarcome aponévrotique'),
(88143, 'Infantile fibrosarcoma', 'Fibrosarcome infantile'),
(88200, 'Elastofibroma', 'Élastofibrome'),
(88211, 'Aggressive fibromatosis', 'Fibromatose agressive'),
(88221, 'Abdominal fibromatosis', 'Fibromatose abdominale'),
(88231, 'Desmoplastic fibroma', 'Fibrome desmoplasique'),
(88241, 'Myofibromatosis', 'Myofibromatose'),
(88300, 'Fibrous histiocytoma NOS', 'Histiocytome fibreux SAI'),
(88301, 'Atypical fibrous histiocytoma', 'Histiocytome fibreux atypique'),
(88303, 'Fibrous histiocytoma, malignant', 'Histiocytome fibreux, malin'),
(88320, 'Dermatofibroma NOS', 'Dermatofibrome SAI'),
(88323, 'Dermatofibrosarcoma NOS', 'Dermatofibrosarcome SAI'),
(88333, 'Pigmented dermatofibrosarcoma protuberans', 'Dermatofibrosarcome protubérant pigmenté'),
(88400, 'Myxoma NOS', 'Myxome SAI'),
(88403, 'Myxosarcoma', 'Myxosarcome'),
(88411, 'Angiomyxoma', 'Angiomyxome'),
(88500, 'Lipoma NOS', 'Lipome SAI'),
(88503, 'Liposarcoma NOS', 'Liposarcome SAI'),
(88510, 'Fibrolipoma', 'Fibrolipome'),
(88513, 'Liposarcoma, well differentiated', 'Liposarcome bien différencié'),
(88520, 'Fibromyxolipoma', 'Fibromyxolipome'),
(88523, 'Myxoid liposarcoma', 'Liposarcome myxoïde'),
(88533, 'Round cell liposarcoma', 'Liposarcome à cellules rondes'),
(88540, 'Pleomorphic lipoma', 'Lipome polymorphe'),
(88543, 'Pleomorphic liposarcoma', 'Liposarcome polymorphe'),
(88553, 'Mixed liposarcoma', 'Liposarcome à cellularité mixte'),
(88560, 'Intramuscular lipoma', 'Lipome intramusculaire'),
(88570, 'Spindle cell lipoma', 'Lipome à cellules fusiformes'),
(88583, 'Dedifferentiated liposarcoma', 'Liposarcome dédifférencié'),
(88600, 'Angiomyolipoma', 'Angiomyolipome'),
(88610, 'Angiolipoma NOS', 'Angiolipome SAI'),
(88700, 'Myelolipoma', 'Myélolipome'),
(88800, 'Hibernoma', 'Hibernome'),
(88810, 'Lipoblastomatosis', 'Lipoblastomatose'),
(88900, 'Leiomyoma NOS', 'Léiomyome SAI'),
(88901, 'Leiomyomatosis NOS', 'Léiomyomatose SAI'),
(88903, 'Leiomyosarcoma NOS', 'Léiomyosarcome SAI'),
(88910, 'Epithelioid leiomyoma', 'Léiomyome épithélioïde'),
(88913, 'Epithelioid leiomyosarcoma', 'Léiomyosarcome épithélioïde'),
(88920, 'Cellular leiomyoma', 'Léiomyome cellulaire'),
(88930, 'Bizarre leiomyoma', 'Léiomyome bizarre'),
(88940, 'Angiomyoma', 'Angiomyome'),
(88943, 'Angiomyosarcoma', 'Angiomyosarcome'),
(88950, 'Myoma', 'Myome'),
(88953, 'Myosarcoma', 'Myosarcome'),
(88963, 'Myxoid leiomyosarcoma', 'Léiomyosarcome myxoïde'),
(88971, 'Smooth muscle tumour NOS', 'Tumeur des muscles lisses SAI'),
(89000, 'Rhabdomyoma NOS', 'Rhabdomyome SAI'),
(89003, 'Rhabdomyosarcoma NOS', 'Rhabdomyosarcome SAI'),
(89013, 'Pleomorphic rhabdomyosarcoma', 'Rhabdomyosarcome polymorphe'),
(89023, 'Mixed type rhabdomyosarcoma', 'Rhabdomyosarcome à cellularité mixte'),
(89030, 'Fetal rhabdomyoma', 'Rhabdomyome foetal'),
(89040, 'Adult rhabdomyoma', 'Rhabdomyome adulte'),
(89103, 'Embryonal rhabdomyosarcoma', 'Rhabdomyosarcome embryonnaire'),
(89203, 'Alveolar rhabdomyosarcoma', 'Rhabdomyosarcome alvéolaire'),
(89300, 'Endometrial stromal nodule', 'Nodule du chorion cytogène'),
(89303, 'Endometrial stromal sarcoma', 'Sarcome du chorion cytogène (endomètre)'),
(89311, 'Endolymphatic stromal myosis', 'Myose stromale endolymphatique'),
(89320, 'Adenomyoma', 'Adénomyome'),
(89333, 'Adenosarcoma', 'Adénosarcome'),
(89400, 'Pleomorphic adenoma', 'Adénome pléomorphe'),
(89403, 'Mixed tumour, malignant NOS', 'Tumeur mixte, maligne SAI'),
(89413, 'Carcinoma in pleomorphic adenoma', 'Carcinome sur adénome pléomorphe'),
(89503, 'M¸llerian mixed tumour', 'Tumeur mixte müllérienne'),
(89513, 'Mesodermal mixed tumour', 'Tumeur mésodermique, mixte'),
(89601, 'Mesoblastic nephroma', 'Néphrome mésoblastique'),
(89603, 'Nephroblastoma NOS', 'Néphroblastome SAI'),
(89633, 'Rhabdoid sarcoma', 'Sarcome rhabdoïde'),
(89643, 'Clear cell sarcoma of kidney', 'Sarcome à cellules claires du rein'),
(89703, 'Hepatoblastoma', 'Hépatoblastome'),
(89713, 'Pancreatoblastoma', 'Pancréatoblastome'),
(89723, 'Pulmonary blastoma', 'Blastome pulmonaire'),
(89803, 'Carcinosarcoma NOS', 'Carcinosarcome SAI'),
(89813, 'Carcinosarcoma, embryonal', 'Carcinosarcome embryonnaire'),
(89820, 'Myoepithelioma', 'Myo-épithéliome'),
(89900, 'Mesenchymoma, benign', 'Mésenchymome bénin'),
(89901, 'Mesenchymoma NOS', 'Mésenchymome SAI'),
(89903, 'Mesenchymoma, malignant', 'Mésenchymome malin'),
(89913, 'Embryonal sarcoma', 'Sarcome embryonnaire'),
(90000, 'Brenner tumour NOS', 'Tumeur de Brenner SAI'),
(90001, 'Brenner tumour, borderline malignancy', 'Tumeur de Brenner, à la limite de la malignité'),
(90003, 'Brenner tumour, malignant', 'Tumeur de Brenner, maligne'),
(90100, 'Fibroadenoma NOS', 'Fibro-adénome SAI'),
(90110, 'Intracanalicular fibroadenoma', 'Fibroadénome intracanaliculaire'),
(90120, 'Pericanalicular fibroadenoma', 'Fibroadénome péricanaliculaire'),
(90130, 'Adenofibroma NOS', 'Adénofibrome SAI'),
(90140, 'Serous adenofibroma', 'Adénofibrome séreux'),
(90150, 'Mucinous adenofibroma', 'Adénofibrome mucineux'),
(90160, 'Giant fibroadenoma', 'Fibro-adénome géant'),
(90200, 'Phyllodes tumour, benign', 'Tumeur phyllode, bénigne'),
(90201, 'Phyllodes tumour NOS', 'Tumeur phyllode SAI'),
(90203, 'Phyllodes tumour, malignant', 'Tumeur phyllode, maligne'),
(90300, 'Juvenile fibroadenoma', 'Fibro-adénome juvénile'),
(90400, 'Synovioma, benign', 'Synoviome bénin'),
(90403, 'Synovial sarcoma NOS', 'Sarcome synovial SAI'),
(90413, 'Synovial sarcoma, spindle cell', 'Sarcome synovial, à cellules fusiformes'),
(90423, 'Synovial sarcoma, epithelioid cell', 'Sarcome synovial, à cellules épithélioïdes'),
(90433, 'Synovial sarcoma, biphasic', 'Sarcome synovial, de type biphasique'),
(90443, 'Clear cell sarcoma', 'Sarcome à cellules claires (sauf rein)'),
(90500, 'Mesothelioma, benign', 'Mésothéliome bénin'),
(90503, 'Mesothelioma, malignant', 'Mésothéliome malin'),
(90510, 'Fibrous mesothelioma, benign', 'Mésothéliome fibreux bénin'),
(90513, 'Fibrous mesothelioma, malignant', 'Mésothéliome fibreux malin'),
(90520, 'Epithelioid mesothelioma, benign', 'Mésothéliome épithélioïde bénin'),
(90523, 'Epithelioid mesothelioma, malignant', 'Mésothéliome épithélioïde malin'),
(90530, 'Mesothelioma, biphasic, benign', 'Mésothéliome biphasique bénin'),
(90533, 'Mesothelioma, biphasic, malignant', 'Mésothéliome biphasique malin'),
(90540, 'Adenomatoid tumour NOS', 'Tumeur adénomatoïde SAI'),
(90551, 'Cystic mesothelioma', 'Mésothéliome kystique'),
(90603, 'Dysgerminoma', 'Dysgerminome'),
(90613, 'Seminoma NOS', 'Séminome SAI'),
(90623, 'Seminoma, anaplastic', 'Séminome anaplasique'),
(90633, 'Spermatocytic seminoma', 'Séminome spermatocytaire'),
(90643, 'Germinoma', 'Germinome'),
(90703, 'Embryonal carcinoma NOS', 'Carcinome embryonnaire SAI'),
(90713, 'Endodermal sinus tumour', 'Tumeur des sinus endodermiques'),
(90723, 'Polyembryoma', 'Polyembryome'),
(90731, 'Gonadoblastoma', 'Gonadoblastome'),
(90800, 'Teratoma, benign', 'Tératome bénin'),
(90801, 'Teratoma NOS', 'Tératome SAI'),
(90803, 'Teratoma, malignant NOS', 'Tératome malin SAI'),
(90813, 'Teratocarcinoma', 'Tératocarcinome'),
(90823, 'Malignant teratoma, undifferentiated', 'Tératome malin de type indifférencié'),
(90833, 'Malignant teratoma, intermediate', 'Tératome malin de type intermédiaire'),
(90840, 'Dermoid cyst NOS', 'Kyste dermoïde SAI'),
(90843, 'Teratoma with malignant transformation', 'Tératome avec transformation maligne'),
(90853, 'Mixed germ cell tumour', 'Tumeur mixte, à cellules germinales'),
(90900, 'Struma ovarii NOS', 'Goitre ovarien SAI'),
(90903, 'Struma ovarii, malignant', 'Goitre ovarien malin'),
(90911, 'Strumal carcinoid', 'Carcinoïde ovarien'),
(91000, 'Hydatidiform mole NOS', 'Môle hydatiforme SAI'),
(91001, 'Invasive hydatidiform mole', 'Môle hydatidiforme invasive'),
(91003, 'Choriocarcinoma NOS', 'Choriocarcinome SAI'),
(91013, 'Choriocarcinoma combined with other germ cell elements', 'Choriocarcinome associé à d''autres éléments à cellules germinales'),
(91023, 'Malignant teratoma, trophoblastic', 'Tératome malin trophoblastique'),
(91030, 'Partial hydatidiform mole', 'Môle hydatidiforme partielle'),
(91041, 'Placental site trophoblastic tumour', 'Tumeur trophoblastique, siège placentaire'),
(91100, 'Mesonephroma, benign', 'Mésonéphrome bénin'),
(91101, 'Mesonephric tumour', 'Tumeur mésonéphrique'),
(91103, 'Mesonephroma, malignant', 'Mésonéphrome malin'),
(91200, 'Haemangioma NOS', 'Hémangiome SAI'),
(91203, 'Haemangiosarcoma', 'Hémangiosarcome'),
(91210, 'Cavernous haemangioma', 'Hémangiome caverneux'),
(91220, 'Venous haemangioma', 'Hémangiome veineux'),
(91230, 'Racemose haemangioma', 'Hémangiome racémeux'),
(91243, 'Kupffer cell sarcoma', 'Sarcome des cellules de Kupffer'),
(91250, 'Epithelioid haemangioma', 'Hémangiome épithélioïde'),
(91260, 'Histiocytoid haemangioma', 'Hémangiome histiocytoïde'),
(91300, 'Haemangioendothelioma, benign', 'Hémangio-endothéliome bénin'),
(91301, 'Haemangioendothelioma NOS', 'Hémangio-endothéliome SAI'),
(91303, 'Haemangioendothelioma, malignant', 'Hémangio-endothéliome malin'),
(91310, 'Capillary haemangioma', 'Hémangiome capillaire'),
(91320, 'Intramuscular haemangioma', 'Hémangiome intramusculaire'),
(91331, 'Epithelioid haemangioendotheliomaNOS', 'Hémangio-endothéliome épithélioïde SAI'),
(91333, 'Epithelioid haemangioendothelioma,malignant', 'Hémangio-endothéliome épithélioïde malin'),
(91341, 'Intravascular bronchial alveolar tumour', 'Tumeur bronchique alvéolaire intravasculaire'),
(91403, 'Kaposi''s sarcoma', 'Sarcome de Kaposi'),
(91410, 'Angiokeratoma', 'Angiokératome'),
(91420, 'Verrucous keratotic haemangioma', 'Hémangiome verruqueux kératosique'),
(91500, 'Haemangiopericytoma, benign', 'Hémangiopéricytome bénin'),
(91501, 'Haemangiopericytoma NOS', 'Hémangiopéricytome SAI'),
(91503, 'Haemangiopericytoma, malignant', 'Hémangiopéricytome malin'),
(91600, 'Angiofibroma NOS', 'Angiofibrome SAI'),
(91611, 'Haemangioblastoma', 'Hémangioblastome'),
(91700, 'Lymphangioma NOS', 'Lymphangiome SAI'),
(91703, 'Lymphangiosarcoma', 'Lymphangiosarcome'),
(91710, 'Capillary lymphangioma', 'Lymphangiome capillaire'),
(91720, 'Cavernous lymphangioma', 'Lymphangiome caverneux'),
(91730, 'Cystic lymphangioma', 'Lymphangiome kystique'),
(91740, 'Lymphangiomyoma', 'Lymphangiomyome'),
(91741, 'Lymphangiomyomatosis', 'Lymphangiomyomatose'),
(91750, 'Haemolymphangioma', 'Hémolymphangiome'),
(91800, 'Osteoma NOS', 'Ostéome SAI'),
(91803, 'Osteosarcoma NOS', 'Ostéosarcome SAI'),
(91813, 'Chondroblastic osteosarcoma', 'Ostéosarcome chondroblastique'),
(91823, 'Fibroblastic osteosarcoma', 'Ostéosarcome fibroblastique'),
(91833, 'Telangiectatic osteosarcoma', 'Ostéosarcome télangiectasique'),
(91843, 'Osteosarcoma in Paget''s disease ofbone', 'Ostéosarcome sur maladie osseuse de Paget'),
(91853, 'Small cell osteosarcoma', 'Ostéosarcome à petites cellules'),
(91903, 'Juxtacortical osteosarcoma', 'Ostéosarcome juxtacortical'),
(91910, 'Osteoid osteoma NOS', 'Ostéome ostéoïde SAI'),
(92000, 'Osteoblastoma NOS', 'Ostéoblastome SAI'),
(92001, 'Aggressive osteoblastoma', 'Ostéoblastome agressif'),
(92100, 'Osteochondroma', 'Ostéochondrome'),
(92101, 'Osteochondromatosis NOS', 'Ostéochondromatose SAI'),
(92200, 'Chondroma NOS', 'Chondrome SAI'),
(92201, 'Chondromatosis NOS', 'Chondromatose SAI'),
(92203, 'Chondrosarcoma NOS', 'Chondrosarcome SAI'),
(92210, 'Juxtacortical chondroma', 'Chondrome juxtacortical'),
(92213, 'Juxtacortical chondrosarcoma', 'Chondrosarcome juxtacortical'),
(92300, 'Chondroblastoma NOS', 'Chondroblastome SAI'),
(92303, 'Chondroblastoma, malignant', 'Chondroblastome malin'),
(92313, 'Myxoid chondrosarcoma', 'Chondrosarcome myxoïde'),
(92403, 'Mesenchymal chondrosarcoma', 'Chondrosarcome mésenchymateux'),
(92410, 'Chondromyxoid fibroma', 'Fibrome chondromyxoïde'),
(92501, 'Giant cell tumour of bone NOS', 'Ostéoclastome SAI'),
(92503, 'Giant cell tumour of bone, malignant', 'Ostéoclastome malin'),
(92511, 'Giant cell tumour of soft parts NOS', 'Tumeur à cellules géantes des tissus mous SAI'),
(92513, 'Malignant giant cell tumour of soft parts', 'Tumeur à cellules géantes des tissus mous, maligne'),
(92603, 'Ewing''s sarcoma', 'Sarcome d''Ewing'),
(92613, 'Adamantinoma of long bones', 'Adamantinome des os longs'),
(92620, 'Ossifying fibroma', 'Fibrome ossifiant'),
(92700, 'Odontogenic tumour, benign', 'Tumeur odontogénique bénigne'),
(92701, 'Odontogenic tumour NOS', 'Tumeur odontogénique SAI'),
(92703, 'Odontogenic tumour, malignant', 'Tumeur odontogénique maligne'),
(92710, 'Dentinoma', 'Dentinome'),
(92720, 'Cementoma NOS', 'Cémentome SAI'),
(92730, 'Cementoblastoma, benign', 'Cémentoblastome bénin'),
(92740, 'Cementifying fibroma', 'Fibrome cémentifiant'),
(92750, 'Gigantiform cementoma', 'Cémentome géant'),
(92800, 'Odontoma NOS', 'Odontome SAI'),
(92810, 'Compound odontoma', 'Odontome composé'),
(92820, 'Complex odontoma', 'Odontome complexe'),
(92900, 'Ameloblastic fibro-odontoma', 'Fibro-odontome améloblastique'),
(92903, 'Ameloblastic odontosarcoma', 'Odontosarcome améloblastique'),
(93000, 'Adenomatoid odontogenic tumour', 'Tumeur odontogénique de type adénomatoïde'),
(93010, 'Calcifying odontogenic cyst', 'Kyste odontogénique calcifiant'),
(93020, 'Odontogenic ghost cell tumour', 'Tumeur odontogénique à cellules pâles'),
(93100, 'Ameloblastoma NOS', 'Améloblastome SAI'),
(93103, 'Ameloblastoma, malignant', 'Améloblastome malin'),
(93110, 'Odontoameloblastoma', 'Odonto-améloblastome'),
(93120, 'Squamous odontogenic tumour', 'Tumeur odontogène spino-cellulaire'),
(93200, 'Odontogenic myxoma', 'Myxome odontogène'),
(93210, 'Central odontogenic fibroma', 'Fibrome odontogène central'),
(93220, 'Peripheral odontogenic fibroma', 'Fibrome odontogène périphérique'),
(93300, 'Ameloblastic fibroma', 'Fibrome améloblastique'),
(93303, 'Ameloblastic fibrosarcoma', 'Fibrosarcome améloblastique'),
(93400, 'Calcifying epithelial odontogenictumour', 'Tumeur odontogène épithéliale calcifiante'),
(93501, 'Craniopharyngioma', 'Craniopharyngiome'),
(93601, 'Pinealoma', 'Pinéalome'),
(93611, 'Pineocytoma', 'Pinéocytome'),
(93623, 'Pineoblastoma', 'Pinéoblastome'),
(93630, 'Melanotic neuroectodermal tumour', 'Tumeur mélanique neuro-ectodermique'),
(93643, 'Peripheral neuroectodermal tumour', 'Tumeur neuro-ectodermique périphérique'),
(93703, 'Chordoma', 'Chordome'),
(93803, 'Glioma, malignant', 'Gliome malin'),
(93813, 'Gliomatosis cerebri', 'Gliomatose du cerveau'),
(93823, 'Mixed glioma', 'Gliome mixte'),
(93831, 'Subependymal glioma', 'Gliome sous-épendymaire'),
(93841, 'Subependymal giant cell astrocytoma', 'Astrocytome sous-épendymaire à cellules géantes'),
(93900, 'Choroid plexus papilloma NOS', 'Papillome des plexus choroïdes'),
(93903, 'Choroid plexus papilloma, malignant', 'Papillome malin des plexus choroïdes'),
(93913, 'Ependymoma NOS', 'Épendymome SAI'),
(93923, 'Ependymoma, anaplastic', 'Épendymome anaplasique'),
(93931, 'Papillary ependymoma', 'Épendymome papillaire'),
(93941, 'Myxopapillary ependymoma', 'Épendymome myxopapillaire'),
(94003, 'Astrocytoma NOS', 'Astrocytome SAI'),
(94013, 'Astrocytoma, anaplastic', 'Astrocytome anaplasique'),
(94103, 'Protoplasmic astrocytoma', 'Astrocytome protoplasmique'),
(94113, 'Gemistocytic astrocytoma', 'Astrocytome gémistocytique'),
(94203, 'Fibrillary astrocytoma', 'Astrocytome fibrillaire'),
(94213, 'Pilocytic astrocytoma', 'Astrocytome pilocytique'),
(94223, 'Spongioblastoma NOS', 'Spongioblastome SAI'),
(94233, 'Spongioblastoma polare', 'Spongioblastome polaire'),
(94243, 'Pleomorphic xanthoastrocytoma', 'Xanthoastrocytome pléomorphe'),
(94303, 'Astroblastoma', 'Astroblastome'),
(94403, 'Glioblastoma NOS', 'Glioblastome SAI'),
(94413, 'Giant cell glioblastoma', 'Glioblastome à cellules géantes'),
(94423, 'Gliosarcoma', 'Gliosarcome'),
(94433, 'Primitive polar spongioblastoma', 'Spongioblastome polaire primitif'),
(94503, 'Oligodendroglioma NOS', 'Oligodendrogliome SAI'),
(94513, 'Oligodendroglioma, anaplastic', 'Oligodendrogliome anaplasique'),
(94603, 'Oligodendroblastoma', 'Oligodendroblastome'),
(94703, 'Medulloblastoma NOS', 'Médulloblastome SAI'),
(94713, 'Desmoplastic medulloblastoma', 'Médulloblastome desmoplasique'),
(94723, 'Medullomyoblastoma', 'Médullomyoblastome'),
(94733, 'Primitive neuroectodermal tumour', 'Tumeur neuro-ectodermique primitive'),
(94803, 'Cerebellar sarcoma NOS', 'Sarcome cérébelleux SAI'),
(94813, 'Monstrocellular sarcoma', 'Sarcome monstrocellulaire'),
(94900, 'Ganglioneuroma', 'Ganglioneurome'),
(94903, 'Ganglioneuroblastoma', 'Ganglioneuroblastome'),
(94910, 'Ganglioneuromatosis', 'Ganglioneuromatose'),
(95003, 'Neuroblastoma NOS', 'Neuroblastome SAI'),
(95013, 'Medulloepithelioma NOS', 'Médullo-épithéliome SAI'),
(95023, 'Teratoid medulloepithelioma', 'Médullo-épithéliome tératoïde'),
(95033, 'Neuroepithelioma NOS', 'Neuro-épithéliome SAI'),
(95043, 'Spongioneuroblastoma', 'Spongioneuroblastome'),
(95051, 'Ganglioglioma', 'Gangliogliome'),
(95060, 'Neurocytoma', 'Neurocytome'),
(95070, 'Pacinian tumour', 'Tumeur des corpuscules de Pacini'),
(95103, 'Retinoblastoma NOS', 'Rétinoblastome SAI'),
(95113, 'Retinoblastoma, differentiated', 'Rétinoblastome différencié'),
(95123, 'Retinoblastoma, undifferentiated', 'Rétinoblastome indifférencié'),
(95203, 'Olfactory neurogenic tumour', 'Tumeur neurogénique olfactive'),
(95213, 'Esthesioneurocytoma', 'Esthésioneurocytome'),
(95223, 'Esthesioneuroblastoma', 'Esthésioneuroblastome'),
(95233, 'Esthesioneuroepithelioma', 'Esthésioneuro-épithéliome'),
(95300, 'Meningioma NOS', 'Méningiome SAI'),
(95301, 'Meningiomatosis NOS', 'Méningiomatose SAI'),
(95303, 'Meningioma, malignant', 'Méningiome malin'),
(95310, 'Meningotheliomatous meningioma', 'Méningiome méningothéliomateux'),
(95320, 'Fibrous meningioma', 'Méningiome fibreux'),
(95330, 'Psammomatous meningioma', 'Méningiome psammomateux'),
(95340, 'Angiomatous meningioma', 'Méningiome angiomateux'),
(95350, 'Haemangioblastic meningioma', 'Méningiome hémangioblastique'),
(95360, 'Haemangiopericytic meningioma', 'Méningiome hémangiopéricytique'),
(95370, 'Transitional meningioma', 'Méningiome transitionnel'),
(95381, 'Papillary meningioma', 'Méningiome papillaire'),
(95393, 'Meningeal sarcomatosis', 'Sarcomatose méningée'),
(95400, 'Neurofibroma NOS', 'Neurofibrome SAI'),
(95401, 'Neurofibromatosis NOS', 'Neurofibromatose SAI'),
(95403, 'Neurofibrosarcoma', 'Neurofibrosarcome'),
(95410, 'Melanotic neurofibroma', 'Neurofibrome mélanique'),
(95500, 'Plexiform neurofibroma', 'Neurofibrome plexiforme'),
(95600, 'Neurilemmoma NOS', 'Neurilemmome SAI'),
(95601, 'Neurinomatosis', 'Neurinomatose'),
(95603, 'Neurilemmoma, malignant', 'Neurilemmome malin'),
(95613, 'Triton tumour, malignant', 'Tumeur de Triton maligne'),
(95620, 'Neurothekeoma', 'Neurothécome'),
(95700, 'Neuroma NOS', 'Neurome SAI'),
(95800, 'Granular cell tumour NOS', 'Tumeur à cellules granuleuses SAI'),
(95803, 'Granular cell tumour, malignant', 'Tumeur maligne à cellules granuleuses'),
(95813, 'Alveolar soft part sarcoma', 'Sarcome alvéolaire des tissus mous'),
(95903, 'Malignant lymphoma NOS', 'Lymphome malin SAI'),
(95913, 'Malignant lymphoma, non-Hodgkin''sNOS', 'Lymphome malin, non hodgkinien, SAI'),
(95933, 'Reticulosarcoma NOS', 'Réticulosarcome SAI'),
(95943, 'Microglioma', 'Microgliome'),
(95953, 'Malignant lymphoma, diffuse NOS', 'Lymphome malin diffus SAI'),
(96503, 'Hodgkin''s disease NOS', 'Maladie de Hodgkin SAI'),
(96523, 'Hodgkin''s disease, mixed cellularity NOS', 'Maladie de Hodgkin à cellularité mixte SAI'),
(96533, 'Hodgkin''s disease, lymphocytic depletion NOS', 'Maladie de Hodgkin, déplétion lymphocytaire SAI'),
(96543, 'Hodgkin''s disease, lymphocytic depletion, diffuse fibrosis', 'Maladie de Hodgkin, déplétion lymphocytaire, type fibrose diffuse'),
(96553, 'Hodgkin''s disease, lymphocytic depletion, reticular', 'Maladie de Hodgkin, déplétion lymphocytaire, type réticulaire'),
(96573, 'Hodgkin''s disease, lymphocytic predominance NOS', 'Maladie de Hodgkin, prédominance lymphocytaire SAI'),
(96583, 'Hodgkin''s disease, lymphocytic predominance, diffuse', 'Maladie de Hodgkin, prédominance lymphocytaire, diffuse'),
(96593, 'Hodgkin''s disease, lymphocytic predominance, nodular', 'Maladie de Hodgkin, prédominance lymphocytaire, nodulaire'),
(96603, 'Hodgkin''s paragranuloma NOS', 'Paragranulome hodgkinien SAI'),
(96613, 'Hodgkin''s granuloma', 'Granulome hodgkinien'),
(96623, 'Hodgkin''s sarcoma', 'Sarcome hodgkinien'),
(96633, 'Hodgkin''s disease, nodular sclerosis NOS', 'Maladie de Hodgkin, sclérose nodulaire SAI'),
(96643, 'Hodgkin''s disease, nodular sclerosis, cellular phase', 'Maladie de Hodgkin, sclérose nodulaire, phase cellulaire'),
(96653, 'Hodgkin''s disease, nodular sclerosis, lymphocytic predominance', 'Maladie de Hodgkin, sclérose nodulaire, prédominance lymphocytaire'),
(96663, 'Hodgkin''s disease, nodular sclerosis, mixed cellularity', 'Maladie de Hodgkin, sclérose nodulaire, à cellularité mixte'),
(96673, 'Hodgkin''s disease, nodular sclerosis, lymphocytic depletion', 'Maladie de Hodgkin, sclérose nodulaire, déplétion lymphocytaire'),
(96703, 'Malignant lymphoma, small lymphocytic NOS', 'Lymphome malin, à petites cellules SAI'),
(96713, 'Malignant lymphoma, lymphoplasmacytic', 'Lymphome malin, lymphoplasmocytaire'),
(96723, 'Malignant lymphoma, small cleavedcell, diffuse', 'Lymphome malin, à petites cellules encochées, diffus'),
(96733, 'Malignant lymphoma, lymphocytic, intermediate differentiation, diffuse', 'Lymphome malin, lymphocytaire, à différentiation intermédiaire, diffus'),
(96743, 'Malignant lymphoma, centrocytic', 'Lymphome malin, centrocytaire'),
(96753, 'Malignant lymphoma, mixed small and large cell, diffuse', 'Lymphome malin, mixte, à petites cellules et grandes cellules, diffus'),
(96763, 'Malignant lymphoma, centroblastic-centrocytic, diffuse', 'Lymphome malin, centroblastique-centrocytique, diffus'),
(96773, 'Malignant lymphomatous polyposis', 'Polypose lymphomateuse maligne'),
(96803, 'Malignant lymphoma, large cell, diffuse NOS', 'Lymphome malin, à grandes cellules, diffus SAI'),
(96813, 'Malignant lymphoma, large cell, cleaved, diffuse', 'Lymphome malin, à grandes cellules encochées, diffus'),
(96823, 'Malignant lymphoma, large cell, noncleaved, diffuse', 'Lymphome malin, à grandes cellules non encochées, diffus'),
(96833, 'Malignant lymphoma, centroblastic,diffuse', 'Lymphome malin, centroblastique, diffus'),
(96843, 'Malignant lymphoma, immunoblasticNOS', 'Lymphome malin, immunoblastique SAI'),
(96853, 'Malignant lymphoma, lymphoblastic', 'Lymphome malin, lymphoblastique'),
(96863, 'Malignant lymphoma, small cell, noncleaved, diffuse', 'Lymphome malin, à petites cellules non encochées, diffus'),
(96873, 'Burkitt''s lymphoma NOS', 'Lymphome de Burkitt SAI'),
(96903, 'Malignant lymphoma, follicular NOS', 'Lymphome malin, folliculaire SAI');
INSERT INTO `coding_icd_o_3_morphology` VALUES
(96913, 'Malignant lymphoma, mixed small cleaved and large cell, follicular', 'Lymphome malin, mixte, à petites cellules et grandes cellules, folliculaire'),
(96923, 'Malignant lymphoma, centroblastic-centrocytic, follicular', 'Lymphome malin, centroblastique-centrocytique, folliculaire'),
(96933, 'Malignant lymphoma, lymphocytic, well differentiated, nodular', 'Lymphome malin, lymphocytaire, bien différencié, nodulaire'),
(96943, 'Malignant lymphoma, lymphocytic, intermediate differentiation, nodular', 'Lymphome malin, lymphocytaire, à différentiation intermédiaire, nodulaire'),
(96953, 'Malignant lymphoma, small cleavedcell, follicular', 'Lymphome malin, à petites cellules encochées, folliculaire'),
(96963, 'Malignant lymphoma, lymphocytic, poorly differentiated, nodular', 'Lymphome malin, lymphocytaire, peu différencié, nodulaire'),
(96973, 'Malignant lymphoma, centroblastic,follicular', 'Lymphome malin, centroblastique, folliculaire'),
(96983, 'Malignant lymphoma, large cell, follicular NOS', 'Lymphome malin, à grandes cellules, folliculaire SAI'),
(97003, 'Mycosis fungoides', 'Mycosis fongoïde'),
(97013, 'SÈzary''s disease', 'Réticulose de Sézary'),
(97023, 'Peripheral T-cell lymphoma NOS', 'Lymphome périphérique à cellules T SAI'),
(97053, 'Peripheral T-cell lymphoma, AILD (angioimmunoblastic lymphadenopathy with dysproteinaemia)', 'Lymphome périphérique à cellules T, type LAID (lymphadénopathie angio-immunoblastique avec dysprotéinémie)'),
(97063, 'Peripheral T-cell lymphoma, pleomorphic small cell', 'Lymphome périphérique à cellules T, petites cellules pléomorphes'),
(97073, 'Peripheral T-cell lymphoma, pleomorphic medium and large cell', 'Lymphome périphérique à cellules T, cellules moyennes et grandes pléomorphes'),
(97093, 'Cutaneous lymphoma', 'Lymphome cutané'),
(97113, 'Monocytoid B-cell lymphoma', 'Lymphome à cellules B monocytoïdes'),
(97123, 'Angioendotheliomatosis', 'Angioendothéliomatose'),
(97133, 'Angiocentric T-cell lymphoma', 'Lymphome à cellules T angiocentrique'),
(97143, 'Large cell (Ki-1+) lymphoma', 'Lymphome à grandes cellules (Ki-1+)'),
(97203, 'Malignant histiocytosis', 'Histiocytose maligne'),
(97223, 'Letterer-Siwe disease', 'Maladie de Letterer-Siwe'),
(97233, 'True histiocytic lymphoma', 'Lymphome histiocytaire vrai'),
(97313, 'Plasmacytoma NOS', 'Plasmocytome SAI'),
(97323, 'Multiple myeloma', 'Myélome multiple'),
(97401, 'Mastocytoma NOS', 'Mastocytome SAI'),
(97403, 'Mast cell sarcoma', 'Sarcome à mastocytes'),
(97413, 'Malignant mastocytosis', 'Mastocytose maligne'),
(97603, 'Immunoproliferative disease NOS', 'Maladie immunoproliférative SAI'),
(97613, 'Waldenstrˆm''s macroglobulinaemia', 'Macroglobulinémie de Waldenström'),
(97623, 'Alpha heavy chain disease', 'Maladie des chaînes lourdes alpha'),
(97633, 'Gamma heavy chain disease', 'Maladie des chaînes lourdes gamma'),
(97643, 'Immunoproliferative small intestinal disease', 'Maladie immunoproliférative de l''intestin grêle'),
(97651, 'Monoclonal gammopathy', 'Gammapathie monoclonale'),
(97661, 'Angiocentric immunoproliferative lesion', 'Lésion immunoproliférative angiocentrique'),
(97671, 'Angioimmunoblastic lymphadenopathy', 'Lymphadénopathie angio-immunoblastique'),
(97681, 'T-gamma lymphoproliferative disease', 'Maladie lymphoproliférative, type T-gamma'),
(98003, 'Leukaemia NOS', 'Leucémie SAI'),
(98013, 'Acute leukaemia NOS', 'Leucémie aiguë SAI'),
(98023, 'Subacute leukaemia NOS', 'Leucémie subaiguë SAI'),
(98033, 'Chronic leukaemia NOS', 'Leucémie chronique SAI'),
(98043, 'Aleukaemic leukaemia NOS', 'Leucémie aleucémique SAI'),
(98203, 'Lymphoid leukaemia NOS', 'Leucémie lymphoïde SAI'),
(98213, 'Acute lymphoblastic leukaemia NOS', 'Leucémie lymphoblastique aiguë SAI'),
(98223, 'Subacute lymphoid leukaemia', 'Leucémie lymphoïde subaiguë'),
(98233, 'Chronic lymphocytic leukaemia', 'Leucémie lymphocytaire chronique'),
(98243, 'Aleukaemic lymphoid leukaemia', 'Leucémie lymphoïde aleucémique'),
(98253, 'Prolymphocytic leukaemia', 'Leucémie à prolymphocytes'),
(98263, 'Burkitt''s cell leukaemia', 'Leucémie à cellules de Burkitt'),
(98273, 'Adult T-cell leukaemia/lymphoma', 'Leucémie/Lymphome de l''adulte à cellules T'),
(98303, 'Plasma cell leukaemia', 'Leucémie à plasmocytes'),
(98403, 'Erythroleukaemia', 'Érythroleucose'),
(98413, 'Acute erythraemia', 'Polyglobulie primitive aiguë'),
(98423, 'Chronic erythraemia', 'Polyglobulie primitive chronique'),
(98503, 'Lymphosarcoma cell leukaemia', 'Lymphosarcome leucémique'),
(98603, 'Myeloid leukaemia NOS', 'Leucémie myéloïde SAI'),
(98613, 'Acute myeloid leukaemia', 'Leucémie myéloïde aiguë'),
(98623, 'Subacute myeloid leukaemia', 'Leucémie myéloïde subaiguë'),
(98633, 'Chronic myeloid leukaemia', 'Leucémie myéloïde chronique'),
(98643, 'Aleukaemic myeloid leukaemia', 'Leucémie myéloïde aleucémique'),
(98663, 'Acute promyelocytic leukaemia', 'Leucémie promyélocytaire aiguë'),
(98673, 'Acute myelomonocytic leukaemia', 'Leucémie myélomonocytaire aiguë'),
(98683, 'Chronic myelomonocytic leukaemia', 'Leucémie myélomonocytaire chronique'),
(98703, 'Basophilic leukaemia', 'Leucémie basophile'),
(98803, 'Eosinophilic leukaemia', 'Leucémie à éosinophiles'),
(98903, 'Monocytic leukaemia NOS', 'Leucémie monocytaire SAI'),
(98913, 'Acute monocytic leukaemia', 'Leucémie monocytaire aiguë'),
(98923, 'Subacute monocytic leukaemia', 'Leucémie monocytaire subaiguë'),
(98933, 'Chronic monocytic leukaemia', 'Leucémie monocytaire chronique'),
(98943, 'Aleukaemic monocytic leukaemia', 'Leucémie monocytaire aleucémique'),
(99003, 'Mast cell leukaemia', 'Leucémie à mastocytes'),
(99103, 'Acute megakaryoblastic leukaemia', 'Leucémie aiguë à mégacaryocytes'),
(99303, 'Myeloid sarcoma', 'Sarcome myéloïde'),
(99313, 'Acute panmyelosis', 'Panmyélose aiguë'),
(99323, 'Acute myelofibrosis', 'Myélofibrose aiguë'),
(99403, 'Hairy cell leukaemia', 'Leucémie à tricholeucocytes'),
(99413, 'Leukaemic reticuloendotheliosis', 'Réticulo-endothéliose leucémique'),
(99501, 'Polycythaemia vera', 'Polyglobulie essentielle'),
(99601, 'Chronic myeloproliferative disease', 'Maladie myéloproliférative chronique'),
(99611, 'Myelosclerosis with myeloid metaplasia', 'Myélosclérose avec métaplasie myéloïde'),
(99621, 'Idiopathic thrombocythaemia', 'Thrombocytémie idiopathique'),
(99701, 'Lymphoproliferative disease NOS', 'Maladie lymphoproliférative SAI'),
(99801, 'Refractory anaemia NOS', 'Anémie réfractaire SAI'),
(99811, 'Refractory anaemia without sideroblasts', 'Anémie réfractaire non sidéroblastique'),
(99821, 'Refractory anaemia with sideroblasts', 'Anémie réfractaire sidéroblastique'),
(99831, 'Refractory anaemia with excess ofblasts', 'Anémie réfractaire avec excès de blastes'),
(99841, 'Refractory anaemia with excess ofblasts with transformation', 'Anémie réfractaire avec excès de blastes en transformation'),
(99891, 'Myelodysplastic syndrome NOS', 'Syndrome myélodysplasique SAI');