-- Add aliquot_label

UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters_for_collection_tree_view') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters_for_storage_tree_view') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='1',flag_edit_readonly='1',flag_search='0',flag_addgrid='1',flag_addgrid_readonly='1',flag_editgrid='1',flag_editgrid_readonly='1',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='sourcealiquots') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='1',flag_addgrid_readonly='1',flag_editgrid='1',flag_editgrid_readonly='1',flag_index='0',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='children_aliquots_selection') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='1',flag_edit_readonly='1',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='realiquotedparent') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='1',flag_edit_readonly='1',flag_search='1',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='1',flag_summary='0',flag_float='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='1',flag_edit_readonly='1',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='0',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='used_aliq_in_stock_details') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='1',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='qualityctrls') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquotinternaluses') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='1',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters_for_storage_list_view') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='1',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='procure_transferred_aliquots_details') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='1',flag_editgrid_readonly='0',flag_index='0',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='procure_aliquot_barcode_and_label_update') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='1',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='0',flag_editgrid_readonly='0',flag_index='1',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='view_aliquot_joined_to_sample_and_collection') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					
UPDATE structure_formats SET flag_edit='0',flag_edit_readonly='0',flag_search='0',flag_addgrid='0',flag_addgrid_readonly='0',flag_editgrid='1',flag_editgrid_readonly='1',flag_index='0',flag_detail='0',flag_summary='0',flag_float='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='procure_aliquot_barcode_and_label_update') AND structure_field_id IN (SELECT id FROM structure_fields WHERE `field`='aliquot_label');					

REPLACE INTO i18n (id,en,fr) VALUES ('aliquot label','Label (CHUS)','Étiquette (CHUS)');
UPDATE structure_formats SET `display_order`='300' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
UPDATE structure_formats SET `display_order`='200' WHERE structure_id=(SELECT id FROM structures WHERE alias='aliquot_masters') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='barcode' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `margin`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='ad_spec_tiss_blocks'), (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='aliquot label' AND `language_tag`=''), '0', '300', '', '0', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1');
UPDATE structure_formats SET `flag_addgrid`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='ad_spec_tiss_blocks') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');
INSERT INTO structure_formats(`structure_id`, `structure_field_id`, `display_column`, `display_order`, `language_heading`, `margin`, `flag_override_label`, `language_label`, `flag_override_tag`, `language_tag`, `flag_override_help`, `language_help`, `flag_override_type`, `type`, `flag_override_setting`, `setting`, `flag_override_default`, `default`, `flag_add`, `flag_add_readonly`, `flag_edit`, `flag_edit_readonly`, `flag_search`, `flag_search_readonly`, `flag_addgrid`, `flag_addgrid_readonly`, `flag_editgrid`, `flag_editgrid_readonly`, `flag_batchedit`, `flag_batchedit_readonly`, `flag_index`, `flag_detail`, `flag_summary`, `flag_float`) VALUES 
((SELECT id FROM structures WHERE alias='ad_spec_tiss_slides'), (SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label' AND `type`='input' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0' AND `setting`='' AND `default`='' AND `language_help`='' AND `language_label`='aliquot label' AND `language_tag`=''), '0', '300', '', '0', '0', '', '0', '', '0', '', '0', '', '0', '', '0', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1');
UPDATE structure_formats SET `flag_addgrid`='1' WHERE structure_id=(SELECT id FROM structures WHERE alias='ad_spec_tiss_slides') AND structure_field_id=(SELECT id FROM structure_fields WHERE `model`='AliquotMaster' AND `tablename`='aliquot_masters' AND `field`='aliquot_label' AND `structure_value_domain`  IS NULL  AND `flag_confidential`='0');

UPDATE versions SET permissions_regenerated = 0;
UPDATE versions SET site_branch_build_number = '6372' WHERE version_number = '2.6.6';