<?php
/** **********************************************************************
 * CHUM-BioTransit Project
 * ***********************************************************************
 *
 * InventoryManagement plugin custom code
 *
 * @author N. Luc - CTRNet (nicolas.luc@gmail.com)
 * @since 2018-10-22
 */

// --------------------------------------------------------------------------------
// Only barcode generated by the system can be updated
// --------------------------------------------------------------------------------

if ($aliquotData['AliquotMaster']['barcode'] != $this->request->data['AliquotMaster']['barcode']) {
    // Validate barcode is different than barcodes generated by the system
    
    
    if (preg_match('/^atim#/i', $this->request->data['AliquotMaster']['barcode'])) {
        $this->AliquotMaster->validationErrors['barcode'][] = 'error barcode should be different than system barcode';
        $submittedDataValidates = false;
    }   else if (!preg_match('/^atim#/i', $aliquotData['AliquotMaster']['barcode'])) {
        $this->AliquotMaster->validationErrors['barcode'][] = 'only barcode generated by the system can be updated';
        $submittedDataValidates = false;
    }
}